      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. ARITHMETIC.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-MAX-X  PIC S9(18).
       01 WS-MAX-Y  PIC S9(18).
       01 WS-MAX-RET     PIC S9(18).
       01 WS-ABS-X  PIC S9(18).
       01 WS-ABS-RET     PIC S9(18).
       01 WS-CLAMP-LO  PIC S9(18).
       01 WS-CLAMP-HI  PIC S9(18).
       01 WS-CLAMP-X  PIC S9(18).
       01 WS-CLAMP-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       MAX-PARA.
           IF WS-X > WS-Y
             MOVE 1 TO WS-V0001
           ELSE
             MOVE 0 TO WS-V0001
           END-IF
           IF WS-V0001 NOT = 0
             MOVE WS-X TO WS-V0002
           ELSE
             MOVE WS-Y TO WS-V0002
           END-IF
           MOVE WS-V0002 TO WS-MAX-RET

       ABS-PARA.
           IF WS-X < 0
             MOVE 1 TO WS-V0003
           ELSE
             MOVE 0 TO WS-V0003
           END-IF
           IF WS-V0003 NOT = 0
           MULTIPLY WS-X BY -1 GIVING WS-V0005
             MOVE WS-V0005 TO WS-V0004
           ELSE
             MOVE WS-X TO WS-V0004
           END-IF
           MOVE WS-V0004 TO WS-ABS-RET

       CLAMP-PARA.
           IF WS-X < WS-LO
             MOVE 1 TO WS-V0006
           ELSE
             MOVE 0 TO WS-V0006
           END-IF
           IF WS-V0006 NOT = 0
             MOVE WS-LO TO WS-V0007
           ELSE
           IF WS-X > WS-HI
             MOVE 1 TO WS-V0008
           ELSE
             MOVE 0 TO WS-V0008
           END-IF
           IF WS-V0008 NOT = 0
             MOVE WS-HI TO WS-V0009
           ELSE
             MOVE WS-X TO WS-V0009
           END-IF
             MOVE WS-V0009 TO WS-V0007
           END-IF
           MOVE WS-V0007 TO WS-V0010
           MOVE WS-CLAMPED TO WS-CLAMP-RET

       MAIN-LOGIC.
           MOVE 0 TO WS-CLAMP-ARG0
           MOVE 100 TO WS-CLAMP-ARG1
           MULTIPLY 42 BY -1 GIVING WS-V0011
           MOVE WS-V0011 TO WS-MAX-ARG0
           MOVE 37 TO WS-MAX-ARG1
           PERFORM MAX-PARA
           MOVE WS-MAX-RET TO WS-ABS-ARG0
           PERFORM ABS-PARA
           MOVE WS-ABS-RET TO WS-CLAMP-ARG2
           PERFORM CLAMP-PARA
           DISPLAY WS-CLAMP-RET
           STOP RUN.

