      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. EFFECTS_DEMO.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-GREET-NAME  PIC X(256).
       01 WS-GREET-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       GREET-PARA.
           STRING WS-NAME DELIMITED BY SPACE
                  "!" DELIMITED BY SPACE
                  INTO WS-T0002
           STRING "Hello, " DELIMITED BY SPACE
                  WS-T0002 DELIMITED BY SPACE
                  INTO WS-T0004
           DISPLAY WS-T0004
           MOVE 0 TO WS-GREET-RET

       MAIN-LOGIC.
           MOVE "Alice" TO WS-GREET-ARG0
           PERFORM GREET-PARA
           MOVE "Bob" TO WS-GREET-ARG0
           PERFORM GREET-PARA
           DISPLAY "Done!"
           STOP RUN.

