      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. EFFECTFUL_HELLO.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       MAIN-LOGIC.
           DISPLAY "What is your name?"
      *>   bind: name
           STRING WS-NAME DELIMITED BY SPACE
                  "!" DELIMITED BY SPACE
                  INTO WS-JOINED-2
           STRING "Hello, " DELIMITED BY SPACE
                  WS-JOINED-2 DELIMITED BY SPACE
                  INTO WS-JOINED-4
           DISPLAY WS-JOINED-4
           STOP RUN.

