      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. FIBONACCI.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-FIB-N  PIC S9(18).
       01 WS-FIB-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       FIB-PARA.
           IF WS-N = 0
             MOVE 1 TO WS-V0001
           ELSE
             MOVE 0 TO WS-V0001
           END-IF
           IF WS-V0001 NOT = 0
             MOVE 0 TO WS-V0002
           ELSE
           IF WS-N = 1
             MOVE 1 TO WS-V0003
           ELSE
             MOVE 0 TO WS-V0003
           END-IF
           IF WS-V0003 NOT = 0
             MOVE 1 TO WS-V0004
           ELSE
           SUBTRACT 1 FROM WS-N GIVING WS-V0005
           MOVE WS-V0005 TO WS-FIB-ARG0
           PERFORM FIB-PARA
           SUBTRACT 2 FROM WS-N GIVING WS-V0006
           MOVE WS-V0006 TO WS-FIB-ARG0
           PERFORM FIB-PARA
           ADD WS-FIB-RET WS-FIB-RET GIVING WS-V0007
             MOVE WS-V0007 TO WS-V0004
           END-IF
             MOVE WS-V0004 TO WS-V0002
           END-IF
           MOVE WS-V0002 TO WS-FIB-RET

       MAIN-LOGIC.
           MOVE 20 TO WS-FIB-ARG0
           PERFORM FIB-PARA
           DISPLAY WS-FIB-RET
           STOP RUN.

