      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. GREETING.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-GREETING-NAME  PIC X(256).
       01 WS-GREETING-RET     PIC X(256).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
      *> greeting
       GREETING-PARA.
           STRING WS-NAME DELIMITED BY SPACE
                  "!" DELIMITED BY SPACE
                  INTO WS-GREETING-JOINED-2
           STRING "Hello, " DELIMITED BY SPACE
                  WS-GREETING-JOINED-2 DELIMITED BY SPACE
                  INTO WS-GREETING-JOINED-4
           MOVE WS-GREETING-JOINED-4 TO WS-GREETING-RET

       MAIN-LOGIC.
           MOVE "World" TO WS-GREETING-NAME
           PERFORM GREETING-PARA
           DISPLAY WS-GREETING-RET
           STOP RUN.

