      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SQUARE-X  PIC S9(18).
       01 WS-SQUARE-RET     PIC S9(18).
       01 WS-DOUBLE-X  PIC S9(18).
       01 WS-DOUBLE-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
      *> square
       SQUARE-PARA.
           MULTIPLY WS-X BY WS-X GIVING WS-SQUARE-PROD-1
           MOVE WS-SQUARE-PROD-1 TO WS-SQUARE-RET

      *> double
       DOUBLE-PARA.
           ADD WS-X WS-X GIVING WS-DOUBLE-SUM-2
           MOVE WS-DOUBLE-SUM-2 TO WS-DOUBLE-RET

       MAIN-LOGIC.
           MOVE 5 TO WS-SQUARE-X
           PERFORM SQUARE-PARA
           DISPLAY WS-SQUARE-RET
           STOP RUN.

