      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. IS_PRIME.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-IS_PRIME-N  PIC S9(18).
       01 WS-IS_PRIME-RET     PIC 9(1).
       01 WS-CHECK_DIVISOR-N  PIC S9(18).
       01 WS-CHECK_DIVISOR-D  PIC S9(18).
       01 WS-CHECK_DIVISOR-RET     PIC 9(1).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
      *> is-prime
       IS_PRIME-PARA.
           IF WS-N < 2
             MOVE 1 TO WS-IS_PRIME-CMP-1
           ELSE
             MOVE 0 TO WS-IS_PRIME-CMP-1
           END-IF
           IF WS-IS_PRIME-CMP-1 NOT = 0
             MOVE 0 TO WS-IS_PRIME-BRANCH-2
           ELSE
           MOVE WS-N TO WS-CHECK_DIVISOR-N
           MOVE 2 TO WS-CHECK_DIVISOR-D
           PERFORM CHECK_DIVISOR-PARA
             MOVE WS-CHECK_DIVISOR-RET TO WS-IS_PRIME-BRANCH-2
           END-IF
           MOVE WS-IS_PRIME-BRANCH-2 TO WS-IS_PRIME-RET

      *> check-divisor
       CHECK_DIVISOR-PARA.
       CHECK_DIVISOR-LOOP.
           MULTIPLY WS-D BY WS-D GIVING WS-CHECK_DIVISOR-PROD-3
           IF WS-CHECK_DIVISOR-PROD-3 > WS-N
             MOVE 1 TO WS-CHECK_DIVISOR-CMP-4
           ELSE
             MOVE 0 TO WS-CHECK_DIVISOR-CMP-4
           END-IF
           IF WS-CHECK_DIVISOR-CMP-4 NOT = 0
           MOVE 1 TO WS-CHECK_DIVISOR-RET
           GO TO CHECK_DIVISOR-END
           ELSE
           DIVIDE WS-N BY WS-D GIVING WS-CHECK_DIVISOR-QUOT-5
           MULTIPLY WS-CHECK_DIVISOR-QUOT-5 BY WS-D GIVING WS-CHECK_DIVISOR-PROD-6
           IF WS-CHECK_DIVISOR-PROD-6 = WS-N
             MOVE 1 TO WS-CHECK_DIVISOR-EQ-7
           ELSE
             MOVE 0 TO WS-CHECK_DIVISOR-EQ-7
           END-IF
           IF WS-CHECK_DIVISOR-EQ-7 NOT = 0
           MOVE 0 TO WS-CHECK_DIVISOR-RET
           GO TO CHECK_DIVISOR-END
           ELSE
           MOVE WS-N TO WS-CHECK_DIVISOR-N
           ADD WS-D 1 GIVING WS-CHECK_DIVISOR-SUM-8
           MOVE WS-CHECK_DIVISOR-SUM-8 TO WS-CHECK_DIVISOR-D
           GO TO CHECK_DIVISOR-LOOP
           END-IF
           END-IF
       CHECK_DIVISOR-END.

       MAIN-LOGIC.
           MOVE 2 TO WS-IS_PRIME-N
           PERFORM IS_PRIME-PARA
           MOVE WS-IS_PRIME-RET TO WS-A-9
           MOVE 17 TO WS-IS_PRIME-N
           PERFORM IS_PRIME-PARA
           MOVE WS-IS_PRIME-RET TO WS-B-10
           MOVE 49 TO WS-IS_PRIME-N
           PERFORM IS_PRIME-PARA
           MOVE WS-IS_PRIME-RET TO WS-C-11
           MOVE 97 TO WS-IS_PRIME-N
           PERFORM IS_PRIME-PARA
           MOVE WS-IS_PRIME-RET TO WS-D-12
           STRING " " DELIMITED BY SPACE
                  WS-D DELIMITED BY SPACE
                  INTO WS-JOINED-14
           STRING WS-C DELIMITED BY SPACE
                  WS-JOINED-14 DELIMITED BY SPACE
                  INTO WS-JOINED-16
           STRING " " DELIMITED BY SPACE
                  WS-JOINED-16 DELIMITED BY SPACE
                  INTO WS-JOINED-18
           STRING WS-B DELIMITED BY SPACE
                  WS-JOINED-18 DELIMITED BY SPACE
                  INTO WS-JOINED-20
           STRING " " DELIMITED BY SPACE
                  WS-JOINED-20 DELIMITED BY SPACE
                  INTO WS-JOINED-22
           STRING WS-A DELIMITED BY SPACE
                  WS-JOINED-22 DELIMITED BY SPACE
                  INTO WS-JOINED-24
           DISPLAY WS-JOINED-24
           STOP RUN.

