      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MATHLIB.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SQUARE-X  PIC S9(18).
       01 WS-SQUARE-RET     PIC S9(18).
       01 WS-CUBE-X  PIC S9(18).
       01 WS-CUBE-RET     PIC S9(18).
       01 WS-HELPER-X  PIC S9(18).
       01 WS-HELPER-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
      *> square
       SQUARE-PARA.
           MULTIPLY WS-X BY WS-X GIVING WS-SQUARE-PROD-1
           MOVE WS-SQUARE-PROD-1 TO WS-SQUARE-RET

      *> cube
       CUBE-PARA.
           MULTIPLY WS-X BY WS-X GIVING WS-CUBE-PROD-2
           MULTIPLY WS-CUBE-PROD-2 BY WS-X GIVING WS-CUBE-PROD-3
           MOVE WS-CUBE-PROD-3 TO WS-CUBE-RET

      *> helper
       HELPER-PARA.
           ADD WS-X 1 GIVING WS-HELPER-SUM-4
           MOVE WS-HELPER-SUM-4 TO WS-HELPER-RET

       MAIN-LOGIC.
           STOP RUN.

