      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. MINI_BOOTSTRAP.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-POINT.
         05 WS-POINT-X PIC S9(18).
         05 WS-POINT-Y PIC S9(18).
       01 WS-COLOR.
         05 WS-COLOR-TAG    PIC 9(2).
         05 WS-COLOR-F0     PIC S9(18).
       01 TAG-RED      PIC 9(2) VALUE 1.
       01 TAG-GREEN      PIC 9(2) VALUE 2.
       01 TAG-BLUE      PIC 9(2) VALUE 3.
       01 WS-SHOW_COLOR-C  PIC S9(18).
       01 WS-SHOW_COLOR-RET     PIC X(256).
       01 WS-GET_X-P  PIC S9(18).
       01 WS-GET_X-RET     PIC S9(18).
       01 WS-ADD_POINTS-A  PIC S9(18).
       01 WS-ADD_POINTS-B  PIC S9(18).
       01 WS-ADD_POINTS-RET     PIC S9(18).
       01 WS-MAP_LIST-F  PIC S9(18).
       01 WS-MAP_LIST-XS  PIC S9(18).
       01 WS-MAP_LIST-RET     PIC S9(18).
       01 WS-MAP_LIST_LOOP-F  PIC S9(18).
       01 WS-MAP_LIST_LOOP-XS  PIC S9(18).
       01 WS-MAP_LIST_LOOP-I  PIC S9(18).
       01 WS-MAP_LIST_LOOP-LEN  PIC S9(18).
       01 WS-MAP_LIST_LOOP-ACC  PIC S9(18).
       01 WS-MAP_LIST_LOOP-RET     PIC S9(18).
       01 WS-USE_MAP-PTS  PIC S9(18).
       01 WS-USE_MAP-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       SHOW_COLOR-PARA.
           MOVE 0 TO WS-SHOW_COLOR-RET

       GET_X-PARA.
           MOVE WS-P TO WS-GET_X-RET

       ADD_POINTS-PARA.
           MOVE 0 TO WS-V0001
      *>   Record Point construction
           MOVE WS-V0001 TO WS-ADD_POINTS-RET

       MAP_LIST-PARA.
           MOVE WS-F TO WS-MAP_LIST_LOOP-ARG0
           MOVE WS-XS TO WS-MAP_LIST_LOOP-ARG1
           MOVE 0 TO WS-MAP_LIST_LOOP-ARG2
           MOVE WS-XS TO WS-MAP_LIST_LOOP-ARG3
           MOVE 0 TO WS-MAP_LIST_LOOP-ARG4
           PERFORM MAP_LIST_LOOP-PARA
           MOVE WS-MAP_LIST_LOOP-RET TO WS-MAP_LIST-RET

       MAP_LIST_LOOP-PARA.
       MAP_LIST_LOOP-LOOP.
           IF WS-I = WS-LEN
             MOVE 1 TO WS-V0002
           ELSE
             MOVE 0 TO WS-V0002
           END-IF
           IF WS-V0002 NOT = 0
           MOVE WS-ACC TO WS-MAP_LIST_LOOP-RET
           GO TO MAP_LIST_LOOP-END
           ELSE
           MOVE WS-F TO WS-MAP_LIST_LOOP-F
           MOVE WS-XS TO WS-MAP_LIST_LOOP-XS
           ADD WS-I 1 GIVING WS-V0003
           MOVE WS-V0003 TO WS-MAP_LIST_LOOP-I
           MOVE WS-LEN TO WS-MAP_LIST_LOOP-LEN
           ADD WS-ACC 0 GIVING WS-V0004
           MOVE WS-V0004 TO WS-MAP_LIST_LOOP-ACC
           GO TO MAP_LIST_LOOP-LOOP
           END-IF
       MAP_LIST_LOOP-END.

       USE_MAP-PARA.
           MOVE WS-GET_X TO WS-MAP_LIST-ARG0
           MOVE WS-PTS TO WS-MAP_LIST-ARG1
           PERFORM MAP_LIST-PARA
           MOVE WS-MAP_LIST-RET TO WS-USE_MAP-RET

       MAIN-LOGIC.
           MOVE 0 TO WS-USE_MAP-ARG0
           PERFORM USE_MAP-PARA
           DISPLAY WS-USE_MAP-RET
           STOP RUN.

