      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. SAFE_DIVIDE.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-RESULT.
         05 WS-RESULT-TAG    PIC 9(2).
         05 WS-RESULT-F0     PIC S9(18).
       01 TAG-SUCCESS      PIC 9(2) VALUE 1.
       01 TAG-FAILURE      PIC 9(2) VALUE 2.
       01 WS-SAFE_DIVIDE-X  PIC S9(18).
       01 WS-SAFE_DIVIDE-Y  PIC S9(18).
       01 WS-SAFE_DIVIDE-RET     PIC S9(18).
       01 WS-DESCRIBE-RESULT  PIC S9(18).
       01 WS-DESCRIBE-RET     PIC X(256).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
      *> safe-divide
       SAFE_DIVIDE-PARA.
           IF WS-Y = 0
             MOVE 1 TO WS-SAFE_DIVIDE-EQ-1
           ELSE
             MOVE 0 TO WS-SAFE_DIVIDE-EQ-1
           END-IF
           IF WS-SAFE_DIVIDE-EQ-1 NOT = 0
             MOVE "division by zero" TO WS-SAFE_DIVIDE-BRANCH-2
           ELSE
           DIVIDE WS-X BY WS-Y GIVING WS-SAFE_DIVIDE-QUOT-3
             MOVE WS-SAFE_DIVIDE-QUOT-3 TO WS-SAFE_DIVIDE-BRANCH-2
           END-IF
           MOVE WS-SAFE_DIVIDE-BRANCH-2 TO WS-SAFE_DIVIDE-RET

      *> describe
       DESCRIBE-PARA.
           EVALUATE WS-RESULT-TAG
             WHEN TAG-SUCCESS
           STRING "got " DELIMITED BY SPACE
                  WS-N DELIMITED BY SPACE
                  INTO WS-DESCRIBE-JOINED-6
               MOVE WS-DESCRIBE-JOINED-6 TO WS-DESCRIBE-MATCH-4
             WHEN TAG-FAILURE
           STRING "error: " DELIMITED BY SPACE
                  WS-MSG DELIMITED BY SPACE
                  INTO WS-DESCRIBE-JOINED-8
               MOVE WS-DESCRIBE-JOINED-8 TO WS-DESCRIBE-MATCH-4
           END-EVALUATE
           MOVE WS-DESCRIBE-MATCH-4 TO WS-DESCRIBE-RET

       MAIN-LOGIC.
           MOVE 42 TO WS-SAFE_DIVIDE-X
           MOVE 7 TO WS-SAFE_DIVIDE-Y
           PERFORM SAFE_DIVIDE-PARA
           MOVE WS-SAFE_DIVIDE-RET TO WS-DESCRIBE-RESULT
           PERFORM DESCRIBE-PARA
           DISPLAY WS-DESCRIBE-RET
           STOP RUN.

