      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. SHAPES.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SHAPE.
         05 WS-SHAPE-TAG    PIC 9(2).
         05 WS-SHAPE-F0     PIC S9(18).
         05 WS-SHAPE-F1     PIC S9(18).
       01 TAG-CIRCLE      PIC 9(2) VALUE 1.
       01 TAG-RECTANGLE      PIC 9(2) VALUE 2.
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       MAIN-LOGIC.
           DISPLAY 0
           STOP RUN.

