      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. STAGE1_TEST.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SQUARE-X  PIC S9(18).
       01 WS-SQUARE-RET     PIC S9(18).
       01 WS-GREET-NAME  PIC X(256).
       01 WS-GREET-RET     PIC X(256).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
      *> square
       SQUARE-PARA.
           MULTIPLY WS-X BY WS-X GIVING WS-SQUARE-PROD-1
           MOVE WS-SQUARE-PROD-1 TO WS-SQUARE-RET

      *> greet
       GREET-PARA.
           STRING WS-NAME DELIMITED BY SPACE
                  "!" DELIMITED BY SPACE
                  INTO WS-GREET-JOINED-3
           STRING "Hello, " DELIMITED BY SPACE
                  WS-GREET-JOINED-3 DELIMITED BY SPACE
                  INTO WS-GREET-JOINED-5
           MOVE WS-GREET-JOINED-5 TO WS-GREET-RET

       MAIN-LOGIC.
           MOVE "Codex" TO WS-GREET-NAME
           PERFORM GREET-PARA
           DISPLAY WS-GREET-RET
           MOVE 7 TO WS-SQUARE-X
           PERFORM SQUARE-PARA
           DISPLAY WS-SQUARE-RET
           STOP RUN.

