      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. STRING_OPS.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-IS_IDENTIFIER_CHAR-CH  PIC X(256).
       01 WS-IS_IDENTIFIER_CHAR-RET     PIC 9(1).
       01 WS-COUNT_LETTERS-S  PIC X(256).
       01 WS-COUNT_LETTERS-I  PIC S9(18).
       01 WS-COUNT_LETTERS-ACC  PIC S9(18).
       01 WS-COUNT_LETTERS-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       IS_IDENTIFIER_CHAR-PARA.
           IF WS-CH NOT = 0
             MOVE 1 TO WS-V0001
           ELSE
           IF WS-CH NOT = 0
             MOVE 1 TO WS-V0002
           ELSE
           IF WS-CH = "-"
             MOVE 1 TO WS-V0003
           ELSE
             MOVE 0 TO WS-V0003
           END-IF
           IF WS-V0003 NOT = 0
             MOVE 1 TO WS-V0004
           ELSE
             MOVE 0 TO WS-V0004
           END-IF
             MOVE WS-V0004 TO WS-V0002
           END-IF
             MOVE WS-V0002 TO WS-V0001
           END-IF
           MOVE WS-V0001 TO WS-IS_IDENTIFIER_CHAR-RET

       COUNT_LETTERS-PARA.
       COUNT_LETTERS-LOOP.
           IF WS-I >= WS-S
             MOVE 1 TO WS-V0005
           ELSE
             MOVE 0 TO WS-V0005
           END-IF
           IF WS-V0005 NOT = 0
           MOVE WS-ACC TO WS-COUNT_LETTERS-RET
           GO TO COUNT_LETTERS-END
           ELSE
           MOVE WS-I TO WS-V0006
           IF WS-CH NOT = 0
           MOVE WS-S TO WS-COUNT_LETTERS-S
           ADD WS-I 1 GIVING WS-V0007
           MOVE WS-V0007 TO WS-COUNT_LETTERS-I
           ADD WS-ACC 1 GIVING WS-V0008
           MOVE WS-V0008 TO WS-COUNT_LETTERS-ACC
           GO TO COUNT_LETTERS-LOOP
           ELSE
           MOVE WS-S TO WS-COUNT_LETTERS-S
           ADD WS-I 1 GIVING WS-V0009
           MOVE WS-V0009 TO WS-COUNT_LETTERS-I
           MOVE WS-ACC TO WS-COUNT_LETTERS-ACC
           GO TO COUNT_LETTERS-LOOP
           END-IF
           END-IF
       COUNT_LETTERS-END.

       MAIN-LOGIC.
           MOVE "hello world 123" TO WS-COUNT_LETTERS-ARG0
           MOVE 0 TO WS-COUNT_LETTERS-ARG1
           MOVE 0 TO WS-COUNT_LETTERS-ARG2
           PERFORM COUNT_LETTERS-PARA
           DISPLAY WS-COUNT_LETTERS-RET
           STOP RUN.

