      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCO_STRESS.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-SUM_TO-N  PIC S9(18).
       01 WS-SUM_TO-ACC  PIC S9(18).
       01 WS-SUM_TO-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       SUM_TO-PARA.
       SUM_TO-LOOP.
           IF WS-N = 0
             MOVE 1 TO WS-V0001
           ELSE
             MOVE 0 TO WS-V0001
           END-IF
           IF WS-V0001 NOT = 0
           MOVE WS-ACC TO WS-SUM_TO-RET
           GO TO SUM_TO-END
           ELSE
           SUBTRACT 1 FROM WS-N GIVING WS-V0002
           MOVE WS-V0002 TO WS-SUM_TO-N
           ADD WS-ACC WS-N GIVING WS-V0003
           MOVE WS-V0003 TO WS-SUM_TO-ACC
           GO TO SUM_TO-LOOP
           END-IF
       SUM_TO-END.

       MAIN-LOGIC.
           MOVE 1000000 TO WS-SUM_TO-ARG0
           MOVE 0 TO WS-SUM_TO-ARG1
           PERFORM SUM_TO-PARA
           DISPLAY WS-SUM_TO-RET
           STOP RUN.

