      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TYPE_CHECKER_TEST.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-ADD_ONE-X  PIC S9(18).
       01 WS-ADD_ONE-RET     PIC S9(18).
       01 WS-DOUBLE-X  PIC S9(18).
       01 WS-DOUBLE-RET     PIC S9(18).
       01 WS-GREET-NAME  PIC X(256).
       01 WS-GREET-RET     PIC X(256).
       01 WS-IS_POSITIVE-X  PIC S9(18).
       01 WS-IS_POSITIVE-RET     PIC 9(1).
       01 WS-APPLY_TWICE-F  PIC S9(18).
       01 WS-APPLY_TWICE-X  PIC S9(18).
       01 WS-APPLY_TWICE-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
      *> add-one
       ADD_ONE-PARA.
           ADD WS-X 1 GIVING WS-ADD_ONE-SUM-1
           MOVE WS-ADD_ONE-SUM-1 TO WS-ADD_ONE-RET

      *> double
       DOUBLE-PARA.
           MULTIPLY WS-X BY 2 GIVING WS-DOUBLE-PROD-2
           MOVE WS-DOUBLE-PROD-2 TO WS-DOUBLE-RET

      *> greet
       GREET-PARA.
           STRING WS-NAME DELIMITED BY SPACE
                  "!" DELIMITED BY SPACE
                  INTO WS-GREET-JOINED-4
           STRING "Hello, " DELIMITED BY SPACE
                  WS-GREET-JOINED-4 DELIMITED BY SPACE
                  INTO WS-GREET-JOINED-6
           MOVE WS-GREET-JOINED-6 TO WS-GREET-RET

      *> is-positive
       IS_POSITIVE-PARA.
           IF WS-X > 0
             MOVE 1 TO WS-IS_POSITIVE-CMP-7
           ELSE
             MOVE 0 TO WS-IS_POSITIVE-CMP-7
           END-IF
           MOVE WS-IS_POSITIVE-CMP-7 TO WS-IS_POSITIVE-RET

      *> apply-twice
       APPLY_TWICE-PARA.
           MOVE WS-X TO WS-APPLY_TWICE-RET

       MAIN-LOGIC.
           MOVE WS-ADD_ONE TO WS-APPLY_TWICE-F
           MOVE 40 TO WS-APPLY_TWICE-X
           PERFORM APPLY_TWICE-PARA
           DISPLAY WS-APPLY_TWICE-RET
           STOP RUN.

