      *> Generated by Codex compiler — COBOL backend
      *> A functional language compiling to COBOL.
      *> The universe has come full circle.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TYPE_CHECKER_TEST.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-ADD_ONE-X  PIC S9(18).
       01 WS-ADD_ONE-RET     PIC S9(18).
       01 WS-DOUBLE-X  PIC S9(18).
       01 WS-DOUBLE-RET     PIC S9(18).
       01 WS-GREET-NAME  PIC X(256).
       01 WS-GREET-RET     PIC X(256).
       01 WS-IS_POSITIVE-X  PIC S9(18).
       01 WS-IS_POSITIVE-RET     PIC 9(1).
       01 WS-APPLY_TWICE-F  PIC S9(18).
       01 WS-APPLY_TWICE-X  PIC S9(18).
       01 WS-APPLY_TWICE-RET     PIC S9(18).
       01 WS-RESULT         PIC S9(18).
       01 WS-TEMP           PIC S9(18).
       01 WS-TEXT-RESULT     PIC X(256).

       PROCEDURE DIVISION.
       ADD_ONE-PARA.
           ADD WS-X 1 GIVING WS-V0001
           MOVE WS-V0001 TO WS-ADD_ONE-RET

       DOUBLE-PARA.
           MULTIPLY WS-X BY 2 GIVING WS-V0002
           MOVE WS-V0002 TO WS-DOUBLE-RET

       GREET-PARA.
           STRING WS-NAME DELIMITED BY SPACE
                  "!" DELIMITED BY SPACE
                  INTO WS-T0004
           STRING "Hello, " DELIMITED BY SPACE
                  WS-T0004 DELIMITED BY SPACE
                  INTO WS-T0006
           MOVE WS-T0006 TO WS-GREET-RET

       IS_POSITIVE-PARA.
           IF WS-X > 0
             MOVE 1 TO WS-V0007
           ELSE
             MOVE 0 TO WS-V0007
           END-IF
           MOVE WS-V0007 TO WS-IS_POSITIVE-RET

       APPLY_TWICE-PARA.
           MOVE WS-X TO WS-APPLY_TWICE-RET

       MAIN-LOGIC.
           MOVE WS-ADD_ONE TO WS-APPLY_TWICE-ARG0
           MOVE 40 TO WS-APPLY_TWICE-ARG1
           PERFORM APPLY_TWICE-PARA
           DISPLAY WS-APPLY_TWICE-RET
           STOP RUN.

