// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


} // namespace codex

int main() {
    using namespace codex;
    std::cout << std::string("What is your name?") << std::endl;
    auto name = [&]{ std::string _l; std::getline(std::cin, _l); return _l; }();
    std::cout << (std::string("Hello, ") + (name + std::string("!"))) << std::endl;
    return 0;
}
