// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {

struct Lit;
struct Add;
struct Sub;
struct Mul;
struct Div;
struct ParseResult;

struct Lit {
    int64_t field0;
};

struct Add {
    auto field0;
    auto field1;
};

struct Sub {
    auto field0;
    auto field1;
};

struct Mul {
    auto field0;
    auto field1;
};

struct Div {
    auto field0;
    auto field1;
};

using Expr = std::variant<Lit, Add, Sub, Mul, Div>;

struct ParseResult {
    auto expr;
    int64_t pos;
};

int64_t skip_ws(std::string input, int64_t pos) {
    while (true) {
        if ((pos >= int64_t(input.size()))) {
            return pos;
        } else {
            if ((!std::string(1, input[pos]).empty() && std::isspace(std::string(1, input[pos])[0]))) {
                auto _tco_0 = input;
                auto _tco_1 = (pos + int64_t(1));
                input = _tco_0;
                pos = _tco_1;
                continue;
            } else {
                return pos;
            }
        }
    }
}

int64_t collect_digits(std::string input, int64_t pos, int64_t len, int64_t acc) {
    while (true) {
        if ((pos >= len)) {
            return acc;
        } else {
            if ((!std::string(1, input[pos]).empty() && std::isdigit(std::string(1, input[pos])[0]))) {
                auto d = int64_t(std::stoll(std::string(1, input[pos])));
                auto _tco_0 = input;
                auto _tco_1 = (pos + int64_t(1));
                auto _tco_2 = len;
                auto _tco_3 = ((acc * int64_t(10)) + d);
                input = _tco_0;
                pos = _tco_1;
                len = _tco_2;
                acc = _tco_3;
                continue;
            } else {
                return acc;
            }
        }
    }
}

int64_t digit_count(std::string input, int64_t pos, int64_t len) {
    return ((pos >= len) ? int64_t(0) : ((!std::string(1, input[pos]).empty() && std::isdigit(std::string(1, input[pos])[0])) ? (int64_t(1) + digit_count(input, (pos + int64_t(1)), len)) : int64_t(0)));
}

ParseResult parse_atom(std::string input, int64_t start) {
    return [&]{ auto pos = skip_ws(input, start); return [&]{ auto len = int64_t(input.size()); return ((pos >= len) ? ParseResult{Expr(Lit{int64_t(0)}), pos} : ((std::string(1, input[pos]) == std::string("(")) ? [&]{ auto inner = parse_additive(input, (pos + int64_t(1))); return [&]{ auto after = skip_ws(input, inner.pos); return ((after < len) ? ParseResult{inner.expr, (after + int64_t(1))} : ParseResult{inner.expr, after}); }(); }() : [&]{ auto digits = digit_count(input, pos, len); return ((digits > int64_t(0)) ? [&]{ auto value = collect_digits(input, pos, len, int64_t(0)); return ParseResult{Expr(Lit{value}), (pos + digits)}; }() : ParseResult{Expr(Lit{int64_t(0)}), pos}); }())); }(); }();
}

ParseResult parse_multiplicative(std::string input, int64_t start) {
    return [&]{ auto left = parse_atom(input, start); return continue_multiplicative(input, left); }();
}

ParseResult continue_multiplicative(std::string input, ParseResult current) {
    while (true) {
        auto pos = skip_ws(input, current.pos);
        auto len = int64_t(input.size());
        if ((pos >= len)) {
            return current;
        } else {
            if ((std::string(1, input[pos]) == std::string("*"))) {
                auto right = parse_atom(input, (pos + int64_t(1)));
                auto _tco_0 = input;
                auto _tco_1 = ParseResult{Expr(Mul{current.expr, right.expr}), right.pos};
                input = _tco_0;
                current = _tco_1;
                continue;
            } else {
                if ((std::string(1, input[pos]) == std::string("/"))) {
                    auto right = parse_atom(input, (pos + int64_t(1)));
                    auto _tco_0 = input;
                    auto _tco_1 = ParseResult{Expr(Div{current.expr, right.expr}), right.pos};
                    input = _tco_0;
                    current = _tco_1;
                    continue;
                } else {
                    return current;
                }
            }
        }
    }
}

ParseResult parse_additive(std::string input, int64_t start) {
    return [&]{ auto left = parse_multiplicative(input, start); return continue_additive(input, left); }();
}

ParseResult continue_additive(std::string input, ParseResult current) {
    while (true) {
        auto pos = skip_ws(input, current.pos);
        auto len = int64_t(input.size());
        if ((pos >= len)) {
            return current;
        } else {
            if ((std::string(1, input[pos]) == std::string("+"))) {
                auto right = parse_multiplicative(input, (pos + int64_t(1)));
                auto _tco_0 = input;
                auto _tco_1 = ParseResult{Expr(Add{current.expr, right.expr}), right.pos};
                input = _tco_0;
                current = _tco_1;
                continue;
            } else {
                if ((std::string(1, input[pos]) == std::string("-"))) {
                    auto right = parse_multiplicative(input, (pos + int64_t(1)));
                    auto _tco_0 = input;
                    auto _tco_1 = ParseResult{Expr(Sub{current.expr, right.expr}), right.pos};
                    input = _tco_0;
                    current = _tco_1;
                    continue;
                } else {
                    return current;
                }
            }
        }
    }
}

Expr parse(std::string input) {
    return parse_additive(input, int64_t(0)).expr;
}

int64_t eval(Expr e) {
    return std::visit([&](auto&& _s) -> int64_t { if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Lit>) { auto n = _s.field0; return n; } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Add>) { auto a = _s.field0; auto b = _s.field1; return (eval(a) + eval(b)); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Sub>) { auto a = _s.field0; auto b = _s.field1; return (eval(a) - eval(b)); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Mul>) { auto a = _s.field0; auto b = _s.field1; return (eval(a) * eval(b)); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Div>) { auto a = _s.field0; auto b = _s.field1; return (eval(a) / eval(b)); } else { throw std::runtime_error("non-exhaustive match"); } }, e);
}

std::string format(Expr e) {
    return std::visit([&](auto&& _s) -> std::string { if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Lit>) { auto n = _s.field0; return [&]{ std::ostringstream _o; _o << n; return _o.str(); }(); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Add>) { auto a = _s.field0; auto b = _s.field1; return (std::string("(") + (format(a) + (std::string(" + ") + (format(b) + std::string(")"))))); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Sub>) { auto a = _s.field0; auto b = _s.field1; return (std::string("(") + (format(a) + (std::string(" - ") + (format(b) + std::string(")"))))); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Mul>) { auto a = _s.field0; auto b = _s.field1; return (std::string("(") + (format(a) + (std::string(" * ") + (format(b) + std::string(")"))))); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Div>) { auto a = _s.field0; auto b = _s.field1; return (std::string("(") + (format(a) + (std::string(" / ") + (format(b) + std::string(")"))))); } else { throw std::runtime_error("non-exhaustive match"); } }, e);
}

std::string test_expr(std::string input, int64_t expected) {
    return [&]{ auto tree = parse(input); return [&]{ auto result = eval(tree); return [&]{ auto status = ((result == expected) ? std::string("PASS") : std::string("FAIL")); return (status + (std::string(": ") + (input + (std::string(" = ") + ([&]{ std::ostringstream _o; _o << result; return _o.str(); }() + (std::string(" (expected ") + ([&]{ std::ostringstream _o; _o << expected; return _o.str(); }() + (std::string(")  tree: ") + format(tree))))))))); }(); }(); }();
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << std::string("=== Expression Calculator ===") << std::endl;
    std::cout << std::string("") << std::endl;
    std::cout << test_expr(std::string("42"), int64_t(42)) << std::endl;
    std::cout << test_expr(std::string("2 + 3"), int64_t(5)) << std::endl;
    std::cout << test_expr(std::string("10 - 4"), int64_t(6)) << std::endl;
    std::cout << test_expr(std::string("3 * 7"), int64_t(21)) << std::endl;
    std::cout << test_expr(std::string("100 / 5"), int64_t(20)) << std::endl;
    std::cout << test_expr(std::string("2 + 3 * 4"), int64_t(14)) << std::endl;
    std::cout << test_expr(std::string("10 - 2 * 3"), int64_t(4)) << std::endl;
    std::cout << test_expr(std::string("(2 + 3) * 4"), int64_t(20)) << std::endl;
    std::cout << test_expr(std::string("1 + 2 + 3 + 4"), int64_t(10)) << std::endl;
    std::cout << test_expr(std::string("2 * 3 + 4 * 5"), int64_t(26)) << std::endl;
    std::cout << std::string("") << std::endl;
    std::cout << std::string("All PASS = compiler correctly compiles a recursive descent parser.") << std::endl;
    std::cout << std::string("QED: not a quine.") << std::endl;
    return 0;
}
