// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


int64_t _abs(int64_t x) {
    return ((x < int64_t(0)) ? (-x) : x);
}

int64_t _max(int64_t x, int64_t y) {
    return ((x > y) ? x : y);
}

int64_t factorial(int64_t n) {
    return ((n == int64_t(0)) ? int64_t(1) : (n * factorial((n - int64_t(1)))));
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << factorial(int64_t(10)) << std::endl;
    return 0;
}
