// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


int64_t square(int64_t x) {
    return (x * x);
}

int64_t _double(int64_t x) {
    return (x + x);
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << square(int64_t(5)) << std::endl;
    return 0;
}
