// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


bool is_prime(int64_t n) {
    return ((n < int64_t(2)) ? false : check_divisor(n, int64_t(2)));
}

bool check_divisor(int64_t n, int64_t d) {
    while (true) {
        if (((d * d) > n)) {
            return true;
        } else {
            if ((((n / d) * d) == n)) {
                return false;
            } else {
                auto _tco_0 = n;
                auto _tco_1 = (d + int64_t(1));
                n = _tco_0;
                d = _tco_1;
                continue;
            }
        }
    }
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << [&]{ auto a = is_prime(int64_t(2)); return [&]{ auto b = is_prime(int64_t(17)); return [&]{ auto c = is_prime(int64_t(49)); return [&]{ auto d = is_prime(int64_t(97)); return ([&]{ std::ostringstream _o; _o << a; return _o.str(); }() + (std::string(" ") + ([&]{ std::ostringstream _o; _o << b; return _o.str(); }() + (std::string(" ") + ([&]{ std::ostringstream _o; _o << c; return _o.str(); }() + (std::string(" ") + [&]{ std::ostringstream _o; _o << d; return _o.str(); }())))))); }(); }(); }(); }() << std::endl;
    return 0;
}
