// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {

struct Red;
struct Green;
struct Blue;
struct Point;

struct Red {
};

struct Green {
};

struct Blue {
    int64_t field0;
};

using Color = std::variant<Red, Green, Blue>;

struct Point {
    int64_t x;
    int64_t y;
};

std::string show_color(Color c) {
    return std::visit([&](auto&& _s) -> std::string { if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Red>) { return std::string("red"); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Green>) { return std::string("green"); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Blue>) { auto n = _s.field0; return std::string("blue"); } else { throw std::runtime_error("non-exhaustive match"); } }, c);
}

int64_t get_x(Point p) {
    return p.x;
}

Point add_points(Point a, Point b) {
    return Point{(a.x + b.x), (a.y + b.y)};
}

template<typename T0, typename T1>
std::vector<T1> map_list(std::function<T1(T0)> f, std::vector<T0> xs) {
    return map_list_loop(f, xs, int64_t(0), int64_t(xs.size()), std::vector<T1>({}));
}

template<typename T2, typename T3>
std::vector<T3> map_list_loop(std::function<T3(T2)> f, std::vector<T2> xs, int64_t i, int64_t len, std::vector<T3> acc) {
    while (true) {
        if ((i == len)) {
            return acc;
        } else {
            auto _tco_0 = f;
            auto _tco_1 = xs;
            auto _tco_2 = (i + int64_t(1));
            auto _tco_3 = len;
            auto _tco_4 = [&]{ auto _l = acc; auto _r = std::vector<T3>({f(xs[i])}); _l.insert(_l.end(), _r.begin(), _r.end()); return _l; }();
            f = _tco_0;
            xs = _tco_1;
            i = _tco_2;
            len = _tco_3;
            acc = _tco_4;
            continue;
        }
    }
}

std::vector<int64_t> use_map(std::vector<Point> pts) {
    return map_list(get_x, pts);
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << use_map(std::vector<Point>({Point{int64_t(1), int64_t(2)}})) << std::endl;
    return 0;
}
