// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {

struct Person;

struct Person {
    std::string name;
    int64_t age;
};

std::string greet(Person p) {
    return (std::string("Hello, ") + (p.name + std::string("!")));
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << greet(Person{std::string("Alice"), int64_t(30)}) << std::endl;
    return 0;
}
