// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


std::string greet(std::string name) {
    return (std::string("Hello, ") + (name + std::string("!")));
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << greet(std::string("World")) << std::endl;
    return 0;
}
