// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {

struct Success;
struct Failure;

template<typename T0>
struct Success {
    T0 field0;
};

template<typename T0>
struct Failure {
    std::string field0;
};

template<typename T0>
using Result = std::variant<Success<T0>, Failure<T0>>;

Result safe_divide(int64_t x, int64_t y) {
    return ((y == int64_t(0)) ? Result(Failure{std::string("division by zero")}) : Result(Success{(x / y)}));
}

std::string describe(Result result) {
    return std::visit([&](auto&& _s) -> std::string { if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Success>) { auto n = _s.field0; return (std::string("got ") + [&]{ std::ostringstream _o; _o << n; return _o.str(); }()); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Failure>) { auto msg = _s.field0; return (std::string("error: ") + msg); } else { throw std::runtime_error("non-exhaustive match"); } }, result);
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << describe(safe_divide(int64_t(42), int64_t(7))) << std::endl;
    return 0;
}
