// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {

struct Circle;
struct Rectangle;

struct Circle {
    double field0;
};

struct Rectangle {
    double field0;
    double field1;
};

using Shape = std::variant<Circle, Rectangle>;

} // namespace codex

int main() {
    using namespace codex;
    std::cout << std::visit([&](auto&& _s) -> double { if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Circle>) { auto r = _s.field0; return ((double(3.14) * r) * r); } else if constexpr (std::is_same_v<std::decay_t<decltype(_s)>, Rectangle>) { auto w = _s.field0; auto h = _s.field1; return (w * h); } else { throw std::runtime_error("non-exhaustive match"); } }, Shape(Circle{double(5.0)})) << std::endl;
    return 0;
}
