// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


bool is_identifier_char(std::string ch) {
    return ((!ch.empty() && std::isalpha(ch[0])) ? true : ((!ch.empty() && std::isdigit(ch[0])) ? true : ((ch == std::string("-")) ? true : false)));
}

int64_t count_letters(std::string s, int64_t i, int64_t acc) {
    while (true) {
        if ((i >= int64_t(s.size()))) {
            return acc;
        } else {
            auto ch = std::string(1, s[i]);
            if ((!ch.empty() && std::isalpha(ch[0]))) {
                auto _tco_0 = s;
                auto _tco_1 = (i + int64_t(1));
                auto _tco_2 = (acc + int64_t(1));
                s = _tco_0;
                i = _tco_1;
                acc = _tco_2;
                continue;
            } else {
                auto _tco_0 = s;
                auto _tco_1 = (i + int64_t(1));
                auto _tco_2 = acc;
                s = _tco_0;
                i = _tco_1;
                acc = _tco_2;
                continue;
            }
        }
    }
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << count_letters(std::string("hello world 123"), int64_t(0), int64_t(0)) << std::endl;
    return 0;
}
