// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


int64_t sum_to(int64_t n, int64_t acc) {
    while (true) {
        if ((n == int64_t(0))) {
            return acc;
        } else {
            auto _tco_0 = (n - int64_t(1));
            auto _tco_1 = (acc + n);
            n = _tco_0;
            acc = _tco_1;
            continue;
        }
    }
}

} // namespace codex

int main() {
    using namespace codex;
    std::cout << sum_to(int64_t(1000000), int64_t(0)) << std::endl;
    return 0;
}
