// Generated by Codex compiler — C++ backend
// Compile: g++ -std=c++17 -o output output.cpp
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <variant>
#include <iostream>
#include <cmath>
#include <algorithm>
#include <sstream>
#include <fstream>

namespace codex {


} // namespace codex

int main() {
    using namespace codex;
    [&]{ auto result = run_process(std::string("dotnet"))(std::string("--version")); return std::cout << (std::string("dotnet version: ") + result) << std::endl; }();
    return 0;
}
