using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Cobol;

public sealed class CobolEmitter : ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;
    Map<string, string> m_ctorToTag = Map<string, string>.s_empty;
    Map<string, IRDefinition> m_definitions = Map<string, IRDefinition>.s_empty;
    int m_varCounter;
    string m_currentFunc = "";
    List<string> m_workingStorage = [];

    public string TargetName => "COBOL";
    public string FileExtension => ".cob";

    public string Emit(IRChapter module)
    {
        m_constructorNames = CollectConstructorNames(module);
        m_ctorToTag = BuildCtorTagMap(module);
        m_definitionArity = ValueMap<string, int>.s_empty;
        m_varCounter = 0;
        m_workingStorage = [];

        foreach (IRDefinition d in module.Definitions)
        {
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);
            m_definitions = m_definitions.Set(d.Name, d);
        }

        string programId = Sanitize(module.Name.Parts.Count > 0
            ? module.Name.Parts[module.Name.Parts.Count - 1].Value : "MAIN").ToUpper();

        StringBuilder sb = new();
        sb.AppendLine("      *> Generated by Codex compiler — COBOL backend");
        sb.AppendLine("      *> A functional language compiling to COBOL.");
        sb.AppendLine("      *> The universe has come full circle.");
        sb.AppendLine("       IDENTIFICATION DIVISION.");
        sb.AppendLine($"       PROGRAM-ID. {programId}.");
        sb.AppendLine();
        sb.AppendLine("       DATA DIVISION.");
        sb.AppendLine("       WORKING-STORAGE SECTION.");

        EmitTypeDefinitions(sb, module);

        foreach (IRDefinition def in module.Definitions)
        {
            if (def.Name == "main" && def.Parameters.Length == 0)
            {
                continue;
            }

            EmitDefinitionStorage(sb, def);
        }

        sb.AppendLine("       01 WS-RESULT         PIC S9(18).");
        sb.AppendLine("       01 WS-TEMP           PIC S9(18).");
        sb.AppendLine("       01 WS-TEXT-RESULT     PIC X(256).");

        foreach (string ws in m_workingStorage)
        {
            sb.AppendLine(ws);
        }

        sb.AppendLine();
        sb.AppendLine("       PROCEDURE DIVISION.");

        IRDefinition? mainDef = module.Definitions
            .FirstOrDefault(d => d.Name == "main" && d.Parameters.Length == 0);

        foreach (IRDefinition def in module.Definitions)
        {
            if (def == mainDef)
            {
                continue;
            }

            EmitDefinitionParagraph(sb, def);
            sb.AppendLine();
        }

        sb.AppendLine("       MAIN-LOGIC.");
        if (mainDef is not null)
        {
            if (IsEffectfulDefinition(mainDef))
            {
                EmitStatementCobol(sb, mainDef.Body);
            }
            else
            {
                string resVar = EmitExprToVar(sb, mainDef.Body);
                sb.AppendLine($"           DISPLAY {resVar}");
            }
        }
        else if (module.Definitions.Length == 0)
        {
            sb.AppendLine("           DISPLAY \"All proofs verified at compile time.\"");
        }
        sb.AppendLine("           STOP RUN.");
        sb.AppendLine();

        return sb.ToString();
    }

    void EmitTypeDefinitions(StringBuilder sb, IRChapter module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case RecordType rec:
                    string name = Sanitize(rec.TypeName.Value).ToUpper();
                    sb.AppendLine($"       01 WS-{name}.");
                    for (int i = 0; i < rec.Fields.Length; i++)
                    {
                        RecordFieldType field = rec.Fields[i];
                        string fieldName = Sanitize(field.FieldName.Value).ToUpper();
                        string pic = PicClause(field.Type);
                        sb.AppendLine($"         05 WS-{name}-{fieldName} {pic}.");
                    }
                    break;

                case SumType sum:
                    string sName = Sanitize(sum.TypeName.Value).ToUpper();
                    sb.AppendLine($"       01 WS-{sName}.");
                    sb.AppendLine($"         05 WS-{sName}-TAG    PIC 9(2).");
                    int maxFields = 0;
                    foreach (SumConstructorType ctor in sum.Constructors)
                    {
                        if (ctor.Fields.Length > maxFields)
                        {
                            maxFields = ctor.Fields.Length;
                        }
                    }

                    for (int f = 0; f < maxFields; f++)
                    {
                        sb.AppendLine($"         05 WS-{sName}-F{f}     PIC S9(18).");
                    }

                    int tagNum = 1;
                    foreach (SumConstructorType ctor in sum.Constructors)
                    {
                        string ctorName = Sanitize(ctor.Name.Value).ToUpper();
                        sb.AppendLine($"       01 TAG-{ctorName}      PIC 9(2) VALUE {tagNum}.");
                        tagNum++;
                    }
                    break;
            }
        }
    }

    void EmitDefinitionStorage(StringBuilder sb, IRDefinition def)
    {
        string name = Sanitize(def.Name).ToUpper();
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            string pname = Sanitize(def.Parameters[i].Name).ToUpper();
            string pic = PicClause(def.Parameters[i].Type);
            sb.AppendLine($"       01 WS-{name}-{pname}  {pic}.");
        }
        string retPic = PicClause(GetReturnType(def));
        sb.AppendLine($"       01 WS-{name}-RET     {retPic}.");
    }

    void EmitDefinitionParagraph(StringBuilder sb, IRDefinition def)
    {
        string name = Sanitize(def.Name).ToUpper();
        m_currentFunc = $"WS-{name}";

        sb.AppendLine($"      *> {def.Name}");
        sb.AppendLine($"       {name}-PARA.");

        if (HasSelfTailCall(def))
        {
            sb.AppendLine($"       {name}-LOOP.");
            EmitTailCallBodyCobol(sb, def.Body, def.Name, def.Parameters);
            sb.AppendLine($"       {name}-END.");
        }
        else
        {
            string resVar = EmitExprToVar(sb, def.Body);
            sb.AppendLine($"           MOVE {resVar} TO WS-{name}-RET");
        }

        m_currentFunc = "";
    }

    void EmitTailCallBodyCobol(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters)
    {
        string name = Sanitize(funcName).ToUpper();

        switch (expr)
        {
            case IRIf iff:
            {
                string condVar = EmitExprToVar(sb, iff.Condition);
                sb.AppendLine($"           IF {condVar} NOT = 0");
                EmitTailCallBodyCobol(sb, iff.Then, funcName, parameters);
                sb.AppendLine("           ELSE");
                EmitTailCallBodyCobol(sb, iff.Else, funcName, parameters);
                sb.AppendLine("           END-IF");
                break;
            }

            case IRApply app when IsSelfCall(app, funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    string pname = Sanitize(parameters[i].Name).ToUpper();
                    string argVar = EmitExprToVar(sb, args[i]);
                    sb.AppendLine($"           MOVE {argVar} TO WS-{name}-{pname}");
                }
                sb.AppendLine($"           GO TO {name}-LOOP");
                break;
            }

            case IRLet let:
            {
                string letVar = EmitExprToVar(sb, let.Value);
                string letName = AllocVar(Sanitize(let.Name).ToUpper());
                string pic = PicClause(let.NameType);
                m_workingStorage.Add($"       01 {letName}       {pic}.");
                sb.AppendLine($"           MOVE {letVar} TO {letName}");
                EmitTailCallBodyCobol(sb, let.Body, funcName, parameters);
                break;
            }

            default:
            {
                string resVar = EmitExprToVar(sb, expr);
                sb.AppendLine($"           MOVE {resVar} TO WS-{name}-RET");
                sb.AppendLine($"           GO TO {name}-END");
                break;
            }
        }
    }

    string EmitExprToVar(StringBuilder sb, IRExpr expr)
    {
        switch (expr)
        {
            case IRIntegerLit lit:
                return lit.Value.ToString();

            case IRBoolLit lit:
                return lit.Value ? "1" : "0";

            case IRTextLit lit:
                return $"\"{EscapeString(lit.Value)}\"";

            case IRNumberLit lit:
                return lit.Value.ToString();

            case IRName name:
                if (name.Name == "True")
                {
                    return "1";
                }

                if (name.Name == "False")
                {
                    return "0";
                }

                if (name.Name == "Nothing")
                {
                    return "0";
                }

                return $"WS-{Sanitize(name.Name).ToUpper()}";

            case IRBinary bin:
            {
                string left = EmitExprToVar(sb, bin.Left);
                string right = EmitExprToVar(sb, bin.Right);
                string hint = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "SUM",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "DIFF",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "PROD",
                    IRBinaryOp.DivInt or IRBinaryOp.DivNum => "QUOT",
                    IRBinaryOp.Eq or IRBinaryOp.NotEq => "EQ",
                    IRBinaryOp.Lt or IRBinaryOp.Gt or IRBinaryOp.LtEq or IRBinaryOp.GtEq => "CMP",
                    _ => "RESULT"
                };
                string resultVar = AllocVar(hint);
                m_workingStorage.Add($"       01 {resultVar}       PIC S9(18).");

                switch (bin.Op)
                {
                    case IRBinaryOp.AddInt or IRBinaryOp.AddNum:
                        sb.AppendLine($"           ADD {left} {right} GIVING {resultVar}");
                        break;
                    case IRBinaryOp.SubInt or IRBinaryOp.SubNum:
                        sb.AppendLine($"           SUBTRACT {right} FROM {left} GIVING {resultVar}");
                        break;
                    case IRBinaryOp.MulInt or IRBinaryOp.MulNum:
                        sb.AppendLine($"           MULTIPLY {left} BY {right} GIVING {resultVar}");
                        break;
                    case IRBinaryOp.DivInt or IRBinaryOp.DivNum:
                        sb.AppendLine($"           DIVIDE {left} BY {right} GIVING {resultVar}");
                        break;
                    case IRBinaryOp.Eq:
                        sb.AppendLine($"           IF {left} = {right}");
                        sb.AppendLine($"             MOVE 1 TO {resultVar}");
                        sb.AppendLine("           ELSE");
                        sb.AppendLine($"             MOVE 0 TO {resultVar}");
                        sb.AppendLine("           END-IF");
                        break;
                    case IRBinaryOp.NotEq:
                        sb.AppendLine($"           IF {left} NOT = {right}");
                        sb.AppendLine($"             MOVE 1 TO {resultVar}");
                        sb.AppendLine("           ELSE");
                        sb.AppendLine($"             MOVE 0 TO {resultVar}");
                        sb.AppendLine("           END-IF");
                        break;
                    case IRBinaryOp.Lt:
                        sb.AppendLine($"           IF {left} < {right}");
                        sb.AppendLine($"             MOVE 1 TO {resultVar}");
                        sb.AppendLine("           ELSE");
                        sb.AppendLine($"             MOVE 0 TO {resultVar}");
                        sb.AppendLine("           END-IF");
                        break;
                    case IRBinaryOp.Gt:
                        sb.AppendLine($"           IF {left} > {right}");
                        sb.AppendLine($"             MOVE 1 TO {resultVar}");
                        sb.AppendLine("           ELSE");
                        sb.AppendLine($"             MOVE 0 TO {resultVar}");
                        sb.AppendLine("           END-IF");
                        break;
                    case IRBinaryOp.LtEq:
                        sb.AppendLine($"           IF {left} <= {right}");
                        sb.AppendLine($"             MOVE 1 TO {resultVar}");
                        sb.AppendLine("           ELSE");
                        sb.AppendLine($"             MOVE 0 TO {resultVar}");
                        sb.AppendLine("           END-IF");
                        break;
                    case IRBinaryOp.GtEq:
                        sb.AppendLine($"           IF {left} >= {right}");
                        sb.AppendLine($"             MOVE 1 TO {resultVar}");
                        sb.AppendLine("           ELSE");
                        sb.AppendLine($"             MOVE 0 TO {resultVar}");
                        sb.AppendLine("           END-IF");
                        break;
                    case IRBinaryOp.AppendText:
                    {
                        string txtVar = AllocTextVar("JOINED");
                        m_workingStorage.Add($"       01 {txtVar}       PIC X(256).");
                        sb.AppendLine($"           STRING {left} DELIMITED BY SPACE");
                        sb.AppendLine($"                  {right} DELIMITED BY SPACE");
                        sb.AppendLine($"                  INTO {txtVar}");
                        return txtVar;
                    }
                    default:
                        sb.AppendLine($"           ADD {left} {right} GIVING {resultVar}");
                        break;
                }
                return resultVar;
            }

            case IRNegate neg:
            {
                string inner = EmitExprToVar(sb, neg.Operand);
                string resultVar = AllocVar("NEG");
                m_workingStorage.Add($"       01 {resultVar}       PIC S9(18).");
                sb.AppendLine($"           MULTIPLY {inner} BY -1 GIVING {resultVar}");
                return resultVar;
            }

            case IRIf iff:
            {
                string condVar = EmitExprToVar(sb, iff.Condition);
                string resultVar = AllocVar("BRANCH");
                m_workingStorage.Add($"       01 {resultVar}       PIC S9(18).");
                sb.AppendLine($"           IF {condVar} NOT = 0");
                string thenVar = EmitExprToVar(sb, iff.Then);
                sb.AppendLine($"             MOVE {thenVar} TO {resultVar}");
                sb.AppendLine("           ELSE");
                string elseVar = EmitExprToVar(sb, iff.Else);
                sb.AppendLine($"             MOVE {elseVar} TO {resultVar}");
                sb.AppendLine("           END-IF");
                return resultVar;
            }

            case IRLet let:
            {
                string letVar = EmitExprToVar(sb, let.Value);
                string letName = AllocVar(Sanitize(let.Name).ToUpper());
                string pic = PicClause(let.NameType);
                m_workingStorage.Add($"       01 {letName}       {pic}.");
                sb.AppendLine($"           MOVE {letVar} TO {letName}");
                return EmitExprToVar(sb, let.Body);
            }

            case IRApply app:
                return EmitApplyToVar(sb, app);

            case IRRecord rec:
            {
                string recName = Sanitize(rec.TypeName).ToUpper();
                string resultVar = $"WS-{recName}";
                for (int i = 0; i < rec.Fields.Length; i++)
                {
                    string fieldVal = EmitExprToVar(sb, rec.Fields[i].Value);
                    string fieldName = Sanitize(rec.Fields[i].FieldName).ToUpper();
                    sb.AppendLine($"           MOVE {fieldVal} TO WS-{recName}-{fieldName}");
                }
                return resultVar;
            }

            case IRFieldAccess fa:
            {
                string recVar = EmitExprToVar(sb, fa.Record);
                string fieldName = Sanitize(fa.FieldName).ToUpper();
                return $"{recVar}-{fieldName}";
            }

            case IRMatch match:
            {
                string scrutVar = EmitExprToVar(sb, match.Scrutinee);
                string resultVar = AllocVar("MATCH");
                string pic = PicClause(match.Type);
                m_workingStorage.Add($"       01 {resultVar}       {pic}.");
                sb.AppendLine($"           EVALUATE {scrutVar}-TAG");
                foreach (IRMatchBranch branch in match.Branches)
                {
                    if (branch.Pattern is IRCtorPattern ctorPat)
                    {
                        string ctorName = Sanitize(ctorPat.Name).ToUpper();
                        sb.AppendLine($"             WHEN TAG-{ctorName}");
                        string branchVar = EmitExprToVar(sb, branch.Body);
                        sb.AppendLine($"               MOVE {branchVar} TO {resultVar}");
                    }
                    else
                    {
                        sb.AppendLine("             WHEN OTHER");
                        string branchVar = EmitExprToVar(sb, branch.Body);
                        sb.AppendLine($"               MOVE {branchVar} TO {resultVar}");
                    }
                }
                sb.AppendLine("           END-EVALUATE");
                return resultVar;
            }

            default:
                return "0";
        }
    }

    string EmitApplyToVar(StringBuilder sb, IRApply app)
    {
        if (app.Function is IRName fn && fn.Name == "print-line")
        {
            string argVar = EmitExprToVar(sb, app.Argument);
            sb.AppendLine($"           DISPLAY {argVar}");
            return "0";
        }
        else if (app.Function is IRName fn2 && fn2.Name == "show")
        {
            return EmitExprToVar(sb, app.Argument);
        }
        else if (app.Function is IRName fn3 && fn3.Name == "negate")
        {
            string argVar = EmitExprToVar(sb, app.Argument);
            string resultVar = AllocVar("NEG");
            m_workingStorage.Add($"       01 {resultVar}       PIC S9(18).");
            sb.AppendLine($"           MULTIPLY {argVar} BY -1 GIVING {resultVar}");
            return resultVar;
        }

        string? defName = FindDefinitionName(app);
        if (defName is not null
            && m_definitionArity.TryGet(defName, out int arity))
        {
            List<IRExpr> args = [];
            CollectApplyArgs(app, args);
            string name = Sanitize(defName).ToUpper();

            IRDefinition? targetDef = m_definitions[defName];
            for (int i = 0; i < args.Count && i < arity; i++)
            {
                string argVar = EmitExprToVar(sb, args[i]);
                string pname = targetDef is not null && i < targetDef.Parameters.Length
                    ? Sanitize(targetDef.Parameters[i].Name).ToUpper()
                    : $"ARG{i}";
                sb.AppendLine($"           MOVE {argVar} TO WS-{name}-{pname}");
            }
            sb.AppendLine($"           PERFORM {name}-PARA");
            return $"WS-{name}-RET";
        }

        string fallback = EmitExprToVar(sb, app.Argument);
        return fallback;
    }

    void EmitStatementCobol(StringBuilder sb, IRExpr expr)
    {
        if (expr is IRDo doExpr)
        {
            foreach (IRDoStatement stmt in doExpr.Statements)
            {
                switch (stmt)
                {
                    case IRDoExec exec:
                        EmitExprToVar(sb, exec.Expression);
                        break;
                    case IRDoBind bind:
                        sb.AppendLine($"      *>   bind: {bind.Name}");
                        break;
                }
            }
        }
        else
        {
            EmitExprToVar(sb, expr);
        }
    }

    string AllocVar(string hint = "TEMP")
    {
        m_varCounter++;
        string prefix = m_currentFunc.Length > 0 ? m_currentFunc : "WS";
        return $"{prefix}-{hint}-{m_varCounter}";
    }

    string AllocTextVar(string hint = "TEXT")
    {
        m_varCounter++;
        string prefix = m_currentFunc.Length > 0 ? m_currentFunc : "WS";
        return $"{prefix}-{hint}-{m_varCounter}";
    }

    static string PicClause(CodexType type) => type switch
    {
        IntegerType => "PIC S9(18)",
        NumberType => "PIC S9(18)",
        TextType => "PIC X(256)",
        BooleanType => "PIC 9(1)",
        _ => "PIC S9(18)"
    };

    static CodexType GetReturnType(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType)
            {
                type = pft.Return;
            }

            if (type is FunctionType ft)
            {
                type = ft.Return;
            }
            else if (type is DependentFunctionType dep)
            {
                type = dep.Body;
            }
            else
            {
                break;
            }
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType)
        {
            type = pft2.Return;
        }

        if (type is EffectfulType eft)
        {
            type = eft.Return;
        }

        return type;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
        {
            current = inner.Function;
        }

        return current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]) ? name.Name : null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner)
        {
            CollectApplyArgs(inner, args);
        }

        args.Add(app.Argument);
    }

    static Set<string> CollectConstructorNames(IRChapter module)
    {
        Set<string> names = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            if (kv.Value is SumType sum)
            {
                foreach (SumConstructorType ctor in sum.Constructors)
                {
                    names = names.Add(ctor.Name.Value);
                }
            }
        }

        return names;
    }

    static bool HasSelfTailCall(IRDefinition def) =>
        def.Parameters.Length > 0 && ExprHasTailCall(def.Body, def.Name);

    static bool ExprHasTailCall(IRExpr expr, string funcName) => expr switch
    {
        IRIf iff => ExprHasTailCall(iff.Then, funcName) || ExprHasTailCall(iff.Else, funcName),
        IRLet let => ExprHasTailCall(let.Body, funcName),
        IRMatch match => match.Branches.Any(b => ExprHasTailCall(b.Body, funcName)),
        IRApply app => IsSelfCall(app, funcName),
        _ => false
    };

    static bool IsSelfCall(IRApply app, string funcName)
    {
        IRExpr root = app.Function;
        while (root is IRApply inner)
        {
            root = inner.Function;
        }

        return root is IRName name && name.Name == funcName;
    }

    static bool IsEffectfulDefinition(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType)
            {
                type = pft.Return;
            }

            if (type is FunctionType ft)
            {
                type = ft.Return;
            }
            else if (type is DependentFunctionType dep)
            {
                type = dep.Body;
            }
            else
            {
                break;
            }
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType)
        {
            type = pft2.Return;
        }

        return type is EffectfulType;
    }

    static string Sanitize(string name) => name.Replace('-', '_');

    static string EscapeString(string value) => value.Replace("\"", "\"\"");

    static Map<string, string> BuildCtorTagMap(IRChapter module)
    {
        Map<string, string> map = Map<string, string>.s_empty;
        int tagCounter = 0;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            if (kv.Value is SumType sum)
            {
                foreach (SumConstructorType ctor in sum.Constructors)
                {
                    map = map.Set(ctor.Name.Value, (++tagCounter).ToString());
                }
            }
        }

        return map;
    }
}
