// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func max(x int64, y int64) int64 {
	return func() int64 { if (x > y) { return x } else { return y } }()
}

func abs(x int64) int64 {
	return func() int64 { if (x < int64(0)) { return (-x) } else { return x } }()
}

func clamp(lo int64, hi int64, x int64) int64 {
	return func() int64 { clamped := func() int64 { if (x < lo) { return lo } else { return func() int64 { if (x > hi) { return hi } else { return x } }() } }(); return clamped }()
}

func main() {
	fmt.Println(clamp(int64(0), int64(100), abs(max((-int64(42)), int64(37)))))
}
