// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func greet(name string) {
	fmt.Println(("Hello, " + (name + "!")))
}

func main() {
	greet("Alice")
	greet("Bob")
	fmt.Println("Done!")
}
