// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

type Expr interface { isExpr() }

type Lit struct {
	Field0 int64
}
func (Lit) isExpr() {}

type Add struct {
	Field0 interface{}
	Field1 interface{}
}
func (Add) isExpr() {}

type Sub struct {
	Field0 interface{}
	Field1 interface{}
}
func (Sub) isExpr() {}

type Mul struct {
	Field0 interface{}
	Field1 interface{}
}
func (Mul) isExpr() {}

type Div struct {
	Field0 interface{}
	Field1 interface{}
}
func (Div) isExpr() {}

type ParseResult struct {
	Expr interface{}
	Pos int64
}

func skip_ws(input string, pos int64) int64 {
	for {
		if (pos >= int64(len(input))) {
			return pos
		} else {
			if (len(string(input[pos])) > 0 && (string(input[pos])[0] == ' ' || string(input[pos])[0] == '\t')) {
				_tco_0 := input
				_tco_1 := (pos + int64(1))
				input = _tco_0
				pos = _tco_1
				continue
			} else {
				return pos
			}
		}
	}
}

func collect_digits(input string, pos int64, len int64, acc int64) int64 {
	for {
		if (pos >= len) {
			return acc
		} else {
			if (len(string(input[pos])) > 0 && string(input[pos])[0] >= '0' && string(input[pos])[0] <= '9') {
				d := func() int64 { v, _ := strconv.ParseInt(string(input[pos]), 10, 64); return v }()
				_tco_0 := input
				_tco_1 := (pos + int64(1))
				_tco_2 := len
				_tco_3 := ((acc * int64(10)) + d)
				input = _tco_0
				pos = _tco_1
				len = _tco_2
				acc = _tco_3
				continue
			} else {
				return acc
			}
		}
	}
}

func digit_count(input string, pos int64, len int64) int64 {
	return func() int64 { if (pos >= len) { return int64(0) } else { return func() int64 { if (len(string(input[pos])) > 0 && string(input[pos])[0] >= '0' && string(input[pos])[0] <= '9') { return (int64(1) + digit_count(input, (pos + int64(1)), len)) } else { return int64(0) } }() } }()
}

func parse_atom(input string, start int64) ParseResult {
	return func() ParseResult { pos := skip_ws(input, start); return func() ParseResult { len := int64(len(input)); return func() ParseResult { if (pos >= len) { return ParseResult{Lit{int64(0)}, pos} } else { return func() ParseResult { if (string(input[pos]) == "(") { return func() ParseResult { inner := parse_additive(input, (pos + int64(1))); return func() ParseResult { after := skip_ws(input, inner.Pos); return func() ParseResult { if (after < len) { return ParseResult{inner.Expr, (after + int64(1))} } else { return ParseResult{inner.Expr, after} } }() }() }() } else { return func() ParseResult { digits := digit_count(input, pos, len); return func() ParseResult { if (digits > int64(0)) { return func() ParseResult { value := collect_digits(input, pos, len, int64(0)); return ParseResult{Lit{value}, (pos + digits)} }() } else { return ParseResult{Lit{int64(0)}, pos} } }() }() } }() } }() }() }()
}

func parse_multiplicative(input string, start int64) ParseResult {
	return func() ParseResult { left := parse_atom(input, start); return continue_multiplicative(input, left) }()
}

func continue_multiplicative(input string, current ParseResult) ParseResult {
	for {
		pos := skip_ws(input, current.Pos)
		len := int64(len(input))
		if (pos >= len) {
			return current
		} else {
			if (string(input[pos]) == "*") {
				right := parse_atom(input, (pos + int64(1)))
				_tco_0 := input
				_tco_1 := ParseResult{Mul{current.Expr, right.Expr}, right.Pos}
				input = _tco_0
				current = _tco_1
				continue
			} else {
				if (string(input[pos]) == "/") {
					right := parse_atom(input, (pos + int64(1)))
					_tco_0 := input
					_tco_1 := ParseResult{Div{current.Expr, right.Expr}, right.Pos}
					input = _tco_0
					current = _tco_1
					continue
				} else {
					return current
				}
			}
		}
	}
}

func parse_additive(input string, start int64) ParseResult {
	return func() ParseResult { left := parse_multiplicative(input, start); return continue_additive(input, left) }()
}

func continue_additive(input string, current ParseResult) ParseResult {
	for {
		pos := skip_ws(input, current.Pos)
		len := int64(len(input))
		if (pos >= len) {
			return current
		} else {
			if (string(input[pos]) == "+") {
				right := parse_multiplicative(input, (pos + int64(1)))
				_tco_0 := input
				_tco_1 := ParseResult{Add{current.Expr, right.Expr}, right.Pos}
				input = _tco_0
				current = _tco_1
				continue
			} else {
				if (string(input[pos]) == "-") {
					right := parse_multiplicative(input, (pos + int64(1)))
					_tco_0 := input
					_tco_1 := ParseResult{Sub{current.Expr, right.Expr}, right.Pos}
					input = _tco_0
					current = _tco_1
					continue
				} else {
					return current
				}
			}
		}
	}
}

func parse(input string) Expr {
	return parse_additive(input, int64(0)).Expr
}

func eval(e Expr) int64 {
	return func() int64 { switch _v := (e).(type) { case Lit: n := _v.Field0; return n; case Add: a := _v.Field0; b := _v.Field1; return (eval(a) + eval(b)); case Sub: a := _v.Field0; b := _v.Field1; return (eval(a) - eval(b)); case Mul: a := _v.Field0; b := _v.Field1; return (eval(a) * eval(b)); case Div: a := _v.Field0; b := _v.Field1; return (eval(a) / eval(b)); default: panic("non-exhaustive") } }()
}

func format(e Expr) string {
	return func() string { switch _v := (e).(type) { case Lit: n := _v.Field0; return fmt.Sprint(n); case Add: a := _v.Field0; b := _v.Field1; return ("(" + (format(a) + (" + " + (format(b) + ")")))); case Sub: a := _v.Field0; b := _v.Field1; return ("(" + (format(a) + (" - " + (format(b) + ")")))); case Mul: a := _v.Field0; b := _v.Field1; return ("(" + (format(a) + (" * " + (format(b) + ")")))); case Div: a := _v.Field0; b := _v.Field1; return ("(" + (format(a) + (" / " + (format(b) + ")")))); default: panic("non-exhaustive") } }()
}

func test_expr(input string, expected int64) string {
	return func() string { tree := parse(input); return func() string { result := eval(tree); return func() string { status := func() string { if (result == expected) { return "PASS" } else { return "FAIL" } }(); return (status + (": " + (input + (" = " + (fmt.Sprint(result) + (" (expected " + (fmt.Sprint(expected) + (")  tree: " + format(tree))))))))) }() }() }()
}

func main() {
	fmt.Println("=== Expression Calculator ===")
	fmt.Println("")
	fmt.Println(test_expr("42", int64(42)))
	fmt.Println(test_expr("2 + 3", int64(5)))
	fmt.Println(test_expr("10 - 4", int64(6)))
	fmt.Println(test_expr("3 * 7", int64(21)))
	fmt.Println(test_expr("100 / 5", int64(20)))
	fmt.Println(test_expr("2 + 3 * 4", int64(14)))
	fmt.Println(test_expr("10 - 2 * 3", int64(4)))
	fmt.Println(test_expr("(2 + 3) * 4", int64(20)))
	fmt.Println(test_expr("1 + 2 + 3 + 4", int64(10)))
	fmt.Println(test_expr("2 * 3 + 4 * 5", int64(26)))
	fmt.Println("")
	fmt.Println("All PASS = compiler correctly compiles a recursive descent parser.")
	fmt.Println("QED: not a quine.")
}
