// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func abs(x int64) int64 {
	return func() int64 { if (x < int64(0)) { return (-x) } else { return x } }()
}

func max(x int64, y int64) int64 {
	return func() int64 { if (x > y) { return x } else { return y } }()
}

func factorial(n int64) int64 {
	return func() int64 { if (n == int64(0)) { return int64(1) } else { return (n * factorial((n - int64(1)))) } }()
}

func main() {
	fmt.Println(factorial(int64(10)))
}
