// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func fib(n int64) int64 {
	return func() int64 { if (n == int64(0)) { return int64(0) } else { return func() int64 { if (n == int64(1)) { return int64(1) } else { return (fib((n - int64(1))) + fib((n - int64(2)))) } }() } }()
}

func main() {
	fmt.Println(fib(int64(20)))
}
