// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func square(x int64) int64 {
	return (x * x)
}

func double(x int64) int64 {
	return (x + x)
}

func main() {
	fmt.Println(square(int64(5)))
}
