// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func _range(lo int64, hi int64) []int64 {
	return func() []int64 { if (lo > hi) { return []int64{} } else { return append([]int64{lo}, _range((lo + int64(1)), hi)...) } }()
}

func divides(d int64, n int64) bool {
	return (((n / d) * d) == n)
}

func has_no_divisors_in(divisors []int64, n int64, i int64, len int64) bool {
	for {
		if (i == len) {
			return true
		} else {
			d := divisors[i]
			if divides(d, n) {
				return false
			} else {
				_tco_0 := divisors
				_tco_1 := n
				_tco_2 := (i + int64(1))
				_tco_3 := len
				divisors = _tco_0
				n = _tco_1
				i = _tco_2
				len = _tco_3
				continue
			}
		}
	}
}

func small_divisors(xs []int64, limit int64, i int64, len int64) []int64 {
	for {
		if (i == len) {
			return []int64{}
		} else {
			x := xs[i]
			if ((x * x) <= limit) {
				return append([]int64{x}, small_divisors(xs, limit, (i + int64(1)), len)...)
			} else {
				_tco_0 := xs
				_tco_1 := limit
				_tco_2 := (i + int64(1))
				_tco_3 := len
				xs = _tco_0
				limit = _tco_1
				i = _tco_2
				len = _tco_3
				continue
			}
		}
	}
}

func is_prime(n int64) bool {
	return func() bool { if (n < int64(2)) { return false } else { return func() bool { candidates := _range(int64(2), n); return func() bool { small := small_divisors(candidates, n, int64(0), int64(len(candidates))); return has_no_divisors_in(small, n, int64(0), int64(len(small))) }() }() } }()
}

func collect_primes(xs []int64, i int64, len int64) []string {
	for {
		if (i == len) {
			return []string{}
		} else {
			x := xs[i]
			if is_prime(x) {
				return append([]string{fmt.Sprint(x)}, collect_primes(xs, (i + int64(1)), len)...)
			} else {
				_tco_0 := xs
				_tco_1 := (i + int64(1))
				_tco_2 := len
				xs = _tco_0
				i = _tco_1
				len = _tco_2
				continue
			}
		}
	}
}

func join_with_spaces(xs []string, i int64, len int64) string {
	return func() string { if (i == len) { return "" } else { return func() string { if (i == (len - int64(1))) { return xs[i] } else { return (xs[i] + (" " + join_with_spaces(xs, (i + int64(1)), len))) } }() } }()
}

func main() {
	fmt.Println(func() string { candidates := _range(int64(2), int64(50)); return func() string { primes := collect_primes(candidates, int64(0), int64(len(candidates))); return ("Primes up to 50: " + join_with_spaces(primes, int64(0), int64(len(primes)))) }() }())
}
