// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

type Point struct {
	X int64
	Y int64
}

type Color interface { isColor() }

type Red struct {
}
func (Red) isColor() {}

type Green struct {
}
func (Green) isColor() {}

type Blue struct {
	Field0 int64
}
func (Blue) isColor() {}

func show_color(c Color) string {
	return func() string { switch _v := (c).(type) { case Red: return "red"; case Green: return "green"; case Blue: n := _v.Field0; return "blue"; default: panic("non-exhaustive") } }()
}

func get_x(p Point) int64 {
	return p.X
}

func add_points(a Point, b Point) Point {
	return Point{(a.X + b.X), (a.Y + b.Y)}
}

func map_list(f func(interface{}) interface{}, xs []interface{}) []interface{} {
	return map_list_loop(f, xs, int64(0), int64(len(xs)), []interface{}{})
}

func map_list_loop(f func(interface{}) interface{}, xs []interface{}, i int64, len int64, acc []interface{}) []interface{} {
	for {
		if (i == len) {
			return acc
		} else {
			_tco_0 := f
			_tco_1 := xs
			_tco_2 := (i + int64(1))
			_tco_3 := len
			_tco_4 := append(acc, []interface{}{f(xs[i])}...)
			f = _tco_0
			xs = _tco_1
			i = _tco_2
			len = _tco_3
			acc = _tco_4
			continue
		}
	}
}

func use_map(pts []Point) []int64 {
	return map_list(get_x, pts)
}

func main() {
	fmt.Println(use_map([]Point{Point{int64(1), int64(2)}}))
}
