// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

type Result interface { isResult() }

type Success struct {
	Field0 interface{}
}
func (Success) isResult() {}

type Failure struct {
	Field0 string
}
func (Failure) isResult() {}

func safe_divide(x int64, y int64) Result {
	return func() Result { if (y == int64(0)) { return Failure{"division by zero"} } else { return Success{(x / y)} } }()
}

func describe(result Result) string {
	return func() string { switch _v := (result).(type) { case Success: n := _v.Field0; return ("got " + fmt.Sprint(n)); case Failure: msg := _v.Field0; return ("error: " + msg); default: panic("non-exhaustive") } }()
}

func main() {
	fmt.Println(describe(safe_divide(int64(42), int64(7))))
}
