// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func is_identifier_char(ch string) bool {
	return func() bool { if (len(ch) > 0 && ((ch[0] >= 'a' && ch[0] <= 'z') || (ch[0] >= 'A' && ch[0] <= 'Z'))) { return true } else { return func() bool { if (len(ch) > 0 && ch[0] >= '0' && ch[0] <= '9') { return true } else { return func() bool { if (ch == "-") { return true } else { return false } }() } }() } }()
}

func count_letters(s string, i int64, acc int64) int64 {
	for {
		if (i >= int64(len(s))) {
			return acc
		} else {
			ch := string(s[i])
			if (len(ch) > 0 && ((ch[0] >= 'a' && ch[0] <= 'z') || (ch[0] >= 'A' && ch[0] <= 'Z'))) {
				_tco_0 := s
				_tco_1 := (i + int64(1))
				_tco_2 := (acc + int64(1))
				s = _tco_0
				i = _tco_1
				acc = _tco_2
				continue
			} else {
				_tco_0 := s
				_tco_1 := (i + int64(1))
				_tco_2 := acc
				s = _tco_0
				i = _tco_1
				acc = _tco_2
				continue
			}
		}
	}
}

func main() {
	fmt.Println(count_letters("hello world 123", int64(0), int64(0)))
}
