// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func sum_to(n int64, acc int64) int64 {
	for {
		if (n == int64(0)) {
			return acc
		} else {
			_tco_0 := (n - int64(1))
			_tco_1 := (acc + n)
			n = _tco_0
			acc = _tco_1
			continue
		}
	}
}

func main() {
	fmt.Println(sum_to(int64(1000000), int64(0)))
}
