// Generated by Codex compiler — Go backend
package main

import (
	"fmt"
	"strings"
	"strconv"
	"math"
	"os"
	"bufio"
)

var _ = fmt.Sprint
var _ = strings.Replace
var _ = strconv.Itoa
var _ = math.Pow
var _ = os.Open
var _ = bufio.NewReader

func add_one(x int64) int64 {
	return (x + int64(1))
}

func double(x int64) int64 {
	return (x * int64(2))
}

func greet(name string) string {
	return ("Hello, " + (name + "!"))
}

func is_positive(x int64) bool {
	return (x > int64(0))
}

func apply_twice(f func(int64) int64, x int64) int64 {
	return f(f(x))
}

func main() {
	fmt.Println(apply_twice(add_one, int64(40)))
}
