using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Ada;

public sealed class AdaEmitter : ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;
    Map<string, string> m_ctorToTag = Map<string, string>.s_empty;

    public string TargetName => "Ada";
    public string FileExtension => ".adb";

    public string Emit(IRChapter module)
    {
        m_constructorNames = CollectConstructorNames(module);
        m_ctorToTag = BuildCtorTagMap(module);
        m_definitionArity = ValueMap<string, int>.s_empty;
        foreach (IRDefinition d in module.Definitions)
        {
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);
        }

        string packageName = Capitalize(Sanitize(module.Name.Parts.Count > 0
            ? module.Name.Parts[module.Name.Parts.Count - 1].Value : "Main"));

        Set<string> typeNames = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            typeNames = typeNames.Add(Capitalize(Sanitize(kv.Key)));
        }

        if (typeNames.Contains(packageName))
        {
            packageName += "_Main";
        }

        StringBuilder sb = new();
        sb.AppendLine("-- Generated by Codex compiler — Ada backend");
        sb.AppendLine("-- Compile: gnatmake -gnat2012 " + packageName.ToLower() + ".adb");
        sb.AppendLine("with Ada.Text_IO; use Ada.Text_IO;");
        sb.AppendLine("with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;");
        sb.AppendLine("with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;");
        sb.AppendLine();

        sb.AppendLine($"procedure {packageName} is");
        sb.AppendLine();

        EmitTypeDefinitions(sb, module);

        IRDefinition? mainDef = module.Definitions
            .FirstOrDefault(d => d.Name == "main" && d.Parameters.Length == 0);

        foreach (IRDefinition def in module.Definitions)
        {
            if (def == mainDef)
            {
                continue;
            }

            EmitDefinition(sb, def);
            sb.AppendLine();
        }

        sb.AppendLine("begin");
        if (mainDef is not null)
        {
            if (IsEffectfulDefinition(mainDef))
            {
                EmitStatement(sb, mainDef.Body, 1);
            }
            else
            {
                CodexType retType = GetReturnType(mainDef);
                if (retType is IntegerType)
                {
                    sb.Append("   Put(Long_Long_Integer'Image(");
                    EmitExpr(sb, mainDef.Body, 1);
                    sb.AppendLine("));");
                    sb.AppendLine("   New_Line;");
                }
                else if (retType is NumberType)
                {
                    sb.Append("   Put(Long_Float'Image(");
                    EmitExpr(sb, mainDef.Body, 1);
                    sb.AppendLine("));");
                    sb.AppendLine("   New_Line;");
                }
                else if (retType is TextType)
                {
                    sb.Append("   Put_Line(To_String(");
                    EmitExpr(sb, mainDef.Body, 1);
                    sb.AppendLine("));");
                }
                else
                {
                    sb.Append("   Put_Line(\"<result>\");");
                    sb.AppendLine();
                }
            }
        }
        else
        {
            if (module.Definitions.Length == 0)
            {
                sb.AppendLine("   Put_Line(\"All proofs verified at compile time.\");");
            }
            else
            {
                sb.AppendLine("   null;");
            }
        }
        sb.AppendLine($"end {packageName};");
        return sb.ToString();
    }

    static void EmitTypeDefinitions(StringBuilder sb, IRChapter module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    EmitSumType(sb, sum);
                    break;
                case RecordType rec:
                    EmitRecordType(sb, rec);
                    break;
            }
        }
    }

    static void EmitSumType(StringBuilder sb, SumType sum)
    {
        string baseName = Capitalize(Sanitize(sum.TypeName.Value));

        sb.Append($"   type {baseName}_Tag is (");
        for (int i = 0; i < sum.Constructors.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append($"Tag_{Capitalize(Sanitize(sum.Constructors[i].Name.Value))}");
        }
        sb.AppendLine(");");

        int maxFields = 0;
        foreach (SumConstructorType ctor in sum.Constructors)
        {
            if (ctor.Fields.Length > maxFields)
            {
                maxFields = ctor.Fields.Length;
            }
        }

        sb.AppendLine($"   type {baseName}(Kind : {baseName}_Tag := {baseName}_Tag'First) is record");
        sb.AppendLine("      case Kind is");
        foreach (SumConstructorType ctor in sum.Constructors)
        {
            string tag = $"Tag_{Capitalize(Sanitize(ctor.Name.Value))}";
            sb.AppendLine($"         when {tag} =>");
            if (ctor.Fields.IsEmpty)
            {
                sb.AppendLine("            null;");
            }
            else
            {
                for (int i = 0; i < ctor.Fields.Length; i++)
                {
                    sb.AppendLine(
                        $"            {tag}_F{i} : {EmitType(ctor.Fields[i])};");
                }
            }
        }
        sb.AppendLine("      end case;");
        sb.AppendLine("   end record;");
        sb.AppendLine();
    }

    static void EmitRecordType(StringBuilder sb, RecordType rec)
    {
        string name = Capitalize(Sanitize(rec.TypeName.Value));
        sb.AppendLine($"   type {name} is record");
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            RecordFieldType field = rec.Fields[i];
            sb.AppendLine($"      {Capitalize(Sanitize(field.FieldName.Value))} : {EmitType(field.Type)};");
        }
        sb.AppendLine("   end record;");
        sb.AppendLine();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        string name = Capitalize(Sanitize(def.Name));
        CodexType retType = GetReturnType(def);
        bool isProc = IsEffectfulDefinition(def);

        if (HasSelfTailCall(def))
        {
            EmitTailCallDefinition(sb, def);
            return;
        }

        if (isProc)
        {
            sb.Append($"   procedure {name}");
            if (def.Parameters.Length > 0)
            {
                sb.Append('(');
                for (int i = 0; i < def.Parameters.Length; i++)
                {
                    if (i > 0)
                    {
                        sb.Append("; ");
                    }

                    sb.Append(
                        $"{Capitalize(Sanitize(def.Parameters[i].Name))} : {EmitType(def.Parameters[i].Type)}");
                }
                sb.Append(')');
            }
            sb.AppendLine(" is");
            sb.AppendLine("   begin");
            EmitStatement(sb, def.Body, 2);
            sb.AppendLine($"   end {name};");
        }
        else
        {
            sb.Append($"   function {name}");
            if (def.Parameters.Length > 0)
            {
                sb.Append('(');
                for (int i = 0; i < def.Parameters.Length; i++)
                {
                    if (i > 0)
                    {
                        sb.Append("; ");
                    }

                    sb.Append(
                        $"{Capitalize(Sanitize(def.Parameters[i].Name))} : {EmitType(def.Parameters[i].Type)}");
                }
                sb.Append(')');
            }
            sb.AppendLine($" return {EmitType(retType)} is");
            sb.AppendLine("   begin");
            sb.Append("      return ");
            EmitExpr(sb, def.Body, 2);
            sb.AppendLine(";");
            sb.AppendLine($"   end {name};");
        }
    }

    void EmitTailCallDefinition(StringBuilder sb, IRDefinition def)
    {
        string name = Capitalize(Sanitize(def.Name));
        CodexType retType = GetReturnType(def);

        sb.Append($"   function {name}");
        if (def.Parameters.Length > 0)
        {
            sb.Append('(');
            for (int i = 0; i < def.Parameters.Length; i++)
            {
                if (i > 0)
                {
                    sb.Append("; ");
                }

                sb.Append(
                    $"{Capitalize(Sanitize(def.Parameters[i].Name))}_0 : {EmitType(def.Parameters[i].Type)}");
            }
            sb.Append(')');
        }
        sb.AppendLine($" return {EmitType(retType)} is");

        for (int i = 0; i < def.Parameters.Length; i++)
        {
            string pname = Capitalize(Sanitize(def.Parameters[i].Name));
            sb.AppendLine($"      {pname} : {EmitType(def.Parameters[i].Type)} := {pname}_0;");
        }

        sb.AppendLine("   begin");
        sb.AppendLine("      loop");
        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, 3);
        sb.AppendLine("      end loop;");
        sb.AppendLine($"   end {name};");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 3);

        switch (expr)
        {
            case IRIf iff:
                sb.Append($"{pad}if ");
                EmitExpr(sb, iff.Condition, indent);
                sb.AppendLine(" then");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}else");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}end if;");
                break;

            case IRLet let:
                sb.AppendLine($"{pad}declare");
                sb.Append($"{pad}   {Capitalize(Sanitize(let.Name))} : constant {EmitType(let.NameType)} := ");
                EmitExpr(sb, let.Value, indent);
                sb.AppendLine(";");
                sb.AppendLine($"{pad}begin");
                EmitTailCallBody(sb, let.Body, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}end;");
                break;

            case IRApply app when IsSelfCall(app, funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    sb.Append($"{pad}{Capitalize(Sanitize(parameters[i].Name))} := ");
                    EmitExpr(sb, args[i], indent);
                    sb.AppendLine(";");
                }
                break;
            }

            default:
                sb.Append($"{pad}return ");
                EmitExpr(sb, expr, indent);
                sb.AppendLine(";");
                break;
        }
    }

    void EmitExpr(StringBuilder sb, IRExpr expr, int indent)
    {
        switch (expr)
        {
            case IRIntegerLit lit:
                sb.Append(lit.Value);
                break;

            case IRNumberLit lit:
                sb.Append($"Long_Float({lit.Value})");
                break;

            case IRTextLit lit:
                sb.Append($"To_Unbounded_String(\"{EscapeString(lit.Value)}\")");
                break;

            case IRBoolLit lit:
                sb.Append(lit.Value ? "True" : "False");
                break;

            case IRName name:
                if (name.Name == "read-line")
                {
                    sb.Append("To_Unbounded_String(Get_Line)");
                }
                else if (name.Name == "show")
                {
                    sb.Append("Long_Long_Integer'Image");
                }
                else if (name.Name == "True")
                {
                    sb.Append("True");
                }
                else if (name.Name == "False")
                {
                    sb.Append("False");
                }
                else if (name.Name == "Nothing")
                {
                    sb.Append("null");
                }
                else if (m_constructorNames.Contains(name.Name)
                    && name.Type is not FunctionType)
                {
                    string tag = m_ctorToTag[name.Name] ?? "";
                    sb.Append($"(Kind => {tag})");
                }
                else if (m_definitionArity.TryGet(name.Name, out int nameArity)
                    && nameArity == 0
                    && name.Type is not FunctionType)
                {
                    sb.Append($"{Capitalize(Sanitize(name.Name))}");
                }
                else
                {
                    sb.Append(Capitalize(Sanitize(name.Name)));
                }

                break;

            case IRBinary bin:
                EmitBinary(sb, bin, indent);
                break;

            case IRNegate neg:
                sb.Append("(-");
                EmitExpr(sb, neg.Operand, indent);
                sb.Append(')');
                break;

            case IRIf iff:
                sb.Append("(if ");
                EmitExpr(sb, iff.Condition, indent);
                sb.Append(" then ");
                EmitExpr(sb, iff.Then, indent);
                sb.Append(" else ");
                EmitExpr(sb, iff.Else, indent);
                sb.Append(')');
                break;

            case IRLet let:
                sb.Append($"(declare {Capitalize(Sanitize(let.Name))} : constant {EmitType(let.NameType)} := ");
                EmitExpr(sb, let.Value, indent);
                sb.Append(" begin ");
                EmitExpr(sb, let.Body, indent);
                sb.Append(')');
                break;

            case IRApply app:
                EmitApply(sb, app, indent);
                break;

            case IRLambda:
                sb.Append("null");
                break;

            case IRList list:
                sb.Append("(1 .. 0 => <>)");
                break;

            case IRMatch match:
                EmitMatch(sb, match, indent);
                break;

            case IRAct actExpr:
                EmitActExpr(sb, actExpr, indent);
                break;

            case IRRecord rec:
                sb.Append('(');
                for (int i = 0; i < rec.Fields.Length; i++)
                {
                    if (i > 0)
                    {
                        sb.Append(", ");
                    }

                    sb.Append($"{Capitalize(Sanitize(rec.Fields[i].FieldName))} => ");
                    EmitExpr(sb, rec.Fields[i].Value, indent);
                }
                sb.Append(')');
                break;

            case IRFieldAccess fa:
                EmitExpr(sb, fa.Record, indent);
                sb.Append('.');
                sb.Append(Capitalize(Sanitize(fa.FieldName)));
                break;

            case IRError err:
                sb.Append($"raise Program_Error");
                break;

            default:
                sb.Append("null");
                break;
        }
    }

    void EmitApply(StringBuilder sb, IRApply app, int indent)
    {
        if (app.Function is IRName fn && fn.Name == "show")
        {
            sb.Append("To_Unbounded_String(Long_Long_Integer'Image(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))");
        }
        else if (app.Function is IRName fn3 && fn3.Name == "print-line")
        {
            sb.Append("Put_Line(To_String(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))");
        }
        else if (app.Function is IRName fn7 && fn7.Name == "text-length")
        {
            sb.Append("Long_Long_Integer(Length(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))");
        }
        else if (app.Function is IRName fn11b && fn11b.Name == "integer-to-text")
        {
            sb.Append("To_Unbounded_String(Long_Long_Integer'Image(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("))");
        }
        else
        {
            EmitApplyGeneral(sb, app, indent);
        }
    }

    void EmitApplyGeneral(StringBuilder sb, IRApply app, int indent)
    {
        string? ctorName = FindConstructorName(app);
        if (ctorName is not null)
        {
            string tag = m_ctorToTag[ctorName] ?? $"Tag_{Capitalize(Sanitize(ctorName))}";
            List<IRExpr> args = [];
            CollectApplyArgs(app, args);
            sb.Append($"(Kind => {tag}");
            for (int i = 0; i < args.Count; i++)
            {
                sb.Append($", {tag}_F{i} => ");
                EmitExpr(sb, args[i], indent);
            }
            sb.Append(')');
        }
        else
        {
            string? defName = FindDefinitionName(app);
            if (defName is not null
                && m_definitionArity.TryGet(defName, out int arity)
                && arity > 1)
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                if (args.Count == arity)
                {
                    sb.Append($"{Capitalize(Sanitize(defName))}(");
                    for (int i = 0; i < args.Count; i++)
                    {
                        if (i > 0)
                        {
                            sb.Append(", ");
                        }

                        EmitExpr(sb, args[i], indent);
                    }
                    sb.Append(')');
                }
                else
                {
                    sb.Append($"{Capitalize(Sanitize(defName))}(");
                    EmitExpr(sb, app.Argument, indent);
                    sb.Append(')');
                }
            }
            else
            {
                EmitExpr(sb, app.Function, indent);
                sb.Append('(');
                EmitExpr(sb, app.Argument, indent);
                sb.Append(')');
            }
        }
    }

    void EmitBinary(StringBuilder sb, IRBinary bin, int indent)
    {
        switch (bin.Op)
        {
            case IRBinaryOp.AppendText:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" & ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.PowInt:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" ** Natural(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append("))");
                break;

            default:
                string op = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
                    IRBinaryOp.DivInt or IRBinaryOp.DivNum => "/",
                    IRBinaryOp.Eq => "=",
                    IRBinaryOp.NotEq => "/=",
                    IRBinaryOp.Lt => "<",
                    IRBinaryOp.Gt => ">",
                    IRBinaryOp.LtEq => "<=",
                    IRBinaryOp.GtEq => ">=",
                    IRBinaryOp.And => "and then",
                    IRBinaryOp.Or => "or else",
                    _ => "+"
                };
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append($" {op} ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;
        }
    }

    void EmitMatch(StringBuilder sb, IRMatch match, int indent)
    {
        sb.Append("(case ");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.Append(".Kind is ");

        foreach (IRMatchBranch branch in match.Branches)
        {
            switch (branch.Pattern)
            {
                case IRCtorPattern ctorPat:
                    string tag = $"Tag_{Capitalize(Sanitize(ctorPat.Name))}";
                    sb.Append($"when {tag} => ");
                    EmitExpr(sb, branch.Body, indent);
                    break;

                case IRWildcardPattern:
                case IRVarPattern:
                    sb.Append("when others => ");
                    EmitExpr(sb, branch.Body, indent);
                    break;
            }
            sb.Append(", ");
        }
        sb.Append("when others => raise Program_Error)");
    }

    void EmitActExpr(StringBuilder sb, IRAct actExpr, int indent)
    {
        sb.Append("null");
    }

    void EmitStatement(StringBuilder sb, IRExpr expr, int indent)
    {
        string pad = new(' ', indent * 3);
        if (expr is IRAct actExpr)
        {
            foreach (IRActStatement stmt in actExpr.Statements)
            {
                switch (stmt)
                {
                    case IRActBind bind:
                        sb.AppendLine($"{pad}-- bind: {Sanitize(bind.Name)}");
                        break;
                    case IRActExec exec:
                        sb.Append(pad);
                        EmitExpr(sb, exec.Expression, indent);
                        sb.AppendLine(";");
                        break;
                }
            }
        }
        else
        {
            sb.Append(pad);
            EmitExpr(sb, expr, indent);
            sb.AppendLine(";");
        }
    }

    static string EmitType(CodexType type) => type switch
    {
        IntegerType => "Long_Long_Integer",
        NumberType => "Long_Float",
        TextType => "Unbounded_String",
        BooleanType => "Boolean",
        NothingType => "Boolean",
        VoidType => "Boolean",
        EffectfulType eft => EmitType(eft.Return),
        LinearType lin => EmitType(lin.Inner),
        ForAllType fa => EmitType(fa.Body),
        RecordType rt => Capitalize(Sanitize(rt.TypeName.Value)),
        SumType st => Capitalize(Sanitize(st.TypeName.Value)),
        TypeVariable => "Long_Long_Integer",
        _ => "Long_Long_Integer"
    };

    static CodexType GetReturnType(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType)
            {
                type = pft.Return;
            }

            if (type is FunctionType ft)
            {
                type = ft.Return;
            }
            else if (type is DependentFunctionType dep)
            {
                type = dep.Body;
            }
            else
            {
                break;
            }
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType)
        {
            type = pft2.Return;
        }

        if (type is EffectfulType eft)
        {
            type = eft.Return;
        }

        return type;
    }

    static string? FindConstructorName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
        {
            current = inner.Function;
        }

        return current is IRName name && name.Name.Length > 0 && char.IsUpper(name.Name[0]) ? name.Name : null;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
        {
            current = inner.Function;
        }

        return current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]) ? name.Name : null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner)
        {
            CollectApplyArgs(inner, args);
        }

        args.Add(app.Argument);
    }

    static Set<string> CollectConstructorNames(IRChapter module)
    {
        Set<string> names = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            if (kv.Value is SumType sum)
            {
                foreach (SumConstructorType ctor in sum.Constructors)
                {
                    names = names.Add(ctor.Name.Value);
                }
            }
        }

        return names;
    }

    static Map<string, string> BuildCtorTagMap(IRChapter module)
    {
        Map<string, string> map = Map<string, string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            if (kv.Value is SumType sum)
            {
                foreach (SumConstructorType ctor in sum.Constructors)
                {
                    map = map.Set(ctor.Name.Value, $"Tag_{Capitalize(Sanitize(ctor.Name.Value))}");
                }
            }
        }

        return map;
    }

    static bool HasSelfTailCall(IRDefinition def) =>
        def.Parameters.Length > 0 && ExprHasTailCall(def.Body, def.Name);

    static bool ExprHasTailCall(IRExpr expr, string funcName) => expr switch
    {
        IRIf iff => ExprHasTailCall(iff.Then, funcName) || ExprHasTailCall(iff.Else, funcName),
        IRLet let => ExprHasTailCall(let.Body, funcName),
        IRMatch match => match.Branches.Any(b => ExprHasTailCall(b.Body, funcName)),
        IRApply app => IsSelfCall(app, funcName),
        _ => false
    };

    static bool IsSelfCall(IRApply app, string funcName)
    {
        IRExpr root = app.Function;
        while (root is IRApply inner)
        {
            root = inner.Function;
        }

        return root is IRName name && name.Name == funcName;
    }

    static bool IsEffectfulDefinition(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType)
            {
                type = pft.Return;
            }

            if (type is FunctionType ft)
            {
                type = ft.Return;
            }
            else if (type is DependentFunctionType dep)
            {
                type = dep.Body;
            }
            else
            {
                break;
            }
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType)
        {
            type = pft2.Return;
        }

        return type is EffectfulType;
    }

    static string Sanitize(string name)
    {
        string sanitized = name.Replace('-', '_');
        return sanitized switch
        {
            "begin" or "end" or "is" or "type" or "procedure" or "function" or "return"
            or "if" or "then" or "else" or "elsif" or "loop" or "while" or "for" or "exit"
            or "case" or "when" or "others" or "null" or "declare" or "package" or "body"
            or "use" or "with" or "in" or "out" or "of" or "new" or "all" or "access"
            or "record" or "array" or "range" or "constant" or "abs" or "not" or "and"
            or "or" or "xor" or "mod" or "rem" or "raise" or "exception" or "entry"
            or "select" or "accept" or "delay" or "task" or "protected" or "subtype"
            or "generic" or "limited" or "tagged" or "abstract" or "interface"
            or "overriding" or "separate" or "private" or "delta" or "digits"
                => $"{sanitized}_v",
            _ => sanitized
        };
    }

    static string Capitalize(string s) => s.Length == 0 ? s : char.ToUpper(s[0]) + s[1..];

    static string EscapeString(string value) => value
        .Replace("\"", "\"\"");
}
