// Generated by Codex compiler — JavaScript backend
"use strict";

function max(x, y) {
    return ((x > y) ? x : y);
}

function abs(x) {
    return ((x < 0n) ? (-x) : x);
}

function clamp(lo, hi, x) {
    return ((clamped) => clamped)(((x < lo) ? lo : ((x > hi) ? hi : x)));
}

function main() {
    return clamp(0n, 100n, abs(max((-42n), 37n)));
}

console.log(main());
