// Generated by Codex compiler — JavaScript backend
"use strict";

function main() {
    (() => {
        console.log("What is your name?");
        const name = (require('readline-sync').question(''));
        console.log(("Hello, " + (name + "!")));
    })();
}

main();
