// Generated by Codex compiler — JavaScript backend
"use strict";

function greet(name) {
    console.log(("Hello, " + (name + "!")));
}

function main() {
    (() => {
        greet("Alice");
        greet("Bob");
        console.log("Done!");
    })();
}

main();
