// Generated by Codex compiler — JavaScript backend
"use strict";

function abs(x) {
    return ((x < 0n) ? (-x) : x);
}

function max(x, y) {
    return ((x > y) ? x : y);
}

function factorial(n) {
    return ((n === 0n) ? 1n : (n * factorial((n - 1n))));
}

function main() {
    return factorial(10n);
}

console.log(main());
