// Generated by Codex compiler — JavaScript backend
"use strict";

function greeting(name) {
    return ("Hello, " + (name + "!"));
}

function main() {
    return greeting("World");
}

console.log(main());
