// Generated by Codex compiler — JavaScript backend
"use strict";

function square(x) {
    return (x * x);
}

function double(x) {
    return (x + x);
}

function main() {
    return square(5n);
}

console.log(main());
