// Generated by Codex compiler — JavaScript backend
"use strict";

function is_prime(n) {
    return ((n < 2n) ? false : check_divisor(n, 2n));
}

function check_divisor(n, d) {
    while (true) {
        if (((d * d) > n)) {
            return true;
        } else {
            if ((((n / d) * d) === n)) {
                return false;
            } else {
                const _tco_0 = n;
                const _tco_1 = (d + 1n);
                n = _tco_0;
                d = _tco_1;
                continue;
            }
        }
    }
}

function main() {
    return ((a) => ((b) => ((c) => ((d) => (String(a) + (" " + (String(b) + (" " + (String(c) + (" " + String(d))))))))(is_prime(97n)))(is_prime(49n)))(is_prime(17n)))(is_prime(2n));
}

console.log(main());
