// Generated by Codex compiler — JavaScript backend
"use strict";

function square(x) {
    return (x * x);
}

function cube(x) {
    return ((x * x) * x);
}

function helper(x) {
    return (x + 1n);
}

