// Generated by Codex compiler — JavaScript backend
"use strict";

function Person(name, age) { return Object.freeze({ name: name, age: age }); }

function greet(p) {
    return ("Hello, " + (p.name + "!"));
}

function main() {
    return greet(Person("Alice", 30n));
}

console.log(main());
