// Generated by Codex compiler — JavaScript backend
"use strict";

function Success(field0) { return Object.freeze({ tag: "Success", field0: field0 }); }
function Failure(field0) { return Object.freeze({ tag: "Failure", field0: field0 }); }

function safe_divide(x, y) {
    return ((y === 0n) ? Failure("division by zero") : Success((x / y)));
}

function describe(result) {
    return ((_s) => (_s.tag === "Success" ? (() => { const n = _s.field0; return ("got " + String(n)); })() : (_s.tag === "Failure" ? (() => { const msg = _s.field0; return ("error: " + msg); })() : (() => { throw new Error("Non-exhaustive match"); })())))(result);
}

function main() {
    return describe(safe_divide(42n, 7n));
}

console.log(main());
