// Generated by Codex compiler — JavaScript backend
"use strict";

function Circle(field0) { return Object.freeze({ tag: "Circle", field0: field0 }); }
function Rectangle(field0, field1) { return Object.freeze({ tag: "Rectangle", field0: field0, field1: field1 }); }

function main() {
    return ((_s) => (_s.tag === "Circle" ? (() => { const r = _s.field0; return ((3.14 * r) * r); })() : (_s.tag === "Rectangle" ? (() => { const w = _s.field0; const h = _s.field1; return (w * h); })() : (() => { throw new Error("Non-exhaustive match"); })())))(Circle(5.0));
}

console.log(main());
