// Generated by Codex compiler — JavaScript backend
"use strict";

function sum_to(n, acc) {
    while (true) {
        if ((n === 0n)) {
            return acc;
        } else {
            const _tco_0 = (n - 1n);
            const _tco_1 = (acc + n);
            n = _tco_0;
            acc = _tco_1;
            continue;
        }
    }
}

function main() {
    return sum_to(1000000n, 0n);
}

console.log(main());
