// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Effectful_hello {
    public static void main(String[] args) {
        System.out.println("What is your name?");
        var name = new java.util.Scanner(System.in).nextLine();
        System.out.println(("Hello, " + (name + "!")));
    }
}
