// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Effects_demo {
    public static void greet(String name) {
        System.out.println(("Hello, " + (name + "!")));
    }

    public static void main(String[] args) {
        greet.apply("Alice");
        greet.apply("Bob");
        System.out.println("Done!");
    }
}
