// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

sealed interface Expr {}
record Lit(long field0) implements Expr {}
record Add(Object field0, Object field1) implements Expr {}
record Sub(Object field0, Object field1) implements Expr {}
record Mul(Object field0, Object field1) implements Expr {}
record Div(Object field0, Object field1) implements Expr {}

record ParseResult(Object expr, long pos) {}

public class Expr_calculator {
    public static long skip_ws(String input, long pos) {
        while (true) {
            if ((pos >= (long)input.length())) {
                return pos;
            } else {
                if ((!String.valueOf(input.charAt((int)(long)pos)).isEmpty() && Character.isWhitespace(String.valueOf(input.charAt((int)(long)pos)).charAt(0)))) {
                    var _tco_0 = input;
                    var _tco_1 = (pos + 1L);
                    input = _tco_0;
                    pos = _tco_1;
                    continue;
                } else {
                    return pos;
                }
            }
        }
    }

    public static long collect_digits(String input, long pos, long len, long acc) {
        while (true) {
            if ((pos >= len)) {
                return acc;
            } else {
                if ((!String.valueOf(input.charAt((int)(long)pos)).isEmpty() && Character.isDigit(String.valueOf(input.charAt((int)(long)pos)).charAt(0)))) {
                    var d = Long.parseLong(String.valueOf(input.charAt((int)(long)pos)));
                    var _tco_0 = input;
                    var _tco_1 = (pos + 1L);
                    var _tco_2 = len;
                    var _tco_3 = ((acc * 10L) + d);
                    input = _tco_0;
                    pos = _tco_1;
                    len = _tco_2;
                    acc = _tco_3;
                    continue;
                } else {
                    return acc;
                }
            }
        }
    }

    public static long digit_count(String input, long pos, long len) {
        return ((pos >= len) ? 0L : ((!String.valueOf(input.charAt((int)(long)pos)).isEmpty() && Character.isDigit(String.valueOf(input.charAt((int)(long)pos)).charAt(0))) ? (1L + digit_count(input, (pos + 1L), len)) : 0L));
    }

    public static ParseResult parse_atom(String input, long start) {
        return ((Function<Long, ParseResult>)(pos -> ((Function<Long, ParseResult>)(len -> ((pos >= len) ? new ParseResult(new Lit(0L), pos) : (String.valueOf(input.charAt((int)(long)pos)).equals("(") ? ((Function<ParseResult, ParseResult>)(inner -> ((Function<Long, ParseResult>)(after -> ((after < len) ? new ParseResult(inner.expr(), (after + 1L)) : new ParseResult(inner.expr(), after)))).apply(skip_ws(input, inner.pos())))).apply(parse_additive(input, (pos + 1L))) : ((Function<Long, ParseResult>)(digits -> ((digits > 0L) ? ((Function<Long, ParseResult>)(value -> new ParseResult(new Lit(value), (pos + digits)))).apply(collect_digits(input, pos, len, 0L)) : new ParseResult(new Lit(0L), pos)))).apply(digit_count(input, pos, len)))))).apply((long)input.length()))).apply(skip_ws(input, start));
    }

    public static ParseResult parse_multiplicative(String input, long start) {
        return ((Function<ParseResult, ParseResult>)(left -> continue_multiplicative(input, left))).apply(parse_atom(input, start));
    }

    public static ParseResult continue_multiplicative(String input, ParseResult current) {
        while (true) {
            var pos = skip_ws(input, current.pos());
            var len = (long)input.length();
            if ((pos >= len)) {
                return current;
            } else {
                if (String.valueOf(input.charAt((int)(long)pos)).equals("*")) {
                    var right = parse_atom(input, (pos + 1L));
                    var _tco_0 = input;
                    var _tco_1 = new ParseResult(new Mul(current.expr(), right.expr()), right.pos());
                    input = _tco_0;
                    current = _tco_1;
                    continue;
                } else {
                    if (String.valueOf(input.charAt((int)(long)pos)).equals("/")) {
                        var right = parse_atom(input, (pos + 1L));
                        var _tco_0 = input;
                        var _tco_1 = new ParseResult(new Div(current.expr(), right.expr()), right.pos());
                        input = _tco_0;
                        current = _tco_1;
                        continue;
                    } else {
                        return current;
                    }
                }
            }
        }
    }

    public static ParseResult parse_additive(String input, long start) {
        return ((Function<ParseResult, ParseResult>)(left -> continue_additive(input, left))).apply(parse_multiplicative(input, start));
    }

    public static ParseResult continue_additive(String input, ParseResult current) {
        while (true) {
            var pos = skip_ws(input, current.pos());
            var len = (long)input.length();
            if ((pos >= len)) {
                return current;
            } else {
                if (String.valueOf(input.charAt((int)(long)pos)).equals("+")) {
                    var right = parse_multiplicative(input, (pos + 1L));
                    var _tco_0 = input;
                    var _tco_1 = new ParseResult(new Add(current.expr(), right.expr()), right.pos());
                    input = _tco_0;
                    current = _tco_1;
                    continue;
                } else {
                    if (String.valueOf(input.charAt((int)(long)pos)).equals("-")) {
                        var right = parse_multiplicative(input, (pos + 1L));
                        var _tco_0 = input;
                        var _tco_1 = new ParseResult(new Sub(current.expr(), right.expr()), right.pos());
                        input = _tco_0;
                        current = _tco_1;
                        continue;
                    } else {
                        return current;
                    }
                }
            }
        }
    }

    public static Expr parse(String input) {
        return parse_additive(input, 0L).expr();
    }

    public static long eval(Expr e) {
        return switch (e) { case Lit _m -> { var n = _m.field0(); yield n; } case Add _m -> { var a = _m.field0(); var b = _m.field1(); yield (eval(a) + eval(b)); } case Sub _m -> { var a = _m.field0(); var b = _m.field1(); yield (eval(a) - eval(b)); } case Mul _m -> { var a = _m.field0(); var b = _m.field1(); yield (eval(a) * eval(b)); } case Div _m -> { var a = _m.field0(); var b = _m.field1(); yield (eval(a) / eval(b)); } };
    }

    public static String format(Expr e) {
        return switch (e) { case Lit _m -> { var n = _m.field0(); yield String.valueOf(n); } case Add _m -> { var a = _m.field0(); var b = _m.field1(); yield ("(" + (format(a) + (" + " + (format(b) + ")")))); } case Sub _m -> { var a = _m.field0(); var b = _m.field1(); yield ("(" + (format(a) + (" - " + (format(b) + ")")))); } case Mul _m -> { var a = _m.field0(); var b = _m.field1(); yield ("(" + (format(a) + (" * " + (format(b) + ")")))); } case Div _m -> { var a = _m.field0(); var b = _m.field1(); yield ("(" + (format(a) + (" / " + (format(b) + ")")))); } };
    }

    public static String test_expr(String input, long expected) {
        return ((Function<Expr, String>)(tree -> ((Function<Long, String>)(result -> ((Function<String, String>)(status -> (status + (": " + (input + (" = " + (String.valueOf(result) + (" (expected " + (String.valueOf(expected) + (")  tree: " + format(tree))))))))))).apply(((result == expected) ? "PASS" : "FAIL")))).apply(eval(tree)))).apply(parse(input));
    }

    public static void main(String[] args) {
        System.out.println("=== Expression Calculator ===");
        System.out.println("");
        System.out.println(test_expr("42", 42L));
        System.out.println(test_expr("2 + 3", 5L));
        System.out.println(test_expr("10 - 4", 6L));
        System.out.println(test_expr("3 * 7", 21L));
        System.out.println(test_expr("100 / 5", 20L));
        System.out.println(test_expr("2 + 3 * 4", 14L));
        System.out.println(test_expr("10 - 2 * 3", 4L));
        System.out.println(test_expr("(2 + 3) * 4", 20L));
        System.out.println(test_expr("1 + 2 + 3 + 4", 10L));
        System.out.println(test_expr("2 * 3 + 4 * 5", 26L));
        System.out.println("");
        System.out.println("All PASS = compiler correctly compiles a recursive descent parser.");
        System.out.println("QED: not a quine.");
    }
}
