// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Factorial {
    public static long abs(long x) {
        return ((x < 0L) ? (-x) : x);
    }

    public static long max(long x, long y) {
        return ((x > y) ? x : y);
    }

    public static long factorial(long n) {
        return ((n == 0L) ? 1L : (n * factorial.apply((n - 1L))));
    }

    public static void main(String[] args) {
        System.out.println(factorial.apply(10L));
    }
}
