// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Fibonacci {
    public static long fib(long n) {
        return ((n == 0L) ? 0L : ((n == 1L) ? 1L : (fib((n - 1L)) + fib((n - 2L)))));
    }

    public static void main(String[] args) {
        System.out.println(fib(20L));
    }
}
