// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Hello {
    public static long square(long x) {
        return (x * x);
    }

    public static long _double(long x) {
        return (x + x);
    }

    public static void main(String[] args) {
        System.out.println(square.apply(5L));
    }
}
