// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Is_prime_fancy {
    public static ArrayList<Long> range(long lo, long hi) {
        return ((lo > hi) ? new ArrayList<>() : new ArrayList<>() {{ addAll(new ArrayList<>(List.of(lo))); addAll(range((lo + 1L), hi)); }});
    }

    public static boolean divides(long d, long n) {
        return (((n / d) * d) == n);
    }

    public static boolean has_no_divisors_in(ArrayList<Long> divisors, long n, long i, long len) {
        while (true) {
            if ((i == len)) {
                return true;
            } else {
                var d = divisors.get((int)(long)i);
                if (divides(d, n)) {
                    return false;
                } else {
                    var _tco_0 = divisors;
                    var _tco_1 = n;
                    var _tco_2 = (i + 1L);
                    var _tco_3 = len;
                    divisors = _tco_0;
                    n = _tco_1;
                    i = _tco_2;
                    len = _tco_3;
                    continue;
                }
            }
        }
    }

    public static ArrayList<Long> small_divisors(ArrayList<Long> xs, long limit, long i, long len) {
        while (true) {
            if ((i == len)) {
                return new ArrayList<>();
            } else {
                var x = xs.get((int)(long)i);
                if (((x * x) <= limit)) {
                    return new ArrayList<>() {{ addAll(new ArrayList<>(List.of(x))); addAll(small_divisors(xs, limit, (i + 1L), len)); }};
                } else {
                    var _tco_0 = xs;
                    var _tco_1 = limit;
                    var _tco_2 = (i + 1L);
                    var _tco_3 = len;
                    xs = _tco_0;
                    limit = _tco_1;
                    i = _tco_2;
                    len = _tco_3;
                    continue;
                }
            }
        }
    }

    public static boolean is_prime(long n) {
        return ((n < 2L) ? false : ((Function<ArrayList<Long>, Boolean>)(candidates -> ((Function<ArrayList<Long>, Boolean>)(small -> has_no_divisors_in(small, n, 0L, (long)small.size()))).apply(small_divisors(candidates, n, 0L, (long)candidates.size())))).apply(range(2L, n)));
    }

    public static ArrayList<String> collect_primes(ArrayList<Long> xs, long i, long len) {
        while (true) {
            if ((i == len)) {
                return new ArrayList<>();
            } else {
                var x = xs.get((int)(long)i);
                if (is_prime(x)) {
                    return new ArrayList<>() {{ addAll(new ArrayList<>(List.of(String.valueOf(x)))); addAll(collect_primes(xs, (i + 1L), len)); }};
                } else {
                    var _tco_0 = xs;
                    var _tco_1 = (i + 1L);
                    var _tco_2 = len;
                    xs = _tco_0;
                    i = _tco_1;
                    len = _tco_2;
                    continue;
                }
            }
        }
    }

    public static String join_with_spaces(ArrayList<String> xs, long i, long len) {
        return ((i == len) ? "" : ((i == (len - 1L)) ? xs.get((int)(long)i) : (xs.get((int)(long)i) + (" " + join_with_spaces(xs, (i + 1L), len)))));
    }

    public static void main(String[] args) {
        System.out.println(((Function<ArrayList<Long>, String>)(candidates -> ((Function<ArrayList<String>, String>)(primes -> ("Primes up to 50: " + join_with_spaces(primes, 0L, (long)primes.size())))).apply(collect_primes(candidates, 0L, (long)candidates.size())))).apply(range(2L, 50L)));
    }
}
