// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class MathLib {
    public static long square(long x) {
        return (x * x);
    }

    public static long cube(long x) {
        return ((x * x) * x);
    }

    public static long helper(long x) {
        return (x + 1L);
    }

    public static void main(String[] args) {
        System.out.println("Module loaded.");
    }
}
