// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

record Point(long x, long y) {}

sealed interface Color {}
record Red() implements Color {}
record Green() implements Color {}
record Blue(long field0) implements Color {}

public class Mini_bootstrap {
    public static String show_color(Color c) {
        return switch (c) { case Red _m -> "red"; case Green _m -> "green"; case Blue _m -> { var n = _m.field0(); yield "blue"; } };
    }

    public static long get_x(Point p) {
        return p.x();
    }

    public static Point add_points(Point a, Point b) {
        return new Point((a.x() + b.x()), (a.y() + b.y()));
    }

    public static ArrayList<Object> map_list(Function<Object, Object> f, ArrayList<Object> xs) {
        return map_list_loop(f, xs, 0L, (long)xs.size(), new ArrayList<>());
    }

    public static ArrayList<Object> map_list_loop(Function<Object, Object> f, ArrayList<Object> xs, long i, long len, ArrayList<Object> acc) {
        while (true) {
            if ((i == len)) {
                return acc;
            } else {
                var _tco_0 = f;
                var _tco_1 = xs;
                var _tco_2 = (i + 1L);
                var _tco_3 = len;
                var _tco_4 = new ArrayList<>() {{ addAll(acc); addAll(new ArrayList<>(List.of(f.apply(xs.get((int)(long)i))))); }};
                f = _tco_0;
                xs = _tco_1;
                i = _tco_2;
                len = _tco_3;
                acc = _tco_4;
                continue;
            }
        }
    }

    public static ArrayList<Long> use_map(ArrayList<Point> pts) {
        return map_list(get_x, pts);
    }

    public static void main(String[] args) {
        System.out.println(use_map.apply(new ArrayList<>(List.of(new Point(1L, 2L)))));
    }
}
