// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

record Person(String name, long age) {}

public class PersonModule {
    public static String greet(Person p) {
        return ("Hello, " + (p.name() + "!"));
    }

    public static void main(String[] args) {
        System.out.println(greet(new Person("Alice", 30L)));
    }
}
