// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Prose_greeting {
    public static String greet(String name) {
        return ("Hello, " + (name + "!"));
    }

    public static void main(String[] args) {
        System.out.println(greet.apply("World"));
    }
}
