// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

sealed interface Shape {}
record Circle(double field0) implements Shape {}
record Rectangle(double field0, double field1) implements Shape {}

public class Shapes {
    public static void main(String[] args) {
        System.out.println(switch (new Circle(5.0d)) { case Circle _m -> { var r = _m.field0(); yield ((3.14d * r) * r); } case Rectangle _m -> { var w = _m.field0(); var h = _m.field1(); yield (w * h); } });
    }
}
