// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Stage1_test {
    public static long square(long x) {
        return (x * x);
    }

    public static String greet(String name) {
        return ("Hello, " + (name + "!"));
    }

    public static void main(String[] args) {
        System.out.println(greet("Codex"));
        System.out.println(String.valueOf(square(7L)));
    }
}
