// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class String_ops {
    public static boolean is_identifier_char(String ch) {
        return ((!ch.isEmpty() && Character.isLetter(ch.charAt(0))) ? true : ((!ch.isEmpty() && Character.isDigit(ch.charAt(0))) ? true : (ch.equals("-") ? true : false)));
    }

    public static long count_letters(String s, long i, long acc) {
        while (true) {
            if ((i >= (long)s.length())) {
                return acc;
            } else {
                var ch = String.valueOf(s.charAt((int)(long)i));
                if ((!ch.isEmpty() && Character.isLetter(ch.charAt(0)))) {
                    var _tco_0 = s;
                    var _tco_1 = (i + 1L);
                    var _tco_2 = (acc + 1L);
                    s = _tco_0;
                    i = _tco_1;
                    acc = _tco_2;
                    continue;
                } else {
                    var _tco_0 = s;
                    var _tco_1 = (i + 1L);
                    var _tco_2 = acc;
                    s = _tco_0;
                    i = _tco_1;
                    acc = _tco_2;
                    continue;
                }
            }
        }
    }

    public static void main(String[] args) {
        System.out.println(count_letters("hello world 123", 0L, 0L));
    }
}
