// Generated by Codex compiler — Java backend
import java.util.*;
import java.util.function.*;
import java.io.*;

public class Type_checker_test {
    public static long add_one(long x) {
        return (x + 1L);
    }

    public static long _double(long x) {
        return (x * 2L);
    }

    public static String greet(String name) {
        return ("Hello, " + (name + "!"));
    }

    public static boolean is_positive(long x) {
        return (x > 0L);
    }

    public static long apply_twice(Function<Long, Long> f, long x) {
        return f.apply(f.apply(x));
    }

    public static void main(String[] args) {
        System.out.println(apply_twice(add_one, 40L));
    }
}
