using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Fortran;

public sealed class FortranEmitter : ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;
    Map<string, string> m_ctorToTag = Map<string, string>.s_empty;
    int m_tagCounter;

    public string TargetName => "Fortran";
    public string FileExtension => ".f90";

    public string Emit(IRModule module)
    {
        m_constructorNames = CollectConstructorNames(module);
        m_ctorToTag = BuildCtorTagMap(module);
        m_definitionArity = ValueMap<string, int>.s_empty;
        m_tagCounter = 0;
        foreach (IRDefinition d in module.Definitions)
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);

        string modName = SanitizeUpper(module.Name.Parts.Count > 0
            ? module.Name.Parts[module.Name.Parts.Count - 1].Value : "main");

        StringBuilder sb = new();
        sb.AppendLine("! Generated by Codex compiler — Fortran backend");
        sb.AppendLine("! Compile: gfortran -o output output.f90");
        sb.AppendLine();

        if (module.TypeDefinitions.Count > 0 || module.Definitions.Length > 1
            || (module.Definitions.Length == 1 && module.Definitions[0].Name != "main"))
        {
            sb.AppendLine($"module codex_{modName}");
            sb.AppendLine("  implicit none");
            sb.AppendLine();

            EmitTypeDefinitions(sb, module);

            sb.AppendLine("contains");
            sb.AppendLine();

            IRDefinition? mainDef2 = module.Definitions
                .FirstOrDefault(d => d.Name == "main" && d.Parameters.Length == 0);

            foreach (IRDefinition def in module.Definitions)
            {
                if (def == mainDef2) continue;
                EmitDefinition(sb, def);
                sb.AppendLine();
            }

            sb.AppendLine($"end module codex_{modName}");
            sb.AppendLine();
        }

        IRDefinition? mainDef = module.Definitions
            .FirstOrDefault(d => d.Name == "main" && d.Parameters.Length == 0);

        sb.AppendLine("program main_program");
        if (module.TypeDefinitions.Count > 0 || module.Definitions.Length > 1
            || (module.Definitions.Length == 1 && module.Definitions[0].Name != "main"))
            sb.AppendLine($"  use codex_{modName}");
        sb.AppendLine("  implicit none");

        if (mainDef is not null)
        {
            if (IsEffectfulDefinition(mainDef))
            {
                EmitStatement(sb, mainDef.Body, 1);
            }
            else if (mainDef.Body is IRMatch match)
            {
                EmitMatchStatement(sb, match, "print *", 1);
            }
            else
            {
                sb.Append("  print *, ");
                EmitExpr(sb, mainDef.Body, 1);
                sb.AppendLine();
            }
        }
        else if (module.Definitions.Length == 0)
        {
            sb.AppendLine("  print *, 'All proofs verified at compile time.'");
        }

        sb.AppendLine("end program main_program");
        return sb.ToString();
    }

    void EmitTypeDefinitions(StringBuilder sb, IRModule module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    EmitSumType(sb, sum);
                    break;
                case RecordType rec:
                    EmitRecordType(sb, rec);
                    break;
            }
        }
    }

    void EmitSumType(StringBuilder sb, SumType sum)
    {
        string baseName = SanitizeUpper(sum.TypeName.Value);

        sb.AppendLine($"  ! Sum type: {sum.TypeName.Value}");
        int maxFields = 0;
        foreach (SumConstructorType ctor in sum.Constructors)
            if (ctor.Fields.Length > maxFields) maxFields = ctor.Fields.Length;

        sb.AppendLine("  ! Tag constants:");
        foreach (SumConstructorType ctor in sum.Constructors)
        {
            string tag = m_ctorToTag[ctor.Name.Value] ?? $"{m_tagCounter}";
            sb.AppendLine($"  integer, parameter :: TAG_{SanitizeUpper(ctor.Name.Value)} = {tag}");
        }
        sb.AppendLine();

        sb.AppendLine($"  type :: {baseName}");
        sb.AppendLine("    integer :: tag");
        for (int f = 0; f < maxFields; f++)
            sb.AppendLine($"    integer(8) :: field{f}");
        sb.AppendLine($"  end type {baseName}");
        sb.AppendLine();
    }

    static void EmitRecordType(StringBuilder sb, RecordType rec)
    {
        string name = SanitizeUpper(rec.TypeName.Value);
        sb.AppendLine($"  type :: {name}");
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            RecordFieldType field = rec.Fields[i];
            sb.AppendLine($"    {EmitType(field.Type)} :: {SanitizeUpper(field.FieldName.Value)}");
        }
        sb.AppendLine($"  end type {name}");
        sb.AppendLine();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        string name = SanitizeUpper(def.Name);
        bool isProc = IsEffectfulDefinition(def);

        if (HasSelfTailCall(def))
        {
            EmitTailCallDefinition(sb, def);
            return;
        }

        if (isProc)
        {
            sb.Append($"  subroutine {name}(");
            for (int i = 0; i < def.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(SanitizeUpper(def.Parameters[i].Name));
            }
            sb.AppendLine(")");
            for (int i = 0; i < def.Parameters.Length; i++)
                sb.AppendLine(
                    $"    {EmitType(def.Parameters[i].Type)}, intent(in) :: {SanitizeUpper(def.Parameters[i].Name)}");
            sb.AppendLine("    implicit none");
            EmitStatement(sb, def.Body, 2);
            sb.AppendLine($"  end subroutine {name}");
        }
        else
        {
            string retType = EmitReturnType(def);
            sb.Append($"  {retType} function {name}(");
            for (int i = 0; i < def.Parameters.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(SanitizeUpper(def.Parameters[i].Name));
            }
            sb.AppendLine(")");
            for (int i = 0; i < def.Parameters.Length; i++)
                sb.AppendLine(
                    $"    {EmitType(def.Parameters[i].Type)}, intent(in) :: {SanitizeUpper(def.Parameters[i].Name)}");
            if (def.Body is IRMatch bodyMatch)
            {
                EmitMatchStatement(sb, bodyMatch, $"{name} =", 2);
            }
            else
            {
                sb.Append($"    {name} = ");
                EmitExpr(sb, def.Body, 2);
                sb.AppendLine();
            }
            sb.AppendLine($"  end function {name}");
        }
    }

    void EmitTailCallDefinition(StringBuilder sb, IRDefinition def)
    {
        string name = SanitizeUpper(def.Name);
        string retType = EmitReturnType(def);

        sb.Append($"  {retType} function {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{SanitizeUpper(def.Parameters[i].Name)}_in");
        }
        sb.AppendLine(")");
        for (int i = 0; i < def.Parameters.Length; i++)
            sb.AppendLine(
                $"    {EmitType(def.Parameters[i].Type)}, intent(in) :: {SanitizeUpper(def.Parameters[i].Name)}_in");
        for (int i = 0; i < def.Parameters.Length; i++)
            sb.AppendLine(
                $"    {EmitType(def.Parameters[i].Type)} :: {SanitizeUpper(def.Parameters[i].Name)}");
        for (int i = 0; i < def.Parameters.Length; i++)
            sb.AppendLine(
                $"    {SanitizeUpper(def.Parameters[i].Name)} = {SanitizeUpper(def.Parameters[i].Name)}_in");
        sb.AppendLine("    do while (.true.)");
        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, 3);
        sb.AppendLine("    end do");
        sb.AppendLine($"  end function {name}");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 2);

        switch (expr)
        {
            case IRIf iff:
                sb.Append($"{pad}if (");
                EmitExpr(sb, iff.Condition, indent);
                sb.AppendLine(") then");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}else");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}end if");
                break;

            case IRLet let:
                EmitExpr(sb, let.Body, indent);
                break;

            case IRApply app when IsSelfCall(app, funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    sb.Append($"{pad}{SanitizeUpper(parameters[i].Name)} = ");
                    EmitExpr(sb, args[i], indent);
                    sb.AppendLine();
                }
                sb.AppendLine($"{pad}cycle");
                break;
            }

            default:
                sb.Append($"{pad}{SanitizeUpper(funcName)} = ");
                EmitExpr(sb, expr, indent);
                sb.AppendLine();
                sb.AppendLine($"{pad}return");
                break;
        }
    }

    void EmitExpr(StringBuilder sb, IRExpr expr, int indent)
    {
        switch (expr)
        {
            case IRIntegerLit lit:
                sb.Append($"{lit.Value}_8");
                break;

            case IRNumberLit lit:
                string numStr = lit.Value.ToString();
                if (!numStr.Contains('.')) numStr += ".0";
                sb.Append($"{numStr}d0");
                break;

            case IRTextLit lit:
                sb.Append($"'{EscapeString(lit.Value)}'");
                break;

            case IRBoolLit lit:
                sb.Append(lit.Value ? ".true." : ".false.");
                break;

            case IRName name:
                if (name.Name == "True") sb.Append(".true.");
                else if (name.Name == "False") sb.Append(".false.");
                else if (name.Name == "Nothing") sb.Append('0');
                else if (m_definitionArity.TryGet(name.Name, out int nameArity)
                    && nameArity == 0
                    && name.Type is not FunctionType)
                    sb.Append($"{SanitizeUpper(name.Name)}()");
                else
                    sb.Append(SanitizeUpper(name.Name));
                break;

            case IRBinary bin:
                EmitBinary(sb, bin, indent);
                break;

            case IRNegate neg:
                sb.Append("(-");
                EmitExpr(sb, neg.Operand, indent);
                sb.Append(')');
                break;

            case IRIf iff:
                sb.Append("merge(");
                EmitExpr(sb, iff.Then, indent);
                sb.Append(", ");
                EmitExpr(sb, iff.Else, indent);
                sb.Append(", ");
                EmitExpr(sb, iff.Condition, indent);
                sb.Append(')');
                break;

            case IRLet let:
                EmitExpr(sb, let.Body, indent);
                break;

            case IRApply app:
                EmitApply(sb, app, indent);
                break;

            case IRRecord rec:
                sb.Append($"{SanitizeUpper(rec.TypeName)}(");
                for (int i = 0; i < rec.Fields.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, rec.Fields[i].Value, indent);
                }
                sb.Append(')');
                break;

            case IRFieldAccess fa:
                EmitExpr(sb, fa.Record, indent);
                sb.Append($"%{SanitizeUpper(fa.FieldName)}");
                break;

            case IRMatch match:
                EmitFortranMatch(sb, match, indent);
                break;

            case IRList list:
                sb.Append('0');
                break;

            case IRError err:
                sb.Append('0');
                break;

            default:
                sb.Append('0');
                break;
        }
    }

    void EmitFortranMatch(StringBuilder sb, IRMatch match, int indent)
    {
        // Fortran has no expression-level match. Emit nested merge() calls:
        // merge(body1, merge(body2, 0, scrutinee%tag == TAG_Ctor2), scrutinee%tag == TAG_Ctor1)
        ImmutableArray<IRMatchBranch> branches = match.Branches;
        if (branches.Length == 0)
        {
            sb.Append("0");
            return;
        }

        for (int i = 0; i < branches.Length - 1; i++)
            sb.Append("merge(");

        for (int i = 0; i < branches.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            EmitExpr(sb, branches[i].Body, indent);
            if (i < branches.Length - 1)
            {
                sb.Append(", ");
            }
        }

        for (int i = branches.Length - 2; i >= 0; i--)
        {
            sb.Append(", ");
            if (branches[i].Pattern is IRCtorPattern ctorPat
                && m_ctorToTag.TryGet(ctorPat.Name, out _))
            {
                EmitExpr(sb, match.Scrutinee, indent);
                sb.Append($"%tag == TAG_{SanitizeUpper(ctorPat.Name)}");
            }
            else
            {
                sb.Append(".true.");
            }
            sb.Append(')');
        }
    }

    void EmitApply(StringBuilder sb, IRApply app, int indent)
    {
        if (app.Function is IRName fn && fn.Name == "show")
        {
            sb.Append("'<value>'");
        }
        else if (app.Function is IRName fn3 && fn3.Name == "print-line")
        {
            sb.Append("print *, ");
            EmitExpr(sb, app.Argument, indent);
        }
        else if (app.Function is IRName fn7 && fn7.Name == "text-length")
        {
            sb.Append("int(len_trim(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("), 8)");
        }
        else if (app.Function is IRName fn11b && fn11b.Name == "integer-to-text")
        {
            sb.Append("'<integer>'");
        }
        else
        {
            EmitApplyGeneral(sb, app, indent);
        }
    }

    void EmitApplyGeneral(StringBuilder sb, IRApply app, int indent)
    {
        string? defName = FindDefinitionName(app);
        if (defName is not null
            && m_definitionArity.TryGet(defName, out int arity)
            && arity >= 1)
        {
            List<IRExpr> args = [];
            CollectApplyArgs(app, args);
            if (args.Count == arity)
            {
                sb.Append($"{SanitizeUpper(defName)}(");
                for (int i = 0; i < args.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, args[i], indent);
                }
                sb.Append(')');
            }
            else
            {
                sb.Append($"{SanitizeUpper(defName)}(");
                EmitExpr(sb, app.Argument, indent);
                sb.Append(')');
            }
        }
        else
        {
            EmitExpr(sb, app.Function, indent);
            sb.Append('(');
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
    }

    void EmitBinary(StringBuilder sb, IRBinary bin, int indent)
    {
        switch (bin.Op)
        {
            case IRBinaryOp.AppendText:
                sb.Append("trim(");
                EmitExpr(sb, bin.Left, indent);
                sb.Append(") // trim(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.PowInt:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" ** ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            default:
                string op = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
                    IRBinaryOp.DivInt or IRBinaryOp.DivNum => "/",
                    IRBinaryOp.Eq => "==",
                    IRBinaryOp.NotEq => "/=",
                    IRBinaryOp.Lt => "<",
                    IRBinaryOp.Gt => ">",
                    IRBinaryOp.LtEq => "<=",
                    IRBinaryOp.GtEq => ">=",
                    IRBinaryOp.And => ".and.",
                    IRBinaryOp.Or => ".or.",
                    _ => "+"
                };
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append($" {op} ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;
        }
    }

    void EmitStatement(StringBuilder sb, IRExpr expr, int indent)
    {
        string pad = new(' ', indent * 2);
        if (expr is IRDo doExpr)
        {
            foreach (IRDoStatement stmt in doExpr.Statements)
            {
                switch (stmt)
                {
                    case IRDoExec exec:
                        sb.Append(pad);
                        EmitExpr(sb, exec.Expression, indent);
                        sb.AppendLine();
                        break;
                    case IRDoBind bind:
                        sb.AppendLine($"{pad}! bind: {bind.Name}");
                        break;
                }
            }
        }
        else
        {
            sb.Append(pad);
            EmitExpr(sb, expr, indent);
            sb.AppendLine();
        }
    }

    void EmitMatchStatement(StringBuilder sb, IRMatch match, string assignTarget, int indent)
    {
        string pad = new(' ', indent * 2);

        sb.Append($"{pad}select case (");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.AppendLine($"%tag)");

        foreach (IRMatchBranch branch in match.Branches)
        {
            if (branch.Pattern is IRCtorPattern ctorPat
                && m_ctorToTag.TryGet(ctorPat.Name, out _))
            {
                sb.AppendLine($"{pad}  case (TAG_{SanitizeUpper(ctorPat.Name)})");
                sb.Append($"{pad}    {assignTarget} ");
                EmitMatchBranchBody(sb, branch.Body, match.Scrutinee, ctorPat, indent + 2);
                sb.AppendLine();
            }
            else if (branch.Pattern is IRWildcardPattern or IRVarPattern)
            {
                sb.AppendLine($"{pad}  case default");
                sb.Append($"{pad}    {assignTarget} ");
                EmitExpr(sb, branch.Body, indent + 2);
                sb.AppendLine();
            }
        }
        sb.AppendLine($"{pad}end select");
    }

    void EmitMatchBranchBody(StringBuilder sb, IRExpr body, IRExpr scrutinee, IRCtorPattern pattern, int indent)
    {
        IRExpr rewritten = RewritePatternVars(body, scrutinee, pattern);
        EmitExpr(sb, rewritten, indent);
    }

    static IRExpr RewritePatternVars(IRExpr expr, IRExpr scrutinee, IRCtorPattern pattern)
    {
        Dictionary<string, int> varFields = [];
        for (int i = 0; i < pattern.SubPatterns.Length; i++)
        {
            if (pattern.SubPatterns[i] is IRVarPattern vp)
                varFields[vp.Name] = i;
        }
        return RewriteExpr(expr, scrutinee, varFields);
    }

    static IRExpr RewriteExpr(IRExpr expr, IRExpr scrutinee, Dictionary<string, int> varFields)
    {
        switch (expr)
        {
            case IRName name when varFields.TryGetValue(name.Name, out int fieldIdx):
                return new IRFieldAccess(scrutinee, $"field{fieldIdx}", name.Type);

            case IRBinary bin:
                return new IRBinary(
                    bin.Op,
                    RewriteExpr(bin.Left, scrutinee, varFields),
                    RewriteExpr(bin.Right, scrutinee, varFields),
                    bin.Type);

            case IRNegate neg:
                return new IRNegate(
                    RewriteExpr(neg.Operand, scrutinee, varFields));

            case IRIf iff:
                return new IRIf(
                    RewriteExpr(iff.Condition, scrutinee, varFields),
                    RewriteExpr(iff.Then, scrutinee, varFields),
                    RewriteExpr(iff.Else, scrutinee, varFields),
                    iff.Type);

            case IRApply app:
                return new IRApply(
                    RewriteExpr(app.Function, scrutinee, varFields),
                    RewriteExpr(app.Argument, scrutinee, varFields),
                    app.Type);

            default:
                return expr;
        }
    }

    static string EmitType(CodexType type) => type switch
    {
        IntegerType => "integer(8)",
        NumberType => "real(8)",
        TextType => "character(len=256)",
        BooleanType => "logical",
        ForAllType fa => EmitType(fa.Body),
        RecordType rt => $"type({SanitizeUpper(rt.TypeName.Value)})",
        SumType st => $"type({SanitizeUpper(st.TypeName.Value)})",
        _ => "integer(8)"
    };

    string EmitReturnType(IRDefinition def)
    {
        CodexType type = GetReturnType(def);
        return EmitType(type);
    }

    static CodexType GetReturnType(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType) type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType) type = pft2.Return;
        if (type is EffectfulType eft) type = eft.Return;
        return type;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]) ? name.Name : null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner) CollectApplyArgs(inner, args);
        args.Add(app.Argument);
    }

    static Set<string> CollectConstructorNames(IRModule module)
    {
        Set<string> names = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
            if (kv.Value is SumType sum)
                foreach (SumConstructorType ctor in sum.Constructors)
                    names = names.Add(ctor.Name.Value);
        return names;
    }

    Map<string, string> BuildCtorTagMap(IRModule module)
    {
        Map<string, string> map = Map<string, string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
            if (kv.Value is SumType sum)
                foreach (SumConstructorType ctor in sum.Constructors)
                {
                    map = map.Set(ctor.Name.Value, (++m_tagCounter).ToString());
                }
        return map;
    }

    static bool HasSelfTailCall(IRDefinition def) =>
        def.Parameters.Length > 0 && ExprHasTailCall(def.Body, def.Name);

    static bool ExprHasTailCall(IRExpr expr, string funcName) => expr switch
    {
        IRIf iff => ExprHasTailCall(iff.Then, funcName) || ExprHasTailCall(iff.Else, funcName),
        IRLet let => ExprHasTailCall(let.Body, funcName),
        IRMatch match => match.Branches.Any(b => ExprHasTailCall(b.Body, funcName)),
        IRApply app => IsSelfCall(app, funcName),
        _ => false
    };

    static bool IsSelfCall(IRApply app, string funcName)
    {
        IRExpr root = app.Function;
        while (root is IRApply inner) root = inner.Function;
        return root is IRName name && name.Name == funcName;
    }

    static bool IsEffectfulDefinition(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType) type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType) type = pft2.Return;
        return type is EffectfulType;
    }

    static string SanitizeUpper(string name)
    {
        string sanitized = name.Replace('-', '_');
        return sanitized switch
        {
            "program" or "end" or "function" or "subroutine" or "module" or "use"
            or "implicit" or "integer" or "real" or "character" or "logical" or "complex"
            or "type" or "class" or "if" or "then" or "else" or "do" or "while" or "cycle"
            or "exit" or "return" or "call" or "print" or "write" or "read" or "open"
            or "close" or "stop" or "data" or "parameter" or "intent" or "allocatable"
            or "pointer" or "target" or "select" or "case" or "where" or "forall"
            or "block" or "associate" or "contains" or "result" or "recursive"
            or "pure" or "elemental" or "abstract" or "interface" or "operator"
            or "assignment" or "sequence" or "private" or "public" or "protected"
            or "double" or "precision" or "kind" or "len" or "trim" or "merge"
                => $"{sanitized}_v",
            _ => sanitized
        };
    }

    static string EscapeString(string value) => value.Replace("'", "''");
}
