using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Java;

public sealed class JavaEmitter : ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;

    public string TargetName => "Java";
    public string FileExtension => ".java";

    public string Emit(IRChapter module)
    {
        m_constructorNames = CollectConstructorNames(module);
        m_definitionArity = ValueMap<string, int>.s_empty;
        foreach (IRDefinition d in module.Definitions)
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);

        string className = Capitalize(Sanitize(module.Name.Parts.Count > 0
            ? module.Name.Parts[module.Name.Parts.Count - 1].Value : "Program"));

        Set<string> typeNames = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
            typeNames = typeNames.Add(Sanitize(kv.Key));
        if (typeNames.Contains(className))
            className += "Chapter";

        StringBuilder sb = new();
        sb.AppendLine("// Generated by Codex compiler — Java backend");
        sb.AppendLine("import java.util.*;");
        sb.AppendLine("import java.util.function.*;");
        sb.AppendLine("import java.io.*;");
        sb.AppendLine();

        EmitTypeDefinitions(sb, module);

        sb.AppendLine($"public class {className} {{");

        IRDefinition? mainDef = module.Definitions
            .FirstOrDefault(d => d.Name == "main" && d.Parameters.Length == 0);

        foreach (IRDefinition def in module.Definitions)
        {
            if (def == mainDef) continue;
            EmitDefinition(sb, def);
            sb.AppendLine();
        }

        if (mainDef is not null)
        {
            sb.AppendLine("    public static void main(String[] args) {");
            if (IsEffectfulDefinition(mainDef))
            {
                EmitStatement(sb, mainDef.Body, 2);
            }
            else
            {
                sb.Append("        System.out.println(");
                EmitExpr(sb, mainDef.Body, 2);
                sb.AppendLine(");");
            }
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("    public static void main(String[] args) {");
            if (module.Definitions.Length == 0)
                sb.AppendLine("        System.out.println(\"All proofs verified at compile time.\");");
            else
                sb.AppendLine("        System.out.println(\"Chapter loaded.\");");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitTypeDefinitions(StringBuilder sb, IRChapter module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    EmitSumType(sb, sum);
                    break;
                case RecordType rec:
                    EmitRecordType(sb, rec);
                    break;
            }
        }
    }

    static void EmitSumType(StringBuilder sb, SumType sum)
    {
        string baseName = Sanitize(sum.TypeName.Value);
        sb.AppendLine($"sealed interface {baseName} {{}}");
        foreach (SumConstructorType ctor in sum.Constructors)
        {
            string name = Sanitize(ctor.Name.Value);
            if (ctor.Fields.IsEmpty)
            {
                sb.AppendLine($"record {name}() implements {baseName} {{}}");
            }
            else
            {
                sb.Append($"record {name}(");
                for (int i = 0; i < ctor.Fields.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append($"{EmitType(ctor.Fields[i])} field{i}");
                }
                sb.AppendLine($") implements {baseName} {{}}");
            }
        }
        sb.AppendLine();
    }

    static void EmitRecordType(StringBuilder sb, RecordType rec)
    {
        string name = Sanitize(rec.TypeName.Value);
        sb.Append($"record {name}(");
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            RecordFieldType field = rec.Fields[i];
            sb.Append($"{EmitType(field.Type)} {Sanitize(field.FieldName.Value)}");
        }
        sb.AppendLine(") {}");
        sb.AppendLine();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        if (HasSelfTailCall(def))
        {
            EmitTailCallDefinition(sb, def);
            return;
        }

        string returnType = IsEffectfulDefinition(def) ? "void" : EmitReturnType(def);
        string name = Sanitize(def.Name);

        sb.Append($"    public static {returnType} {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{EmitType(def.Parameters[i].Type)} {Sanitize(def.Parameters[i].Name)}");
        }
        sb.AppendLine(") {");

        if (IsEffectfulDefinition(def))
        {
            EmitStatement(sb, def.Body, 2);
        }
        else
        {
            sb.Append("        return ");
            EmitExpr(sb, def.Body, 2);
            sb.AppendLine(";");
        }
        sb.AppendLine("    }");
    }

    void EmitTailCallDefinition(StringBuilder sb, IRDefinition def)
    {
        string returnType = EmitReturnType(def);
        string name = Sanitize(def.Name);

        sb.Append($"    public static {returnType} {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{EmitType(def.Parameters[i].Type)} {Sanitize(def.Parameters[i].Name)}");
        }
        sb.AppendLine(") {");
        sb.AppendLine("        while (true) {");

        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, 3);

        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 4);

        switch (expr)
        {
            case IRIf iff:
                sb.Append($"{pad}if (");
                EmitExpr(sb, iff.Condition, indent);
                sb.AppendLine(") {");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}} else {{");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}}");
                break;

            case IRLet let:
                sb.Append($"{pad}var {Sanitize(let.Name)} = ");
                EmitExpr(sb, let.Value, indent);
                sb.AppendLine(";");
                EmitTailCallBody(sb, let.Body, funcName, parameters, indent);
                break;

            case IRMatch match:
                EmitTailCallMatch(sb, match, funcName, parameters, indent);
                break;

            case IRApply app when IsSelfCall(app, funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    sb.Append($"{pad}var _tco_{i} = ");
                    EmitExpr(sb, args[i], indent);
                    sb.AppendLine(";");
                }
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                    sb.AppendLine($"{pad}{Sanitize(parameters[i].Name)} = _tco_{i};");
                sb.AppendLine($"{pad}continue;");
                break;
            }

            default:
                sb.Append($"{pad}return ");
                EmitExpr(sb, expr, indent);
                sb.AppendLine(";");
                break;
        }
    }

    void EmitTailCallMatch(
        StringBuilder sb, IRMatch match, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 4);
        sb.Append($"{pad}var _tco_s = ");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.AppendLine(";");

        bool first = true;
        int branchIdx = 0;
        foreach (IRMatchBranch branch in match.Branches)
        {
            string keyword = first ? "if" : "else if";
            first = false;
            string mVar = $"_tco_m{branchIdx}";
            branchIdx++;

            switch (branch.Pattern)
            {
                case IRCtorPattern ctorPat:
                    sb.AppendLine(
                        $"{pad}{keyword} (_tco_s instanceof {Sanitize(ctorPat.Name)} {mVar}) {{");
                    for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
                    {
                        if (ctorPat.SubPatterns[i] is IRVarPattern svp)
                            sb.AppendLine($"{pad}    var {Sanitize(svp.Name)} = {mVar}.field{i}();");
                    }
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    break;

                case IRVarPattern varPat:
                    sb.AppendLine($"{pad}else {{");
                    sb.AppendLine($"{pad}    var {Sanitize(varPat.Name)} = _tco_s;");
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    return;

                case IRWildcardPattern:
                    sb.AppendLine($"{pad}else {{");
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    sb.AppendLine($"{pad}}}");
                    return;
            }
        }
    }

    void EmitExpr(StringBuilder sb, IRExpr expr, int indent)
    {
        switch (expr)
        {
            case IRIntegerLit lit:
                sb.Append($"{lit.Value}L");
                break;

            case IRNumberLit lit:
                sb.Append($"{lit.Value}d");
                break;

            case IRTextLit lit:
                sb.Append($"\"{EscapeString(lit.Value)}\"");
                break;

            case IRBoolLit lit:
                sb.Append(lit.Value ? "true" : "false");
                break;

            case IRName name:
                if (name.Name == "read-line")
                    sb.Append("new java.util.Scanner(System.in).nextLine()");
                else if (name.Name == "show")
                    sb.Append("String::valueOf");
                else if (name.Name == "negate")
                    sb.Append("(Function<Long, Long>) x -> -x");
                else if (name.Name == "True")
                    sb.Append("true");
                else if (name.Name == "False")
                    sb.Append("false");
                else if (name.Name == "Nothing")
                    sb.Append("null");
                else if (m_constructorNames.Contains(name.Name)
                    && name.Type is not FunctionType)
                    sb.Append($"new {Sanitize(name.Name)}()");
                else if (m_definitionArity.TryGet(name.Name, out int nameArity)
                    && nameArity == 0
                    && name.Type is not FunctionType)
                    sb.Append($"{Sanitize(name.Name)}()");
                else
                    sb.Append(Sanitize(name.Name));
                break;

            case IRBinary bin:
                EmitBinary(sb, bin, indent);
                break;

            case IRNegate neg:
                sb.Append("(-");
                EmitExpr(sb, neg.Operand, indent);
                sb.Append(')');
                break;

            case IRIf iff:
                sb.Append('(');
                EmitExpr(sb, iff.Condition, indent);
                sb.Append(" ? ");
                EmitExpr(sb, iff.Then, indent);
                sb.Append(" : ");
                EmitExpr(sb, iff.Else, indent);
                sb.Append(')');
                break;

            case IRLet let:
                sb.Append("((Function<");
                sb.Append(EmitBoxedType(let.NameType));
                sb.Append(", ");
                sb.Append(EmitBoxedType(let.Type));
                sb.Append(">)(");
                sb.Append(Sanitize(let.Name));
                sb.Append(" -> ");
                EmitExpr(sb, let.Body, indent);
                sb.Append(")).apply(");
                EmitExpr(sb, let.Value, indent);
                sb.Append(')');
                break;

            case IRApply app:
                EmitApply(sb, app, indent);
                break;

            case IRLambda lam:
                if (lam.Parameters.Length == 1)
                {
                    sb.Append('(');
                    sb.Append(Sanitize(lam.Parameters[0].Name));
                    sb.Append(") -> ");
                    EmitExpr(sb, lam.Body, indent);
                }
                else
                {
                    sb.Append('(');
                    for (int i = 0; i < lam.Parameters.Length; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        sb.Append(Sanitize(lam.Parameters[i].Name));
                    }
                    sb.Append(") -> ");
                    EmitExpr(sb, lam.Body, indent);
                }
                break;

            case IRList list:
                if (list.Elements.Length == 0)
                {
                    sb.Append("new ArrayList<>()");
                }
                else
                {
                    sb.Append("new ArrayList<>(List.of(");
                    for (int i = 0; i < list.Elements.Length; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        EmitExpr(sb, list.Elements[i], indent);
                    }
                    sb.Append("))");
                }
                break;

            case IRMatch match:
                EmitMatch(sb, match, indent);
                break;

            case IRDo doExpr:
                EmitDoExpr(sb, doExpr, indent);
                break;

            case IRRecord rec:
                sb.Append($"new {Sanitize(rec.TypeName)}(");
                for (int i = 0; i < rec.Fields.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, rec.Fields[i].Value, indent);
                }
                sb.Append(')');
                break;

            case IRFieldAccess fa:
                EmitExpr(sb, fa.Record, indent);
                sb.Append('.');
                sb.Append(Sanitize(fa.FieldName));
                sb.Append("()");
                break;

            case IRError err:
                sb.Append($"(() -> {{ throw new RuntimeException(\"{EscapeString(err.Message)}\"); }})");
                break;

            default:
                sb.Append("null");
                break;
        }
    }

    void EmitApply(StringBuilder sb, IRApply app, int indent)
    {
        if (app.Function is IRName fn && fn.Name == "show")
        {
            sb.Append("String.valueOf("); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn2 && fn2.Name == "negate")
        {
            sb.Append("(-"); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn3 && fn3.Name == "print-line")
        {
            sb.Append("System.out.println("); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn7 && fn7.Name == "text-length")
        {
            sb.Append("(long)"); EmitExpr(sb, app.Argument, indent); sb.Append(".length()");
        }
        else if (app.Function is IRName fn7b && fn7b.Name == "char-to-text")
        {
            sb.Append("String.valueOf((char)(long)"); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn8 && fn8.Name == "is-letter")
        {
            sb.Append("Character.isLetter((char)(long)"); EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn9 && fn9.Name == "is-digit")
        {
            sb.Append("Character.isDigit((char)(long)"); EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn10 && fn10.Name == "is-whitespace")
        {
            sb.Append("Character.isWhitespace((char)(long)"); EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn11 && fn11.Name == "text-to-integer")
        {
            sb.Append("Long.parseLong("); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn11b && fn11b.Name == "integer-to-text")
        {
            sb.Append("Long.toString("); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn12 && fn12.Name == "char-code")
        {
            EmitExpr(sb, app.Argument, indent);
        }
        else if (app.Function is IRName fn13 && fn13.Name == "code-to-char")
        {
            EmitExpr(sb, app.Argument, indent);
        }
        else if (app.Function is IRName fn14 && fn14.Name == "list-length")
        {
            sb.Append("(long)"); EmitExpr(sb, app.Argument, indent); sb.Append(".size()");
        }
        else if (TryEmitMultiArgBuiltin(sb, app, indent))
        {
        }
        else
        {
            EmitApplyGeneral(sb, app, indent);
        }
    }

    void EmitApplyGeneral(StringBuilder sb, IRApply app, int indent)
    {
        string? ctorName = FindConstructorName(app);
        if (ctorName is not null)
        {
            List<IRExpr> args = [];
            CollectApplyArgs(app, args);
            sb.Append($"new {Sanitize(ctorName)}(");
            for (int i = 0; i < args.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                EmitExpr(sb, args[i], indent);
            }
            sb.Append(')');
        }
        else
        {
            string? defName = FindDefinitionName(app);
            if (defName is not null
                && m_definitionArity.TryGet(defName, out int arity)
                && arity >= 1)
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                if (args.Count == arity)
                {
                    sb.Append(Sanitize(defName));
                    sb.Append('(');
                    for (int i = 0; i < args.Count; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        EmitExpr(sb, args[i], indent);
                    }
                    sb.Append(')');
                }
                else
                {
                    EmitExpr(sb, app.Function, indent);
                    sb.Append(".apply(");
                    EmitExpr(sb, app.Argument, indent);
                    sb.Append(')');
                }
            }
            else
            {
                EmitExpr(sb, app.Function, indent);
                sb.Append(".apply(");
                EmitExpr(sb, app.Argument, indent);
                sb.Append(')');
            }
        }
    }

    void EmitBinary(StringBuilder sb, IRBinary bin, int indent)
    {
        switch (bin.Op)
        {
            case IRBinaryOp.AppendText:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" + ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.AppendList:
                sb.Append("new ArrayList<>() {{ addAll(");
                EmitExpr(sb, bin.Left, indent);
                sb.Append("); addAll(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append("); }}");
                break;

            case IRBinaryOp.ConsList:
                sb.Append("new ArrayList<>() {{ add(");
                EmitExpr(sb, bin.Left, indent);
                sb.Append("); addAll(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append("); }}");
                break;

            case IRBinaryOp.PowInt:
                sb.Append("(long)Math.pow((double)");
                EmitExpr(sb, bin.Left, indent);
                sb.Append(", (double)");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.Eq when IsTextType(bin.Left.Type):
                EmitExpr(sb, bin.Left, indent);
                sb.Append(".equals(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.NotEq when IsTextType(bin.Left.Type):
                sb.Append('!');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(".equals(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            default:
                string op = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
                    IRBinaryOp.DivInt or IRBinaryOp.DivNum => "/",
                    IRBinaryOp.Eq => "==",
                    IRBinaryOp.NotEq => "!=",
                    IRBinaryOp.Lt => "<",
                    IRBinaryOp.Gt => ">",
                    IRBinaryOp.LtEq => "<=",
                    IRBinaryOp.GtEq => ">=",
                    IRBinaryOp.And => "&&",
                    IRBinaryOp.Or => "||",
                    _ => "+"
                };
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append($" {op} ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;
        }
    }

    void EmitMatch(StringBuilder sb, IRMatch match, int indent)
    {
        sb.Append("switch (");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.Append(") { ");

        foreach (IRMatchBranch branch in match.Branches)
        {
            switch (branch.Pattern)
            {
                case IRCtorPattern ctorPat:
                    sb.Append($"case {Sanitize(ctorPat.Name)} _m -> ");
                    if (ctorPat.SubPatterns.Any(p => p is IRVarPattern))
                    {
                        sb.Append("{ ");
                        for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
                        {
                            if (ctorPat.SubPatterns[i] is IRVarPattern svp)
                                sb.Append($"var {Sanitize(svp.Name)} = _m.field{i}(); ");
                        }
                        sb.Append("yield ");
                        EmitExpr(sb, branch.Body, indent);
                        sb.Append("; } ");
                    }
                    else
                    {
                        EmitExpr(sb, branch.Body, indent);
                        sb.Append("; ");
                    }
                    break;

                case IRVarPattern varPat:
                    sb.Append($"default -> {{ var {Sanitize(varPat.Name)} = ");
                    EmitExpr(sb, match.Scrutinee, indent);
                    sb.Append("; yield ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; } ");
                    break;

                case IRWildcardPattern:
                    sb.Append("default -> ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; ");
                    break;
            }
        }
        sb.Append('}');
    }

    void EmitDoExpr(StringBuilder sb, IRDo doExpr, int indent)
    {
        sb.AppendLine("((Supplier<Object>)(() -> {");
        string pad = new(' ', (indent + 1) * 4);
        foreach (IRDoStatement stmt in doExpr.Statements)
        {
            switch (stmt)
            {
                case IRDoBind bind:
                    sb.Append($"{pad}var {Sanitize(bind.Name)} = ");
                    EmitExpr(sb, bind.Value, indent + 1);
                    sb.AppendLine(";");
                    break;
                case IRDoExec exec:
                    sb.Append(pad);
                    EmitExpr(sb, exec.Expression, indent + 1);
                    sb.AppendLine(";");
                    break;
            }
        }
        sb.Append(new string(' ', indent * 4));
        sb.Append("return null; })).get()");
    }

    void EmitStatement(StringBuilder sb, IRExpr expr, int indent)
    {
        string pad = new(' ', indent * 4);
        if (expr is IRDo doExpr)
        {
            foreach (IRDoStatement stmt in doExpr.Statements)
            {
                switch (stmt)
                {
                    case IRDoBind bind:
                        sb.Append($"{pad}var {Sanitize(bind.Name)} = ");
                        EmitExpr(sb, bind.Value, indent);
                        sb.AppendLine(";");
                        break;
                    case IRDoExec exec:
                        sb.Append(pad);
                        EmitExpr(sb, exec.Expression, indent);
                        sb.AppendLine(";");
                        break;
                }
            }
        }
        else
        {
            sb.Append(pad);
            EmitExpr(sb, expr, indent);
            sb.AppendLine(";");
        }
    }

    bool TryEmitMultiArgBuiltin(StringBuilder sb, IRApply app, int indent)
    {
        string? name = FindBuiltinRoot(app);
        if (name is null) return false;

        List<IRExpr> args = [];
        CollectApplyArgs(app, args);

        switch (name)
        {
            case "char-at" when args.Count == 2:
                sb.Append("(long)");
                EmitExpr(sb, args[0], indent);
                sb.Append(".charAt((int)(long)");
                EmitExpr(sb, args[1], indent);
                sb.Append(')');
                return true;

            case "substring" when args.Count == 3:
                EmitExpr(sb, args[0], indent);
                sb.Append(".substring((int)(long)");
                EmitExpr(sb, args[1], indent);
                sb.Append(", (int)(long)(");
                EmitExpr(sb, args[1], indent);
                sb.Append(" + ");
                EmitExpr(sb, args[2], indent);
                sb.Append("))");
                return true;

            case "list-at" when args.Count == 2:
                EmitExpr(sb, args[0], indent);
                sb.Append(".get((int)(long)");
                EmitExpr(sb, args[1], indent);
                sb.Append(')');
                return true;

            case "text-replace" when args.Count == 3:
                EmitExpr(sb, args[0], indent);
                sb.Append(".replace(");
                EmitExpr(sb, args[1], indent);
                sb.Append(", ");
                EmitExpr(sb, args[2], indent);
                sb.Append(')');
                return true;

            default:
                return false;
        }
    }

    static string EmitType(CodexType type) => type switch
    {
        IntegerType => "long",
        NumberType => "double",
        TextType => "String",
        BooleanType => "boolean",
        NothingType => "Object",
        VoidType => "void",
        EffectfulType eft => EmitType(eft.Return),
        LinearType lin => EmitType(lin.Inner),
        ListType lt => $"ArrayList<{EmitBoxedType(lt.Element)}>",
        FunctionType ft => $"Function<{EmitBoxedType(ft.Parameter)}, {EmitBoxedType(ft.Return)}>",
        SumType st => Sanitize(st.TypeName.Value),
        RecordType rt => Sanitize(rt.TypeName.Value),
        TypeVariable => "Object",
        _ => "Object"
    };

    static string EmitBoxedType(CodexType type) => type switch
    {
        IntegerType => "Long",
        NumberType => "Double",
        BooleanType => "Boolean",
        _ => EmitType(type)
    };

    string EmitReturnType(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType) type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType) type = pft2.Return;
        if (type is EffectfulType eft) type = eft.Return;
        return EmitType(type);
    }

    static bool IsTextType(CodexType type) => type is TextType;

    static string? FindConstructorName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && name.Name.Length > 0 && char.IsUpper(name.Name[0]) ? name.Name : null;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]) ? name.Name : null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner) CollectApplyArgs(inner, args);
        args.Add(app.Argument);
    }

    static readonly Set<string> s_multiArgBuiltins = Set<string>.Of("char-at", "substring", "list-at", "text-replace");

    static string? FindBuiltinRoot(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && s_multiArgBuiltins.Contains(name.Name) ? name.Name : null;
    }

    static Set<string> CollectConstructorNames(IRChapter module)
    {
        Set<string> names = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
            if (kv.Value is SumType sum)
                foreach (SumConstructorType ctor in sum.Constructors)
                    names = names.Add(ctor.Name.Value);
        return names;
    }

    static bool HasSelfTailCall(IRDefinition def) =>
        def.Parameters.Length > 0 && ExprHasTailCall(def.Body, def.Name);

    static bool ExprHasTailCall(IRExpr expr, string funcName) => expr switch
    {
        IRIf iff => ExprHasTailCall(iff.Then, funcName) || ExprHasTailCall(iff.Else, funcName),
        IRLet let => ExprHasTailCall(let.Body, funcName),
        IRMatch match => match.Branches.Any(b => ExprHasTailCall(b.Body, funcName)),
        IRApply app => IsSelfCall(app, funcName),
        _ => false
    };

    static bool IsSelfCall(IRApply app, string funcName)
    {
        IRExpr root = app.Function;
        while (root is IRApply inner) root = inner.Function;
        return root is IRName name && name.Name == funcName;
    }

    static bool IsEffectfulDefinition(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType) type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType) type = pft2.Return;
        return type is EffectfulType;
    }

    static string Sanitize(string name)
    {
        string sanitized = name.Replace('-', '_');
        return sanitized switch
        {
            "class" or "static" or "void" or "return" or "if" or "else" or "for"
            or "while" or "do" or "switch" or "case" or "break" or "continue"
            or "new" or "this" or "super" or "null" or "true" or "false" or "int"
            or "long" or "double" or "boolean" or "char" or "byte" or "short"
            or "float" or "abstract" or "final" or "native" or "synchronized"
            or "volatile" or "transient" or "throws" or "try" or "catch" or "finally"
            or "import" or "package" or "public" or "private" or "protected"
            or "interface" or "extends" or "implements" or "instanceof" or "enum"
            or "default" or "assert" or "throw" or "var" or "record" or "sealed"
            or "yield" or "permits"
                => $"_{sanitized}",
            _ => sanitized
        };
    }

    static string Capitalize(string s) => s.Length == 0 ? s : char.ToUpper(s[0]) + s[1..];

    static string EscapeString(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\n", "\\n")
        .Replace("\r", "\\r")
        .Replace("\t", "\\t");
}
