using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Go;

public sealed class GoEmitter : ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;

    public string TargetName => "Go";
    public string FileExtension => ".go";

    public string Emit(IRModule module)
    {
        m_constructorNames = CollectConstructorNames(module);
        m_definitionArity = ValueMap<string, int>.s_empty;
        foreach (IRDefinition d in module.Definitions)
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);

        StringBuilder sb = new();
        sb.AppendLine("// Generated by Codex compiler — Go backend");
        sb.AppendLine("package main");
        sb.AppendLine();
        sb.AppendLine("import (");
        sb.AppendLine("\t\"fmt\"");
        sb.AppendLine("\t\"strings\"");
        sb.AppendLine("\t\"strconv\"");
        sb.AppendLine("\t\"math\"");
        sb.AppendLine("\t\"os\"");
        sb.AppendLine("\t\"bufio\"");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("var _ = fmt.Sprint");
        sb.AppendLine("var _ = strings.Replace");
        sb.AppendLine("var _ = strconv.Itoa");
        sb.AppendLine("var _ = math.Pow");
        sb.AppendLine("var _ = os.Open");
        sb.AppendLine("var _ = bufio.NewReader");
        sb.AppendLine();

        EmitTypeDefinitions(sb, module);

        IRDefinition? mainDef = module.Definitions
            .FirstOrDefault(d => d.Name == "main" && d.Parameters.Length == 0);

        foreach (IRDefinition def in module.Definitions)
        {
            if (def == mainDef) continue;
            EmitDefinition(sb, def);
            sb.AppendLine();
        }

        if (mainDef is not null)
        {
            sb.AppendLine("func main() {");
            if (IsEffectfulDefinition(mainDef))
            {
                EmitStatement(sb, mainDef.Body, 1);
            }
            else
            {
                sb.Append("\tfmt.Println(");
                EmitExpr(sb, mainDef.Body, 1);
                sb.AppendLine(")");
            }
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("func main() {");
            if (module.Definitions.Length == 0)
                sb.AppendLine("\tfmt.Println(\"All proofs verified at compile time.\")");
            else
                sb.AppendLine("\tfmt.Println(\"Module loaded.\")");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void EmitTypeDefinitions(StringBuilder sb, IRModule module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    EmitSumType(sb, sum);
                    break;
                case RecordType rec:
                    EmitRecordType(sb, rec);
                    break;
            }
        }
    }

    static void EmitSumType(StringBuilder sb, SumType sum)
    {
        string baseName = Sanitize(sum.TypeName.Value);
        sb.AppendLine($"type {baseName} interface {{ is{baseName}() }}");
        sb.AppendLine();

        foreach (SumConstructorType ctor in sum.Constructors)
        {
            string name = Sanitize(ctor.Name.Value);
            sb.AppendLine($"type {name} struct {{");
            for (int i = 0; i < ctor.Fields.Length; i++)
                sb.AppendLine($"\tField{i} {EmitType(ctor.Fields[i])}");
            sb.AppendLine("}");
            sb.AppendLine($"func ({name}) is{baseName}() {{}}");
            sb.AppendLine();
        }
    }

    static void EmitRecordType(StringBuilder sb, RecordType rec)
    {
        string name = Sanitize(rec.TypeName.Value);
        sb.AppendLine($"type {name} struct {{");
        for (int i = 0; i < rec.Fields.Length; i++)
        {
            RecordFieldType field = rec.Fields[i];
            sb.AppendLine($"\t{Capitalize(Sanitize(field.FieldName.Value))} {EmitType(field.Type)}");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        if (HasSelfTailCall(def))
        {
            EmitTailCallDefinition(sb, def);
            return;
        }

        string name = Sanitize(def.Name);
        string retType = EmitReturnType(def);

        sb.Append($"func {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{Sanitize(def.Parameters[i].Name)} {EmitType(def.Parameters[i].Type)}");
        }
        sb.Append(')');
        if (!IsEffectfulDefinition(def))
            sb.Append($" {retType}");
        sb.AppendLine(" {");

        if (IsEffectfulDefinition(def))
        {
            EmitStatement(sb, def.Body, 1);
        }
        else
        {
            sb.Append("\treturn ");
            EmitExpr(sb, def.Body, 1);
            sb.AppendLine();
        }
        sb.AppendLine("}");
    }

    void EmitTailCallDefinition(StringBuilder sb, IRDefinition def)
    {
        string name = Sanitize(def.Name);
        string retType = EmitReturnType(def);

        sb.Append($"func {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append($"{Sanitize(def.Parameters[i].Name)} {EmitType(def.Parameters[i].Type)}");
        }
        sb.AppendLine($") {retType} {{");
        sb.AppendLine("\tfor {");

        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, 2);

        sb.AppendLine("\t}");
        sb.AppendLine("}");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new('\t', indent);

        switch (expr)
        {
            case IRIf iff:
                sb.Append($"{pad}if ");
                EmitExpr(sb, iff.Condition, indent);
                sb.AppendLine(" {");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}} else {{");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}}");
                break;

            case IRLet let:
                sb.Append($"{pad}{Sanitize(let.Name)} := ");
                EmitExpr(sb, let.Value, indent);
                sb.AppendLine();
                EmitTailCallBody(sb, let.Body, funcName, parameters, indent);
                break;

            case IRMatch match:
                EmitTailCallMatch(sb, match, funcName, parameters, indent);
                break;

            case IRApply app when IsSelfCall(app, funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    sb.Append($"{pad}_tco_{i} := ");
                    EmitExpr(sb, args[i], indent);
                    sb.AppendLine();
                }
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                    sb.AppendLine($"{pad}{Sanitize(parameters[i].Name)} = _tco_{i}");
                sb.AppendLine($"{pad}continue");
                break;
            }

            default:
                sb.Append($"{pad}return ");
                EmitExpr(sb, expr, indent);
                sb.AppendLine();
                break;
        }
    }

    void EmitTailCallMatch(
        StringBuilder sb, IRMatch match, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new('\t', indent);
        sb.Append($"{pad}switch _v := (");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.AppendLine(").(type) {");

        foreach (IRMatchBranch branch in match.Branches)
        {
            switch (branch.Pattern)
            {
                case IRCtorPattern ctorPat:
                    sb.AppendLine($"{pad}case {Sanitize(ctorPat.Name)}:");
                    for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
                    {
                        if (ctorPat.SubPatterns[i] is IRVarPattern svp)
                            sb.AppendLine($"{pad}\t{Sanitize(svp.Name)} := _v.Field{i}");
                    }
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    break;

                case IRVarPattern varPat:
                    sb.AppendLine($"{pad}default:");
                    sb.AppendLine($"{pad}\t{Sanitize(varPat.Name)} := _v");
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    break;

                case IRWildcardPattern:
                    sb.AppendLine($"{pad}default:");
                    EmitTailCallBody(sb, branch.Body, funcName, parameters, indent + 1);
                    break;
            }
        }
        sb.AppendLine($"{pad}}}");
    }

    void EmitExpr(StringBuilder sb, IRExpr expr, int indent)
    {
        switch (expr)
        {
            case IRIntegerLit lit:
                sb.Append($"int64({lit.Value})");
                break;

            case IRNumberLit lit:
                sb.Append($"float64({lit.Value})");
                break;

            case IRTextLit lit:
                sb.Append($"\"{EscapeString(lit.Value)}\"");
                break;

            case IRBoolLit lit:
                sb.Append(lit.Value ? "true" : "false");
                break;

            case IRName name:
                if (name.Name == "read-line")
                    sb.Append("func() string { r := bufio.NewReader(os.Stdin); l, _ := r.ReadString('\\n'); return strings.TrimSpace(l) }()");
                else if (name.Name == "show")
                    sb.Append("fmt.Sprint");
                else if (name.Name == "negate")
                    sb.Append("func(x int64) int64 { return -x }");
                else if (name.Name == "True")
                    sb.Append("true");
                else if (name.Name == "False")
                    sb.Append("false");
                else if (name.Name == "Nothing")
                    sb.Append("nil");
                else if (name.Name.Length > 0 && char.IsUpper(name.Name[0])
                    && name.Type is not FunctionType
                    && m_constructorNames.Contains(name.Name))
                    sb.Append($"{Sanitize(name.Name)}{{}}");
                else if (m_definitionArity.TryGet(name.Name, out int nameArity)
                    && nameArity == 0
                    && name.Type is not FunctionType)
                    sb.Append($"{Sanitize(name.Name)}()");
                else
                    sb.Append(Sanitize(name.Name));
                break;

            case IRBinary bin:
                EmitBinary(sb, bin, indent);
                break;

            case IRNegate neg:
                sb.Append("(-");
                EmitExpr(sb, neg.Operand, indent);
                sb.Append(')');
                break;

            case IRIf iff:
                sb.Append("func() ");
                sb.Append(EmitType(iff.Type));
                sb.Append(" { if ");
                EmitExpr(sb, iff.Condition, indent);
                sb.Append(" { return ");
                EmitExpr(sb, iff.Then, indent);
                sb.Append(" } else { return ");
                EmitExpr(sb, iff.Else, indent);
                sb.Append(" } }()");
                break;

            case IRLet let:
                sb.Append("func() ");
                sb.Append(EmitType(let.Type));
                sb.Append($" {{ {Sanitize(let.Name)} := ");
                EmitExpr(sb, let.Value, indent);
                sb.Append("; return ");
                EmitExpr(sb, let.Body, indent);
                sb.Append(" }()");
                break;

            case IRApply app:
                EmitApply(sb, app, indent);
                break;

            case IRLambda lam:
                sb.Append("func(");
                for (int i = 0; i < lam.Parameters.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append($"{Sanitize(lam.Parameters[i].Name)} {EmitType(lam.Parameters[i].Type)}");
                }
                sb.Append(") ");
                sb.Append(EmitType(lam.Body.Type));
                sb.Append(" { return ");
                EmitExpr(sb, lam.Body, indent);
                sb.Append(" }");
                break;

            case IRList list:
                sb.Append($"[]{ EmitType(list.ElementType)}{{");
                for (int i = 0; i < list.Elements.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, list.Elements[i], indent);
                }
                sb.Append('}');
                break;

            case IRMatch match:
                EmitMatch(sb, match, indent);
                break;

            case IRDo doExpr:
                EmitDoExpr(sb, doExpr, indent);
                break;

            case IRRecord rec:
                sb.Append($"{Sanitize(rec.TypeName)}{{");
                for (int i = 0; i < rec.Fields.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, rec.Fields[i].Value, indent);
                }
                sb.Append('}');
                break;

            case IRFieldAccess fa:
                EmitExpr(sb, fa.Record, indent);
                sb.Append('.');
                sb.Append(Capitalize(Sanitize(fa.FieldName)));
                break;

            case IRError err:
                sb.Append($"func() interface{{}} {{ panic(\"{EscapeString(err.Message)}\") }}()");
                break;

            default:
                sb.Append("nil");
                break;
        }
    }

    void EmitApply(StringBuilder sb, IRApply app, int indent)
    {
        if (app.Function is IRName fn && fn.Name == "show")
        {
            sb.Append("fmt.Sprint(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn2 && fn2.Name == "negate")
        {
            sb.Append("(-"); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn3 && fn3.Name == "print-line")
        {
            sb.Append("fmt.Println("); EmitExpr(sb, app.Argument, indent); sb.Append(')');
        }
        else if (app.Function is IRName fn7 && fn7.Name == "text-length")
        {
            sb.Append("int64(len("); EmitExpr(sb, app.Argument, indent); sb.Append("))");
        }
        else if (app.Function is IRName fn8 && fn8.Name == "is-letter")
        {
            sb.Append("(len("); EmitExpr(sb, app.Argument, indent);
            sb.Append(") > 0 && ((");
            EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] >= 'a' && "); EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] <= 'z') || ("); EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] >= 'A' && "); EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] <= 'Z')))");
        }
        else if (app.Function is IRName fn9 && fn9.Name == "is-digit")
        {
            sb.Append("(len("); EmitExpr(sb, app.Argument, indent);
            sb.Append(") > 0 && "); EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] >= '0' && "); EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] <= '9')");
        }
        else if (app.Function is IRName fn10 && fn10.Name == "is-whitespace")
        {
            sb.Append("(len("); EmitExpr(sb, app.Argument, indent);
            sb.Append(") > 0 && ("); EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] == ' ' || "); EmitExpr(sb, app.Argument, indent);
            sb.Append("[0] == '\\t'))");
        }
        else if (app.Function is IRName fn11 && fn11.Name == "text-to-integer")
        {
            sb.Append("func() int64 { v, _ := strconv.ParseInt(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(", 10, 64); return v }()");
        }
        else if (app.Function is IRName fn11b && fn11b.Name == "integer-to-text")
        {
            sb.Append("strconv.FormatInt("); EmitExpr(sb, app.Argument, indent); sb.Append(", 10)");
        }
        else if (app.Function is IRName fn12 && fn12.Name == "char-code")
        {
            sb.Append("int64("); EmitExpr(sb, app.Argument, indent); sb.Append("[0])");
        }
        else if (app.Function is IRName fn13 && fn13.Name == "code-to-char")
        {
            sb.Append("string(rune("); EmitExpr(sb, app.Argument, indent); sb.Append("))");
        }
        else if (app.Function is IRName fn14 && fn14.Name == "list-length")
        {
            sb.Append("int64(len("); EmitExpr(sb, app.Argument, indent); sb.Append("))");
        }
        else if (TryEmitMultiArgBuiltin(sb, app, indent))
        {
        }
        else
        {
            EmitApplyGeneral(sb, app, indent);
        }
    }

    void EmitApplyGeneral(StringBuilder sb, IRApply app, int indent)
    {
        string? ctorName = FindConstructorName(app);
        if (ctorName is not null)
        {
            List<IRExpr> args = [];
            CollectApplyArgs(app, args);
            sb.Append($"{Sanitize(ctorName)}{{");
            for (int i = 0; i < args.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                EmitExpr(sb, args[i], indent);
            }
            sb.Append('}');
        }
        else
        {
            string? defName = FindDefinitionName(app);
            if (defName is not null
                && m_definitionArity.TryGet(defName, out int arity)
                && arity > 1)
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                if (args.Count == arity)
                {
                    sb.Append(Sanitize(defName));
                    sb.Append('(');
                    for (int i = 0; i < args.Count; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        EmitExpr(sb, args[i], indent);
                    }
                    sb.Append(')');
                }
                else
                {
                    EmitExpr(sb, app.Function, indent);
                    sb.Append('(');
                    EmitExpr(sb, app.Argument, indent);
                    sb.Append(')');
                }
            }
            else
            {
                EmitExpr(sb, app.Function, indent);
                sb.Append('(');
                EmitExpr(sb, app.Argument, indent);
                sb.Append(')');
            }
        }
    }

    void EmitBinary(StringBuilder sb, IRBinary bin, int indent)
    {
        switch (bin.Op)
        {
            case IRBinaryOp.AppendText:
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append(" + ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.AppendList:
                sb.Append("append(");
                EmitExpr(sb, bin.Left, indent);
                sb.Append(", ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append("...)");
                break;

            case IRBinaryOp.ConsList:
                sb.Append("append([]");
                sb.Append(EmitType(bin.Left.Type));
                sb.Append('{');
                EmitExpr(sb, bin.Left, indent);
                sb.Append("}, ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append("...)");
                break;

            case IRBinaryOp.PowInt:
                sb.Append("int64(math.Pow(float64(");
                EmitExpr(sb, bin.Left, indent);
                sb.Append("), float64(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(")))");
                break;

            default:
                string op = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
                    IRBinaryOp.DivInt or IRBinaryOp.DivNum => "/",
                    IRBinaryOp.Eq => "==",
                    IRBinaryOp.NotEq => "!=",
                    IRBinaryOp.Lt => "<",
                    IRBinaryOp.Gt => ">",
                    IRBinaryOp.LtEq => "<=",
                    IRBinaryOp.GtEq => ">=",
                    IRBinaryOp.And => "&&",
                    IRBinaryOp.Or => "||",
                    _ => "+"
                };
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append($" {op} ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;
        }
    }

    void EmitMatch(StringBuilder sb, IRMatch match, int indent)
    {
        sb.Append("func() ");
        sb.Append(EmitType(match.Type));
        sb.Append(" { switch _v := (");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.Append(").(type) { ");

        foreach (IRMatchBranch branch in match.Branches)
        {
            switch (branch.Pattern)
            {
                case IRCtorPattern ctorPat:
                    sb.Append($"case {Sanitize(ctorPat.Name)}: ");
                    for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
                    {
                        if (ctorPat.SubPatterns[i] is IRVarPattern svp)
                            sb.Append($"{Sanitize(svp.Name)} := _v.Field{i}; ");
                    }
                    sb.Append("return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; ");
                    break;

                case IRLiteralPattern litPat:
                    sb.Append("case ");
                    EmitLiteralValue(sb, litPat.Value);
                    sb.Append(": return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; ");
                    break;

                case IRVarPattern varPat:
                    sb.Append($"default: {Sanitize(varPat.Name)} := _v; return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; ");
                    break;

                case IRWildcardPattern:
                    sb.Append("default: return ");
                    EmitExpr(sb, branch.Body, indent);
                    sb.Append("; ");
                    break;
            }
        }
        sb.Append("default: panic(\"non-exhaustive\") } }()");
    }

    void EmitDoExpr(StringBuilder sb, IRDo doExpr, int indent)
    {
        sb.AppendLine("func() interface{} {");
        string pad = new('\t', indent + 1);
        foreach (IRDoStatement stmt in doExpr.Statements)
        {
            switch (stmt)
            {
                case IRDoBind bind:
                    sb.Append($"{pad}{Sanitize(bind.Name)} := ");
                    EmitExpr(sb, bind.Value, indent + 1);
                    sb.AppendLine();
                    break;
                case IRDoExec exec:
                    sb.Append(pad);
                    EmitExpr(sb, exec.Expression, indent + 1);
                    sb.AppendLine();
                    break;
            }
        }
        sb.Append(new string('\t', indent));
        sb.Append("return nil }()");
    }

    void EmitStatement(StringBuilder sb, IRExpr expr, int indent)
    {
        string pad = new('\t', indent);
        if (expr is IRDo doExpr)
        {
            foreach (IRDoStatement stmt in doExpr.Statements)
            {
                switch (stmt)
                {
                    case IRDoBind bind:
                        sb.Append($"{pad}{Sanitize(bind.Name)} := ");
                        EmitExpr(sb, bind.Value, indent);
                        sb.AppendLine();
                        break;
                    case IRDoExec exec:
                        sb.Append(pad);
                        EmitExpr(sb, exec.Expression, indent);
                        sb.AppendLine();
                        break;
                }
            }
        }
        else
        {
            sb.Append(pad);
            EmitExpr(sb, expr, indent);
            sb.AppendLine();
        }
    }

    bool TryEmitMultiArgBuiltin(StringBuilder sb, IRApply app, int indent)
    {
        string? name = FindBuiltinRoot(app);
        if (name is null) return false;

        List<IRExpr> args = [];
        CollectApplyArgs(app, args);

        switch (name)
        {
            case "char-at" when args.Count == 2:
                sb.Append("string(");
                EmitExpr(sb, args[0], indent);
                sb.Append('[');
                EmitExpr(sb, args[1], indent);
                sb.Append("])");
                return true;

            case "substring" when args.Count == 3:
                EmitExpr(sb, args[0], indent);
                sb.Append('[');
                EmitExpr(sb, args[1], indent);
                sb.Append(':');
                EmitExpr(sb, args[1], indent);
                sb.Append("+");
                EmitExpr(sb, args[2], indent);
                sb.Append(']');
                return true;

            case "list-at" when args.Count == 2:
                EmitExpr(sb, args[0], indent);
                sb.Append('[');
                EmitExpr(sb, args[1], indent);
                sb.Append(']');
                return true;

            case "text-replace" when args.Count == 3:
                sb.Append("strings.ReplaceAll(");
                EmitExpr(sb, args[0], indent);
                sb.Append(", ");
                EmitExpr(sb, args[1], indent);
                sb.Append(", ");
                EmitExpr(sb, args[2], indent);
                sb.Append(')');
                return true;

            default:
                return false;
        }
    }

    static void EmitLiteralValue(StringBuilder sb, object value)
    {
        switch (value)
        {
            case bool b: sb.Append(b ? "true" : "false"); break;
            case long l: sb.Append($"int64({l})"); break;
            case string s: sb.Append($"\"{EscapeString(s)}\""); break;
            default: sb.Append(value); break;
        }
    }

    static string EmitType(CodexType type) => type switch
    {
        IntegerType => "int64",
        NumberType => "float64",
        TextType => "string",
        BooleanType => "bool",
        NothingType => "interface{}",
        VoidType => "interface{}",
        EffectfulType eft => EmitType(eft.Return),
        LinearType lin => EmitType(lin.Inner),
        ListType lt => $"[]{EmitType(lt.Element)}",
        FunctionType ft => $"func({EmitType(ft.Parameter)}) {EmitType(ft.Return)}",
        SumType st => Sanitize(st.TypeName.Value),
        RecordType rt => Sanitize(rt.TypeName.Value),
        TypeVariable => "interface{}",
        _ => "interface{}"
    };

    string EmitReturnType(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType) type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType) type = pft2.Return;
        if (type is EffectfulType eft) type = eft.Return;
        return EmitType(type);
    }

    static string? FindConstructorName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && name.Name.Length > 0 && char.IsUpper(name.Name[0]) ? name.Name : null;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]) ? name.Name : null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner) CollectApplyArgs(inner, args);
        args.Add(app.Argument);
    }

    static readonly Set<string> s_multiArgBuiltins = Set<string>.Of("char-at", "substring", "list-at", "text-replace");

    static string? FindBuiltinRoot(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && s_multiArgBuiltins.Contains(name.Name) ? name.Name : null;
    }

    static Set<string> CollectConstructorNames(IRModule module)
    {
        Set<string> names = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
            if (kv.Value is SumType sum)
                foreach (SumConstructorType ctor in sum.Constructors)
                    names = names.Add(ctor.Name.Value);
        return names;
    }

    static bool HasSelfTailCall(IRDefinition def) =>
        def.Parameters.Length > 0 && ExprHasTailCall(def.Body, def.Name);

    static bool ExprHasTailCall(IRExpr expr, string funcName) => expr switch
    {
        IRIf iff => ExprHasTailCall(iff.Then, funcName) || ExprHasTailCall(iff.Else, funcName),
        IRLet let => ExprHasTailCall(let.Body, funcName),
        IRMatch match => match.Branches.Any(b => ExprHasTailCall(b.Body, funcName)),
        IRApply app => IsSelfCall(app, funcName),
        _ => false
    };

    static bool IsSelfCall(IRApply app, string funcName)
    {
        IRExpr root = app.Function;
        while (root is IRApply inner) root = inner.Function;
        return root is IRName name && name.Name == funcName;
    }

    static bool IsEffectfulDefinition(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType) type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType) type = pft2.Return;
        return type is EffectfulType;
    }

    static string Sanitize(string name)
    {
        string sanitized = name.Replace('-', '_');
        return sanitized switch
        {
            "func" or "var" or "const" or "type" or "struct" or "interface" or "map"
            or "chan" or "go" or "select" or "defer" or "range" or "return" or "if"
            or "else" or "for" or "switch" or "case" or "break" or "continue" or "default"
            or "package" or "import" or "fallthrough" or "goto"
                => $"_{sanitized}",
            _ => sanitized
        };
    }

    static string Capitalize(string s) => s.Length == 0 ? s : char.ToUpper(s[0]) + s[1..];

    static string EscapeString(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\n", "\\n")
        .Replace("\r", "\\r")
        .Replace("\t", "\\t");
}
