-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 arithmetic.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Arithmetic is

   function Max(X : Long_Long_Integer; Y : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (if (X > Y) then X else Y);
   end Max;

   function Abs_v(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (if (X < 0) then (-X) else X);
   end Abs_v;

   function Clamp(Lo : Long_Long_Integer; Hi : Long_Long_Integer; X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (declare Clamped : constant Long_Long_Integer := (if (X < Lo) then Lo else (if (X > Hi) then Hi else X)) begin Clamped);
   end Clamp;

begin
   Put(Long_Long_Integer'Image(Clamp(0, 100, Abs_v(Max((-42), 37)))));
   New_Line;
end Arithmetic;
