-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 effects_demo.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Effects_demo is

   procedure Greet(Name : Unbounded_String) is
   begin
      Put_Line(To_String((To_Unbounded_String("Hello, ") & (Name & To_Unbounded_String("!")))));
   end Greet;

begin
   Greet(To_Unbounded_String("Alice"));
   Greet(To_Unbounded_String("Bob"));
   Put_Line(To_String(To_Unbounded_String("Done!")));
end Effects_demo;
