-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 effectful_hello.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Effectful_hello is

begin
   Put_Line(To_String(To_Unbounded_String("What is your name?")));
   -- bind: name
   Put_Line(To_String((To_Unbounded_String("Hello, ") & (Name & To_Unbounded_String("!")))));
end Effectful_hello;
