-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 expr_calculator.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Expr_calculator is

   type Expr_Tag is (Tag_Lit, Tag_Add, Tag_Sub, Tag_Mul, Tag_Div);
   type Expr(Kind : Expr_Tag := Expr_Tag'First) is record
      case Kind is
         when Tag_Lit =>
            Tag_Lit_F0 : Long_Long_Integer;
         when Tag_Add =>
            Tag_Add_F0 : Long_Long_Integer;
            Tag_Add_F1 : Long_Long_Integer;
         when Tag_Sub =>
            Tag_Sub_F0 : Long_Long_Integer;
            Tag_Sub_F1 : Long_Long_Integer;
         when Tag_Mul =>
            Tag_Mul_F0 : Long_Long_Integer;
            Tag_Mul_F1 : Long_Long_Integer;
         when Tag_Div =>
            Tag_Div_F0 : Long_Long_Integer;
            Tag_Div_F1 : Long_Long_Integer;
      end case;
   end record;

   type ParseResult is record
      Expr : Long_Long_Integer;
      Pos : Long_Long_Integer;
   end record;

   function Skip_ws(Input_0 : Unbounded_String; Pos_0 : Long_Long_Integer) return Long_Long_Integer is
      Input : Unbounded_String := Input_0;
      Pos : Long_Long_Integer := Pos_0;
   begin
      loop
         if (Pos >= Long_Long_Integer(Length(Input))) then
            return Pos;
         else
            if Is_whitespace(Char_at(Input)(Pos)) then
               Input := Input;
               Pos := (Pos + 1);
            else
               return Pos;
            end if;
         end if;
      end loop;
   end Skip_ws;

   function Collect_digits(Input_0 : Unbounded_String; Pos_0 : Long_Long_Integer; Len_0 : Long_Long_Integer; Acc_0 : Long_Long_Integer) return Long_Long_Integer is
      Input : Unbounded_String := Input_0;
      Pos : Long_Long_Integer := Pos_0;
      Len : Long_Long_Integer := Len_0;
      Acc : Long_Long_Integer := Acc_0;
   begin
      loop
         if (Pos >= Len) then
            return Acc;
         else
            if Is_digit(Char_at(Input)(Pos)) then
               declare
                  D : constant Long_Long_Integer := Text_to_integer(Char_at(Input)(Pos));
               begin
                  Input := Input;
                  Pos := (Pos + 1);
                  Len := Len;
                  Acc := ((Acc * 10) + D);
               end;
            else
               return Acc;
            end if;
         end if;
      end loop;
   end Collect_digits;

   function Digit_count(Input : Unbounded_String; Pos : Long_Long_Integer; Len : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (if (Pos >= Len) then 0 else (if Is_digit(Char_at(Input)(Pos)) then (1 + Digit_count(Input, (Pos + 1), Len)) else 0));
   end Digit_count;

   function Parse_atom(Input : Unbounded_String; Start : Long_Long_Integer) return ParseResult is
   begin
      return (declare Pos : constant Long_Long_Integer := Skip_ws(Input, Start) begin (declare Len : constant Long_Long_Integer := Long_Long_Integer(Length(Input)) begin (if (Pos >= Len) then (Expr => (Kind => Tag_Lit, Tag_Lit_F0 => 0), Pos => Pos) else (if (Char_at(Input)(Pos) = To_Unbounded_String("(")) then (declare Inner : constant ParseResult := Parse_additive(Input, (Pos + 1)) begin (declare After : constant Long_Long_Integer := Skip_ws(Input, Inner.Pos) begin (if (After < Len) then (Expr => Inner.Expr, Pos => (After + 1)) else (Expr => Inner.Expr, Pos => After)))) else (declare Digits_v : constant Long_Long_Integer := Digit_count(Input, Pos, Len) begin (if (Digits_v > 0) then (declare Value : constant Long_Long_Integer := Collect_digits(Input, Pos, Len, 0) begin (Expr => (Kind => Tag_Lit, Tag_Lit_F0 => Value), Pos => (Pos + Digits_v))) else (Expr => (Kind => Tag_Lit, Tag_Lit_F0 => 0), Pos => Pos)))))));
   end Parse_atom;

   function Parse_multiplicative(Input : Unbounded_String; Start : Long_Long_Integer) return ParseResult is
   begin
      return (declare Left : constant ParseResult := Parse_atom(Input, Start) begin Continue_multiplicative(Input, Left));
   end Parse_multiplicative;

   function Continue_multiplicative(Input_0 : Unbounded_String; Current_0 : ParseResult) return ParseResult is
      Input : Unbounded_String := Input_0;
      Current : ParseResult := Current_0;
   begin
      loop
         declare
            Pos : constant Long_Long_Integer := Skip_ws(Input, Current.Pos);
         begin
            declare
               Len : constant Long_Long_Integer := Long_Long_Integer(Length(Input));
            begin
               if (Pos >= Len) then
                  return Current;
               else
                  if (Char_at(Input)(Pos) = To_Unbounded_String("*")) then
                     declare
                        Right : constant ParseResult := Parse_atom(Input, (Pos + 1));
                     begin
                        Input := Input;
                        Current := (Expr => (Kind => Tag_Mul, Tag_Mul_F0 => Current.Expr, Tag_Mul_F1 => Right.Expr), Pos => Right.Pos);
                     end;
                  else
                     if (Char_at(Input)(Pos) = To_Unbounded_String("/")) then
                        declare
                           Right : constant ParseResult := Parse_atom(Input, (Pos + 1));
                        begin
                           Input := Input;
                           Current := (Expr => (Kind => Tag_Div, Tag_Div_F0 => Current.Expr, Tag_Div_F1 => Right.Expr), Pos => Right.Pos);
                        end;
                     else
                        return Current;
                     end if;
                  end if;
               end if;
            end;
         end;
      end loop;
   end Continue_multiplicative;

   function Parse_additive(Input : Unbounded_String; Start : Long_Long_Integer) return ParseResult is
   begin
      return (declare Left : constant ParseResult := Parse_multiplicative(Input, Start) begin Continue_additive(Input, Left));
   end Parse_additive;

   function Continue_additive(Input_0 : Unbounded_String; Current_0 : ParseResult) return ParseResult is
      Input : Unbounded_String := Input_0;
      Current : ParseResult := Current_0;
   begin
      loop
         declare
            Pos : constant Long_Long_Integer := Skip_ws(Input, Current.Pos);
         begin
            declare
               Len : constant Long_Long_Integer := Long_Long_Integer(Length(Input));
            begin
               if (Pos >= Len) then
                  return Current;
               else
                  if (Char_at(Input)(Pos) = To_Unbounded_String("+")) then
                     declare
                        Right : constant ParseResult := Parse_multiplicative(Input, (Pos + 1));
                     begin
                        Input := Input;
                        Current := (Expr => (Kind => Tag_Add, Tag_Add_F0 => Current.Expr, Tag_Add_F1 => Right.Expr), Pos => Right.Pos);
                     end;
                  else
                     if (Char_at(Input)(Pos) = To_Unbounded_String("-")) then
                        declare
                           Right : constant ParseResult := Parse_multiplicative(Input, (Pos + 1));
                        begin
                           Input := Input;
                           Current := (Expr => (Kind => Tag_Sub, Tag_Sub_F0 => Current.Expr, Tag_Sub_F1 => Right.Expr), Pos => Right.Pos);
                        end;
                     else
                        return Current;
                     end if;
                  end if;
               end if;
            end;
         end;
      end loop;
   end Continue_additive;

   function Parse(Input : Unbounded_String) return Expr is
   begin
      return Parse_additive(Input, 0).Expr;
   end Parse;

   function Eval(E : Expr) return Long_Long_Integer is
   begin
      return (case E.Kind is when Tag_Lit => N, when Tag_Add => (Eval(A) + Eval(B)), when Tag_Sub => (Eval(A) - Eval(B)), when Tag_Mul => (Eval(A) * Eval(B)), when Tag_Div => (Eval(A) / Eval(B)), when others => raise Program_Error);
   end Eval;

   function Format(E : Expr) return Unbounded_String is
   begin
      return (case E.Kind is when Tag_Lit => To_Unbounded_String(Long_Long_Integer'Image(N)), when Tag_Add => (To_Unbounded_String("(") & (Format(A) & (To_Unbounded_String(" + ") & (Format(B) & To_Unbounded_String(")"))))), when Tag_Sub => (To_Unbounded_String("(") & (Format(A) & (To_Unbounded_String(" - ") & (Format(B) & To_Unbounded_String(")"))))), when Tag_Mul => (To_Unbounded_String("(") & (Format(A) & (To_Unbounded_String(" * ") & (Format(B) & To_Unbounded_String(")"))))), when Tag_Div => (To_Unbounded_String("(") & (Format(A) & (To_Unbounded_String(" / ") & (Format(B) & To_Unbounded_String(")"))))), when others => raise Program_Error);
   end Format;

   function Test_expr(Input : Unbounded_String; Expected : Long_Long_Integer) return Unbounded_String is
   begin
      return (declare Tree : constant Expr := Parse(Input) begin (declare Result : constant Long_Long_Integer := Eval(Tree) begin (declare Status : constant Unbounded_String := (if (Result = Expected) then To_Unbounded_String("PASS") else To_Unbounded_String("FAIL")) begin (Status & (To_Unbounded_String(": ") & (Input & (To_Unbounded_String(" = ") & (To_Unbounded_String(Long_Long_Integer'Image(Result)) & (To_Unbounded_String(" (expected ") & (To_Unbounded_String(Long_Long_Integer'Image(Expected)) & (To_Unbounded_String(")  tree: ") & Format(Tree))))))))))));
   end Test_expr;

begin
   Put_Line(To_String(To_Unbounded_String("=== Expression Calculator ===")));
   Put_Line(To_String(To_Unbounded_String("")));
   Put_Line(To_String(Test_expr(To_Unbounded_String("42"), 42)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("2 + 3"), 5)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("10 - 4"), 6)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("3 * 7"), 21)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("100 / 5"), 20)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("2 + 3 * 4"), 14)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("10 - 2 * 3"), 4)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("(2 + 3) * 4"), 20)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("1 + 2 + 3 + 4"), 10)));
   Put_Line(To_String(Test_expr(To_Unbounded_String("2 * 3 + 4 * 5"), 26)));
   Put_Line(To_String(To_Unbounded_String("")));
   Put_Line(To_String(To_Unbounded_String("All PASS = compiler correctly compiles a recursive descent parser.")));
   Put_Line(To_String(To_Unbounded_String("QED: not a quine.")));
end Expr_calculator;
