-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 factorial.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Factorial is

   function Abs_v(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (if (X < 0) then (-X) else X);
   end Abs_v;

   function Max(X : Long_Long_Integer; Y : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (if (X > Y) then X else Y);
   end Max;

   function Factorial(N : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (if (N = 0) then 1 else (N * Factorial((N - 1))));
   end Factorial;

begin
   Put(Long_Long_Integer'Image(Factorial(10)));
   New_Line;
end Factorial;
