-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 fibonacci.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Fibonacci is

   function Fib(N : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (if (N = 0) then 0 else (if (N = 1) then 1 else (Fib((N - 1)) + Fib((N - 2)))));
   end Fib;

begin
   Put(Long_Long_Integer'Image(Fib(20)));
   New_Line;
end Fibonacci;
