-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 greeting.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Greeting is

   function Greeting(Name : Unbounded_String) return Unbounded_String is
   begin
      return (To_Unbounded_String("Hello, ") & (Name & To_Unbounded_String("!")));
   end Greeting;

begin
   Put_Line(To_String(Greeting(To_Unbounded_String("World"))));
end Greeting;
