-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 hello.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Hello is

   function Square(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (X * X);
   end Square;

   function Double(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (X + X);
   end Double;

begin
   Put(Long_Long_Integer'Image(Square(5)));
   New_Line;
end Hello;
