-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 is_prime.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Is_prime is

   function Is_prime(N : Long_Long_Integer) return Boolean is
   begin
      return (if (N < 2) then False else Check_divisor(N, 2));
   end Is_prime;

   function Check_divisor(N_0 : Long_Long_Integer; D_0 : Long_Long_Integer) return Boolean is
      N : Long_Long_Integer := N_0;
      D : Long_Long_Integer := D_0;
   begin
      loop
         if ((D * D) > N) then
            return True;
         else
            if (((N / D) * D) = N) then
               return False;
            else
               N := N;
               D := (D + 1);
            end if;
         end if;
      end loop;
   end Check_divisor;

begin
   Put_Line(To_String((declare A : constant Boolean := Is_prime(2) begin (declare B : constant Boolean := Is_prime(17) begin (declare C : constant Boolean := Is_prime(49) begin (declare D : constant Boolean := Is_prime(97) begin (To_Unbounded_String(Long_Long_Integer'Image(A)) & (To_Unbounded_String(" ") & (To_Unbounded_String(Long_Long_Integer'Image(B)) & (To_Unbounded_String(" ") & (To_Unbounded_String(Long_Long_Integer'Image(C)) & (To_Unbounded_String(" ") & To_Unbounded_String(Long_Long_Integer'Image(D))))))))))))));
end Is_prime;
