-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 mathlib.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure MathLib is

   function Square(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (X * X);
   end Square;

   function Cube(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return ((X * X) * X);
   end Cube;

   function Helper(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (X + 1);
   end Helper;

begin
   null;
end MathLib;
