-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 mini_bootstrap.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Mini_bootstrap is

   type Point is record
      X : Long_Long_Integer;
      Y : Long_Long_Integer;
   end record;

   type Color_Tag is (Tag_Red, Tag_Green, Tag_Blue);
   type Color(Kind : Color_Tag := Color_Tag'First) is record
      case Kind is
         when Tag_Red =>
            null;
         when Tag_Green =>
            null;
         when Tag_Blue =>
            Tag_Blue_F0 : Long_Long_Integer;
      end case;
   end record;

   function Show_color(C : Color) return Unbounded_String is
   begin
      return (case C.Kind is when Tag_Red => To_Unbounded_String("red"), when Tag_Green => To_Unbounded_String("green"), when Tag_Blue => To_Unbounded_String("blue"), when others => raise Program_Error);
   end Show_color;

   function Get_x(P : Point) return Long_Long_Integer is
   begin
      return P.X;
   end Get_x;

   function Add_points(A : Point; B : Point) return Point is
   begin
      return (X => (A.X + B.X), Y => (A.Y + B.Y));
   end Add_points;

   function Map_list(F : Long_Long_Integer; Xs : Long_Long_Integer) return Long_Long_Integer is
   begin
      return Map_list_loop(F, Xs, 0, List_length(Xs), (1 .. 0 => <>));
   end Map_list;

   function Map_list_loop(F_0 : Long_Long_Integer; Xs_0 : Long_Long_Integer; I_0 : Long_Long_Integer; Len_0 : Long_Long_Integer; Acc_0 : Long_Long_Integer) return Long_Long_Integer is
      F : Long_Long_Integer := F_0;
      Xs : Long_Long_Integer := Xs_0;
      I : Long_Long_Integer := I_0;
      Len : Long_Long_Integer := Len_0;
      Acc : Long_Long_Integer := Acc_0;
   begin
      loop
         if (I = Len) then
            return Acc;
         else
            F := F;
            Xs := Xs;
            I := (I + 1);
            Len := Len;
            Acc := (Acc + (1 .. 0 => <>));
         end if;
      end loop;
   end Map_list_loop;

   function Use_map(Pts : Long_Long_Integer) return Long_Long_Integer is
   begin
      return Map_list(Get_x, Pts);
   end Use_map;

begin
   Put_Line("<result>");
end Mini_bootstrap;
