-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 person_main.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Person_Main is

   type Person is record
      Name : Unbounded_String;
      Age : Long_Long_Integer;
   end record;

   function Greet(P : Person) return Unbounded_String is
   begin
      return (To_Unbounded_String("Hello, ") & (P.Name & To_Unbounded_String("!")));
   end Greet;

begin
   Put_Line(To_String(Greet((Name => To_Unbounded_String("Alice"), Age => 30))));
end Person_Main;
