-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 prose_greeting.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Prose_greeting is

   function Greet(Name : Unbounded_String) return Unbounded_String is
   begin
      return (To_Unbounded_String("Hello, ") & (Name & To_Unbounded_String("!")));
   end Greet;

begin
   Put_Line(To_String(Greet(To_Unbounded_String("World"))));
end Prose_greeting;
