-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 safe_divide.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Safe_divide is

   type Result_Tag is (Tag_Success, Tag_Failure);
   type Result(Kind : Result_Tag := Result_Tag'First) is record
      case Kind is
         when Tag_Success =>
            Tag_Success_F0 : Long_Long_Integer;
         when Tag_Failure =>
            Tag_Failure_F0 : Unbounded_String;
      end case;
   end record;

   function Safe_divide(X : Long_Long_Integer; Y : Long_Long_Integer) return Result is
   begin
      return (if (Y = 0) then (Kind => Tag_Failure, Tag_Failure_F0 => To_Unbounded_String("division by zero")) else (Kind => Tag_Success, Tag_Success_F0 => (X / Y)));
   end Safe_divide;

   function Describe(Result : Result) return Unbounded_String is
   begin
      return (case Result.Kind is when Tag_Success => (To_Unbounded_String("got ") & To_Unbounded_String(Long_Long_Integer'Image(N))), when Tag_Failure => (To_Unbounded_String("error: ") & Msg), when others => raise Program_Error);
   end Describe;

begin
   Put_Line(To_String(Describe(Safe_divide(42, 7))));
end Safe_divide;
