-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 stage1_test.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Stage1_test is

   function Square(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (X * X);
   end Square;

   function Greet(Name : Unbounded_String) return Unbounded_String is
   begin
      return (To_Unbounded_String("Hello, ") & (Name & To_Unbounded_String("!")));
   end Greet;

begin
   Put_Line(To_String(Greet(To_Unbounded_String("Codex"))));
   Put_Line(To_String(To_Unbounded_String(Long_Long_Integer'Image(Square(7)))));
end Stage1_test;
