-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 string_ops.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure String_ops is

   function Is_identifier_char(Ch : Unbounded_String) return Boolean is
   begin
      return (if Is_letter(Ch) then True else (if Is_digit(Ch) then True else (if (Ch = To_Unbounded_String("-")) then True else False)));
   end Is_identifier_char;

   function Count_letters(S_0 : Unbounded_String; I_0 : Long_Long_Integer; Acc_0 : Long_Long_Integer) return Long_Long_Integer is
      S : Unbounded_String := S_0;
      I : Long_Long_Integer := I_0;
      Acc : Long_Long_Integer := Acc_0;
   begin
      loop
         if (I >= Long_Long_Integer(Length(S))) then
            return Acc;
         else
            declare
               Ch : constant Unbounded_String := Char_at(S)(I);
            begin
               if Is_letter(Ch) then
                  S := S;
                  I := (I + 1);
                  Acc := (Acc + 1);
               else
                  S := S;
                  I := (I + 1);
                  Acc := Acc;
               end if;
            end;
         end if;
      end loop;
   end Count_letters;

begin
   Put(Long_Long_Integer'Image(Count_letters(To_Unbounded_String("hello world 123"), 0, 0)));
   New_Line;
end String_ops;
