-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 tco_stress.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Tco_stress is

   function Sum_to(N_0 : Long_Long_Integer; Acc_0 : Long_Long_Integer) return Long_Long_Integer is
      N : Long_Long_Integer := N_0;
      Acc : Long_Long_Integer := Acc_0;
   begin
      loop
         if (N = 0) then
            return Acc;
         else
            N := (N - 1);
            Acc := (Acc + N);
         end if;
      end loop;
   end Sum_to;

begin
   Put(Long_Long_Integer'Image(Sum_to(1000000, 0)));
   New_Line;
end Tco_stress;
