-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 test_run_process.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Test_run_process is

begin
   Put_Line("All proofs verified at compile time.");
end Test_run_process;
