-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 test_run_process.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Test_run_process is

begin
   (declare Result : constant Unbounded_String := Run_process(To_Unbounded_String("dotnet"))(To_Unbounded_String("--version")) begin Put_Line(To_String((To_Unbounded_String("dotnet version: ") & Result))));
end Test_run_process;
