-- Generated by Codex compiler — Ada backend
-- Compile: gnatmake -gnat2012 type_checker_test.adb
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Integer_Text_IO; use Ada.Integer_Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

procedure Type_checker_test is

   function Add_one(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (X + 1);
   end Add_one;

   function Double(X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return (X * 2);
   end Double;

   function Greet(Name : Unbounded_String) return Unbounded_String is
   begin
      return (To_Unbounded_String("Hello, ") & (Name & To_Unbounded_String("!")));
   end Greet;

   function Is_positive(X : Long_Long_Integer) return Boolean is
   begin
      return (X > 0);
   end Is_positive;

   function Apply_twice(F : Long_Long_Integer; X : Long_Long_Integer) return Long_Long_Integer is
   begin
      return F(F(X));
   end Apply_twice;

begin
   Put(Long_Long_Integer'Image(Apply_twice(Add_one, 40)));
   New_Line;
end Type_checker_test;
