# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def max(x, y):
    return (x if (x > y) else y)

def abs(x):
    return ((-x) if (x < 0) else x)

def clamp(lo, hi, x):
    return (lambda clamped: clamped)((lo if (x < lo) else (hi if (x > hi) else x)))

def main():
    return clamp(0, 100, abs(max((-42), 37)))

print(main())
