# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def greet(name):
    print(("Hello, " + (name + "!")))

def main():
    greet("Alice")
    greet("Bob")
    print("Done!")

main()
