# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def abs(x):
    return ((-x) if (x < 0) else x)

def max(x, y):
    return (x if (x > y) else y)

def factorial(n):
    return (1 if (n == 0) else (n * factorial((n - 1))))

def main():
    return factorial(10)

print(main())
