# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def fib(n):
    return (0 if (n == 0) else (1 if (n == 1) else (fib((n - 1)) + fib((n - 2)))))

def main():
    return fib(20)

print(main())
