# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def greeting(name):
    return ("Hello, " + (name + "!"))

def main():
    return greeting("World")

print(main())
