# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def square(x):
    return (x * x)

def cube(x):
    return ((x * x) * x)

def helper(x):
    return (x + 1)

