# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

@dataclass(frozen=True)
class Point:
    x: Any = None
    y: Any = None

@dataclass(frozen=True)
class Red:
    tag: str = "Red"

@dataclass(frozen=True)
class Green:
    tag: str = "Green"

@dataclass(frozen=True)
class Blue:
    field0: Any = None
    tag: str = "Blue"

def show_color(c):
    return (lambda _s: ("red" if isinstance(_s, Red) else ("green" if isinstance(_s, Green) else ((lambda n: "blue")(_s.field0) if isinstance(_s, Blue) else (_ for _ in ()).throw(Exception("Non-exhaustive match"))))))(c)

def get_x(p):
    return p.x

def add_points(a, b):
    return Point(x=(a.x + b.x), y=(a.y + b.y))

def map_list(f, xs):
    return map_list_loop(f, xs, 0, len(xs), [])

def map_list_loop(f, xs, i, len, acc):
    while True:
        if (i == len):
            return acc
        else:
            _tco_0 = f
            _tco_1 = xs
            _tco_2 = (i + 1)
            _tco_3 = len
            _tco_4 = (acc + [f(xs[i])])
            f, xs, i, len, acc = _tco_0, _tco_1, _tco_2, _tco_3, _tco_4
            continue

def use_map(pts):
    return map_list(get_x, pts)

def main():
    return use_map([Point(x=1, y=2)])

print(main())
