# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def greet(name):
    return ("Hello, " + (name + "!"))

def main():
    return greet("World")

print(main())
