# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def is_identifier_char(ch):
    return (True if ch.isalpha() else (True if ch.isdigit() else (True if (ch == "-") else False)))

def count_letters(s, i, acc):
    while True:
        if (i >= len(s)):
            return acc
        else:
            ch = s[i]
            if ch.isalpha():
                _tco_0 = s
                _tco_1 = (i + 1)
                _tco_2 = (acc + 1)
                s, i, acc = _tco_0, _tco_1, _tco_2
                continue
            else:
                _tco_0 = s
                _tco_1 = (i + 1)
                _tco_2 = acc
                s, i, acc = _tco_0, _tco_1, _tco_2
                continue

def main():
    return count_letters("hello world 123", 0, 0)

print(main())
