# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def sum_to(n, acc):
    while True:
        if (n == 0):
            return acc
        else:
            _tco_0 = (n - 1)
            _tco_1 = (acc + n)
            n, acc = _tco_0, _tco_1
            continue

def main():
    return sum_to(1000000, 0)

print(main())
