# Generated by Codex compiler — Python backend
from dataclasses import dataclass
from typing import Any

def main():
    (lambda result: print(("dotnet version: " + result)))(run_process("dotnet")("--version"))

main()
