! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_arithmetic
  implicit none

contains

  integer(8) function max(x, y)
    integer(8), intent(in) :: x
    integer(8), intent(in) :: y
    max = merge(x, y, (x > y))
  end function max

  integer(8) function abs(x)
    integer(8), intent(in) :: x
    abs = merge((-x), x, (x < 0_8))
  end function abs

  integer(8) function clamp(lo, hi, x)
    integer(8), intent(in) :: lo
    integer(8), intent(in) :: hi
    integer(8), intent(in) :: x
    clamp = clamped
  end function clamp

end module codex_arithmetic

program main_program
  use codex_arithmetic
  implicit none
  print *, clamp(0_8, 100_8, abs(max((-42_8), 37_8)))
end program main_program
