! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_effects_demo
  implicit none

contains

  subroutine greet(name)
    character(len=256), intent(in) :: name
    implicit none
    print *, trim('Hello, ') // trim(trim(name) // trim('!'))
  end subroutine greet

end module codex_effects_demo

program main_program
  use codex_effects_demo
  implicit none
  greet('Alice')
  greet('Bob')
  print *, 'Done!'
end program main_program
