! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

program main_program
  implicit none
  print *, 'What is your name?'
  ! bind: name
  print *, trim('Hello, ') // trim(trim(name) // trim('!'))
end program main_program
