! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_expr_calculator
  implicit none

  type :: ParseResult
    integer(8) :: expr
    integer(8) :: pos
  end type ParseResult

  ! Sum type: Expr
  ! Tag constants:
  integer, parameter :: TAG_Lit = 1
  integer, parameter :: TAG_Add = 2
  integer, parameter :: TAG_Sub = 3
  integer, parameter :: TAG_Mul = 4
  integer, parameter :: TAG_Div = 5

  type :: Expr
    integer :: tag
    integer(8) :: field0
    integer(8) :: field1
  end type Expr

contains

  integer(8) function skip_ws(input_in, pos_in)
    character(len=256), intent(in) :: input_in
    integer(8), intent(in) :: pos_in
    character(len=256) :: input
    integer(8) :: pos
    input = input_in
    pos = pos_in
    do while (.true.)
      if ((pos >= int(len_trim(input), 8))) then
        skip_ws = pos
        return
      else
        if (is_whitespace(char_at(input)(pos))) then
          input = input
          pos = (pos + 1_8)
          cycle
        else
          skip_ws = pos
          return
        end if
      end if
    end do
  end function skip_ws

  integer(8) function collect_digits(input_in, pos_in, len_v_in, acc_in)
    character(len=256), intent(in) :: input_in
    integer(8), intent(in) :: pos_in
    integer(8), intent(in) :: len_v_in
    integer(8), intent(in) :: acc_in
    character(len=256) :: input
    integer(8) :: pos
    integer(8) :: len_v
    integer(8) :: acc
    input = input_in
    pos = pos_in
    len_v = len_v_in
    acc = acc_in
    do while (.true.)
      if ((pos >= len_v)) then
        collect_digits = acc
        return
      else
        if (is_digit(char_at(input)(pos))) then
collect_digits(input, (pos + 1_8), len_v, ((acc * 10_8) + d))        else
          collect_digits = acc
          return
        end if
      end if
    end do
  end function collect_digits

  integer(8) function digit_count(input, pos, len_v)
    character(len=256), intent(in) :: input
    integer(8), intent(in) :: pos
    integer(8), intent(in) :: len_v
    digit_count = merge(0_8, merge((1_8 + digit_count(input, (pos + 1_8), len_v)), 0_8, is_digit(char_at(input)(pos))), (pos >= len_v))
  end function digit_count

  type(ParseResult) function parse_atom(input, start)
    character(len=256), intent(in) :: input
    integer(8), intent(in) :: start
    parse_atom = merge(ParseResult(Lit(0_8), pos), merge(merge(ParseResult(inner%expr, (after + 1_8)), ParseResult(inner%expr, after), (after < len_v)), merge(ParseResult(Lit(value), (pos + digits)), ParseResult(Lit(0_8), pos), (digits > 0_8)), (char_at(input)(pos) == '(')), (pos >= len_v))
  end function parse_atom

  type(ParseResult) function parse_multiplicative(input, start)
    character(len=256), intent(in) :: input
    integer(8), intent(in) :: start
    parse_multiplicative = continue_multiplicative(input, left)
  end function parse_multiplicative

  type(ParseResult) function continue_multiplicative(input_in, current_in)
    character(len=256), intent(in) :: input_in
    type(ParseResult), intent(in) :: current_in
    character(len=256) :: input
    type(ParseResult) :: current
    input = input_in
    current = current_in
    do while (.true.)
merge(current, merge(continue_multiplicative(input, ParseResult(Mul(current%expr)(right%expr), right%pos)), merge(continue_multiplicative(input, ParseResult(Div(current%expr)(right%expr), right%pos)), current, (char_at(input)(pos) == '/')), (char_at(input)(pos) == '*')), (pos >= len_v))    end do
  end function continue_multiplicative

  type(ParseResult) function parse_additive(input, start)
    character(len=256), intent(in) :: input
    integer(8), intent(in) :: start
    parse_additive = continue_additive(input, left)
  end function parse_additive

  type(ParseResult) function continue_additive(input_in, current_in)
    character(len=256), intent(in) :: input_in
    type(ParseResult), intent(in) :: current_in
    character(len=256) :: input
    type(ParseResult) :: current
    input = input_in
    current = current_in
    do while (.true.)
merge(current, merge(continue_additive(input, ParseResult(Add(current%expr)(right%expr), right%pos)), merge(continue_additive(input, ParseResult(Sub(current%expr)(right%expr), right%pos)), current, (char_at(input)(pos) == '-')), (char_at(input)(pos) == '+')), (pos >= len_v))    end do
  end function continue_additive

  type(Expr) function parse(input)
    character(len=256), intent(in) :: input
    parse = parse_additive(input, 0_8)%expr
  end function parse

  integer(8) function eval(e)
    type(Expr), intent(in) :: e
    select case (e%tag)
      case (TAG_Lit)
        eval = e%field0
      case (TAG_Add)
        eval = (eval(e%field0) + eval(e%field1))
      case (TAG_Sub)
        eval = (eval(e%field0) - eval(e%field1))
      case (TAG_Mul)
        eval = (eval(e%field0) * eval(e%field1))
      case (TAG_Div)
        eval = (eval(e%field0) / eval(e%field1))
    end select
  end function eval

  character(len=256) function format(e)
    type(Expr), intent(in) :: e
    select case (e%tag)
      case (TAG_Lit)
        format = '<value>'
      case (TAG_Add)
        format = trim('(') // trim(trim(format(e%field0)) // trim(trim(' + ') // trim(trim(format(e%field1)) // trim(')'))))
      case (TAG_Sub)
        format = trim('(') // trim(trim(format(e%field0)) // trim(trim(' - ') // trim(trim(format(e%field1)) // trim(')'))))
      case (TAG_Mul)
        format = trim('(') // trim(trim(format(e%field0)) // trim(trim(' * ') // trim(trim(format(e%field1)) // trim(')'))))
      case (TAG_Div)
        format = trim('(') // trim(trim(format(e%field0)) // trim(trim(' / ') // trim(trim(format(e%field1)) // trim(')'))))
    end select
  end function format

  character(len=256) function test_expr(input, expected)
    character(len=256), intent(in) :: input
    integer(8), intent(in) :: expected
    test_expr = trim(status) // trim(trim(': ') // trim(trim(input) // trim(trim(' = ') // trim(trim('<value>') // trim(trim(' (expected ') // trim(trim('<value>') // trim(trim(')  tree: ') // trim(format(tree)))))))))
  end function test_expr

end module codex_expr_calculator

program main_program
  use codex_expr_calculator
  implicit none
  print *, '=== Expression Calculator ==='
  print *, ''
  print *, test_expr('42', 42_8)
  print *, test_expr('2 + 3', 5_8)
  print *, test_expr('10 - 4', 6_8)
  print *, test_expr('3 * 7', 21_8)
  print *, test_expr('100 / 5', 20_8)
  print *, test_expr('2 + 3 * 4', 14_8)
  print *, test_expr('10 - 2 * 3', 4_8)
  print *, test_expr('(2 + 3) * 4', 20_8)
  print *, test_expr('1 + 2 + 3 + 4', 10_8)
  print *, test_expr('2 * 3 + 4 * 5', 26_8)
  print *, ''
  print *, 'All PASS = compiler correctly compiles a recursive descent parser.'
  print *, 'QED: not a quine.'
end program main_program
