! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_factorial
  implicit none

contains

  integer(8) function abs(x)
    integer(8), intent(in) :: x
    abs = merge((-x), x, (x < 0_8))
  end function abs

  integer(8) function max(x, y)
    integer(8), intent(in) :: x
    integer(8), intent(in) :: y
    max = merge(x, y, (x > y))
  end function max

  integer(8) function factorial(n)
    integer(8), intent(in) :: n
    factorial = merge(1_8, (n * factorial((n - 1_8))), (n == 0_8))
  end function factorial

end module codex_factorial

program main_program
  use codex_factorial
  implicit none
  print *, factorial(10_8)
end program main_program
