! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_fibonacci
  implicit none

contains

  integer(8) function fib(n)
    integer(8), intent(in) :: n
    fib = merge(0_8, merge(1_8, (fib((n - 1_8)) + fib((n - 2_8))), (n == 1_8)), (n == 0_8))
  end function fib

end module codex_fibonacci

program main_program
  use codex_fibonacci
  implicit none
  print *, fib(20_8)
end program main_program
