! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_greeting
  implicit none

contains

  character(len=256) function greeting(name)
    character(len=256), intent(in) :: name
    greeting = trim('Hello, ') // trim(trim(name) // trim('!'))
  end function greeting

end module codex_greeting

program main_program
  use codex_greeting
  implicit none
  print *, greeting('World')
end program main_program
