! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_hello
  implicit none

contains

  integer(8) function square(x)
    integer(8), intent(in) :: x
    square = (x * x)
  end function square

  integer(8) function double_v(x)
    integer(8), intent(in) :: x
    double_v = (x + x)
  end function double_v

end module codex_hello

program main_program
  use codex_hello
  implicit none
  print *, square(5_8)
end program main_program
