! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_is_prime_fancy
  implicit none

contains

  integer(8) function range(lo, hi)
    integer(8), intent(in) :: lo
    integer(8), intent(in) :: hi
    range = merge(0, (0 + range((lo + 1_8), hi)), (lo > hi))
  end function range

  logical function divides(d, n)
    integer(8), intent(in) :: d
    integer(8), intent(in) :: n
    divides = (((n / d) * d) == n)
  end function divides

  logical function has_no_divisors_in(divisors_in, n_in, i_in, len_v_in)
    integer(8), intent(in) :: divisors_in
    integer(8), intent(in) :: n_in
    integer(8), intent(in) :: i_in
    integer(8), intent(in) :: len_v_in
    integer(8) :: divisors
    integer(8) :: n
    integer(8) :: i
    integer(8) :: len_v
    divisors = divisors_in
    n = n_in
    i = i_in
    len_v = len_v_in
    do while (.true.)
      if ((i == len_v)) then
        has_no_divisors_in = .true.
        return
      else
merge(.false., has_no_divisors_in(divisors, n, (i + 1_8), len_v), divides(d, n))      end if
    end do
  end function has_no_divisors_in

  integer(8) function small_divisors(xs_in, limit_in, i_in, len_v_in)
    integer(8), intent(in) :: xs_in
    integer(8), intent(in) :: limit_in
    integer(8), intent(in) :: i_in
    integer(8), intent(in) :: len_v_in
    integer(8) :: xs
    integer(8) :: limit
    integer(8) :: i
    integer(8) :: len_v
    xs = xs_in
    limit = limit_in
    i = i_in
    len_v = len_v_in
    do while (.true.)
      if ((i == len_v)) then
        small_divisors = 0
        return
      else
merge((0 + small_divisors(xs, limit, (i + 1_8), len_v)), small_divisors(xs, limit, (i + 1_8), len_v), ((x * x) <= limit))      end if
    end do
  end function small_divisors

  logical function is_prime(n)
    integer(8), intent(in) :: n
    is_prime = merge(.false., has_no_divisors_in(small, n, 0_8, list_length(small)), (n < 2_8))
  end function is_prime

  integer(8) function collect_primes(xs_in, i_in, len_v_in)
    integer(8), intent(in) :: xs_in
    integer(8), intent(in) :: i_in
    integer(8), intent(in) :: len_v_in
    integer(8) :: xs
    integer(8) :: i
    integer(8) :: len_v
    xs = xs_in
    i = i_in
    len_v = len_v_in
    do while (.true.)
      if ((i == len_v)) then
        collect_primes = 0
        return
      else
merge((0 + collect_primes(xs, (i + 1_8), len_v)), collect_primes(xs, (i + 1_8), len_v), is_prime(x))      end if
    end do
  end function collect_primes

  character(len=256) function join_with_spaces(xs, i, len_v)
    integer(8), intent(in) :: xs
    integer(8), intent(in) :: i
    integer(8), intent(in) :: len_v
    join_with_spaces = merge('', merge(list_at(xs)(i), trim(list_at(xs)(i)) // trim(trim(' ') // trim(join_with_spaces(xs, (i + 1_8), len_v))), (i == (len_v - 1_8))), (i == len_v))
  end function join_with_spaces

end module codex_is_prime_fancy

program main_program
  use codex_is_prime_fancy
  implicit none
  print *, trim('Primes up to 50: ') // trim(join_with_spaces(primes, 0_8, list_length(primes)))
end program main_program
