! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_is_prime
  implicit none

contains

  logical function is_prime(n)
    integer(8), intent(in) :: n
    is_prime = merge(.false., check_divisor(n, 2_8), (n < 2_8))
  end function is_prime

  logical function check_divisor(n_in, d_in)
    integer(8), intent(in) :: n_in
    integer(8), intent(in) :: d_in
    integer(8) :: n
    integer(8) :: d
    n = n_in
    d = d_in
    do while (.true.)
      if (((d * d) > n)) then
        check_divisor = .true.
        return
      else
        if ((((n / d) * d) == n)) then
          check_divisor = .false.
          return
        else
          n = n
          d = (d + 1_8)
          cycle
        end if
      end if
    end do
  end function check_divisor

end module codex_is_prime

program main_program
  use codex_is_prime
  implicit none
  print *, trim('<value>') // trim(trim(' ') // trim(trim('<value>') // trim(trim(' ') // trim(trim('<value>') // trim(trim(' ') // trim('<value>'))))))
end program main_program
