! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_MathLib
  implicit none

contains

  integer(8) function square(x)
    integer(8), intent(in) :: x
    square = (x * x)
  end function square

  integer(8) function cube(x)
    integer(8), intent(in) :: x
    cube = ((x * x) * x)
  end function cube

  integer(8) function helper(x)
    integer(8), intent(in) :: x
    helper = (x + 1_8)
  end function helper

end module codex_MathLib

program main_program
  use codex_MathLib
  implicit none
end program main_program
