! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_mini_bootstrap
  implicit none

  type :: Point
    integer(8) :: x
    integer(8) :: y
  end type Point

  ! Sum type: Color
  ! Tag constants:
  integer, parameter :: TAG_Red = 1
  integer, parameter :: TAG_Green = 2
  integer, parameter :: TAG_Blue = 3

  type :: Color
    integer :: tag
    integer(8) :: field0
  end type Color

contains

  character(len=256) function show_color(c)
    type(Color), intent(in) :: c
    select case (c%tag)
      case (TAG_Red)
        show_color = 'red'
      case (TAG_Green)
        show_color = 'green'
      case (TAG_Blue)
        show_color = 'blue'
    end select
  end function show_color

  integer(8) function get_x(p)
    type(Point), intent(in) :: p
    get_x = p%x
  end function get_x

  type(Point) function add_points(a, b)
    type(Point), intent(in) :: a
    type(Point), intent(in) :: b
    add_points = Point((a%x + b%x), (a%y + b%y))
  end function add_points

  integer(8) function map_list(f, xs)
    integer(8), intent(in) :: f
    integer(8), intent(in) :: xs
    map_list = map_list_loop(f, xs, 0_8, list_length(xs), 0)
  end function map_list

  integer(8) function map_list_loop(f_in, xs_in, i_in, len_v_in, acc_in)
    integer(8), intent(in) :: f_in
    integer(8), intent(in) :: xs_in
    integer(8), intent(in) :: i_in
    integer(8), intent(in) :: len_v_in
    integer(8), intent(in) :: acc_in
    integer(8) :: f
    integer(8) :: xs
    integer(8) :: i
    integer(8) :: len_v
    integer(8) :: acc
    f = f_in
    xs = xs_in
    i = i_in
    len_v = len_v_in
    acc = acc_in
    do while (.true.)
      if ((i == len_v)) then
        map_list_loop = acc
        return
      else
        f = f
        xs = xs
        i = (i + 1_8)
        len_v = len_v
        acc = (acc + 0)
        cycle
      end if
    end do
  end function map_list_loop

  integer(8) function use_map(pts)
    integer(8), intent(in) :: pts
    use_map = map_list(get_x, pts)
  end function use_map

end module codex_mini_bootstrap

program main_program
  use codex_mini_bootstrap
  implicit none
  print *, use_map(0)
end program main_program
