! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

program main_program
  implicit none
  print *, 'All proofs verified at compile time.'
end program main_program
