! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_safe_divide
  implicit none

  ! Sum type: Result
  ! Tag constants:
  integer, parameter :: TAG_Success = 1
  integer, parameter :: TAG_Failure = 2

  type :: Result
    integer :: tag
    integer(8) :: field0
  end type Result

contains

  type(Result) function safe_divide(x, y)
    integer(8), intent(in) :: x
    integer(8), intent(in) :: y
    safe_divide = merge(Failure('division by zero'), Success((x / y)), (y == 0_8))
  end function safe_divide

  character(len=256) function describe(result_v)
    type(Result), intent(in) :: result_v
    select case (result_v%tag)
      case (TAG_Success)
        describe = trim('got ') // trim('<value>')
      case (TAG_Failure)
        describe = trim('error: ') // trim(result_v%field0)
    end select
  end function describe

end module codex_safe_divide

program main_program
  use codex_safe_divide
  implicit none
  print *, describe(safe_divide(42_8, 7_8))
end program main_program
