! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_shapes
  implicit none

  ! Sum type: Shape
  ! Tag constants:
  integer, parameter :: TAG_Circle = 1
  integer, parameter :: TAG_Rectangle = 2

  type :: Shape
    integer :: tag
    integer(8) :: field0
    integer(8) :: field1
  end type Shape

contains

end module codex_shapes

program main_program
  use codex_shapes
  implicit none
  select case (Circle(5.0d0)%tag)
    case (TAG_Circle)
      print * ((3.14d0 * Circle(5.0d0)%field0) * Circle(5.0d0)%field0)
    case (TAG_Rectangle)
      print * (Circle(5.0d0)%field0 * Circle(5.0d0)%field1)
  end select
end program main_program
