! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_stage1_test
  implicit none

contains

  integer(8) function square(x)
    integer(8), intent(in) :: x
    square = (x * x)
  end function square

  character(len=256) function greet(name)
    character(len=256), intent(in) :: name
    greet = trim('Hello, ') // trim(trim(name) // trim('!'))
  end function greet

end module codex_stage1_test

program main_program
  use codex_stage1_test
  implicit none
  print *, greet('Codex')
  print *, '<value>'
end program main_program
