! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_string_ops
  implicit none

contains

  logical function is_identifier_char(ch)
    character(len=256), intent(in) :: ch
    is_identifier_char = merge(.true., merge(.true., merge(.true., .false., (ch == '-')), is_digit(ch)), is_letter(ch))
  end function is_identifier_char

  integer(8) function count_letters(s_in, i_in, acc_in)
    character(len=256), intent(in) :: s_in
    integer(8), intent(in) :: i_in
    integer(8), intent(in) :: acc_in
    character(len=256) :: s
    integer(8) :: i
    integer(8) :: acc
    s = s_in
    i = i_in
    acc = acc_in
    do while (.true.)
      if ((i >= int(len_trim(s), 8))) then
        count_letters = acc
        return
      else
merge(count_letters(s, (i + 1_8), (acc + 1_8)), count_letters(s, (i + 1_8), acc), is_letter(ch))      end if
    end do
  end function count_letters

end module codex_string_ops

program main_program
  use codex_string_ops
  implicit none
  print *, count_letters('hello world 123', 0_8, 0_8)
end program main_program
