! Generated by Codex compiler — Fortran backend
! Compile: gfortran -o output output.f90

module codex_tco_stress
  implicit none

contains

  integer(8) function sum_to(n_in, acc_in)
    integer(8), intent(in) :: n_in
    integer(8), intent(in) :: acc_in
    integer(8) :: n
    integer(8) :: acc
    n = n_in
    acc = acc_in
    do while (.true.)
      if ((n == 0_8)) then
        sum_to = acc
        return
      else
        n = (n - 1_8)
        acc = (acc + n)
        cycle
      end if
    end do
  end function sum_to

end module codex_tco_stress

program main_program
  use codex_tco_stress
  implicit none
  print *, sum_to(1000000_8, 0_8)
end program main_program
