using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Babbage;

public sealed class BabbageEmitter : ICodeEmitter
{
    int m_nextStore = 10;
    ValueMap<string, int> m_storeMap = ValueMap<string, int>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;
    int m_labelCounter;

    public string TargetName => "Babbage Analytical Engine";
    public string FileExtension => ".ae";

    public string Emit(IRChapter module)
    {
        m_nextStore = 10;
        m_storeMap = ValueMap<string, int>.s_empty;
        m_definitionArity = ValueMap<string, int>.s_empty;
        m_labelCounter = 0;

        foreach (IRDefinition d in module.Definitions)
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);

        StringBuilder sb = new();
        sb.AppendLine(". ---------------------------------------------------");
        sb.AppendLine(". Analytical Engine program");
        sb.AppendLine(". Generated by Codex compiler — Babbage backend");
        sb.AppendLine(". Charles Babbage would be proud (and confused).");
        sb.AppendLine(". ---------------------------------------------------");
        sb.AppendLine(". Store columns 0-9: scratch registers");
        sb.AppendLine(". Store columns 10+: program variables");
        sb.AppendLine(". The Mill performs all arithmetic operations.");
        sb.AppendLine(". ---------------------------------------------------");
        sb.AppendLine();

        IRDefinition? mainDef = module.Definitions
            .FirstOrDefault(d => d.Name == "main" && d.Parameters.Length == 0);

        foreach (IRDefinition def in module.Definitions)
        {
            if (def == mainDef) continue;
            EmitDefinition(sb, def);
            sb.AppendLine();
        }

        if (mainDef is not null)
        {
            sb.AppendLine(". === MAIN PROGRAM ===");
            EmitExprToStore(sb, mainDef.Body, 0);
            sb.AppendLine();
            sb.AppendLine("P  . Print result from Store column 0");
            sb.AppendLine("L000");
            sb.AppendLine();
            sb.AppendLine("H  . Halt the Engine");
        }
        else
        {
            sb.AppendLine(". === MAIN PROGRAM ===");
            if (module.Definitions.Length == 0)
                sb.AppendLine(". All proofs verified. No computation required.");
            else
                sb.AppendLine(". No entry point. Chapter loaded.");
            sb.AppendLine();
            sb.AppendLine("H  . Halt the Engine");
        }

        return sb.ToString();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        sb.AppendLine($". === FUNCTION: {def.Name} ===");
        sb.AppendLine($". Parameters: {string.Join(", ", def.Parameters.Select(p => p.Name))}");

        for (int i = 0; i < def.Parameters.Length; i++)
        {
            int col = AllocStore(def.Parameters[i].Name);
            sb.AppendLine($". Param '{def.Parameters[i].Name}' in Store column {col}");
        }

        if (HasSelfTailCall(def))
        {
            sb.AppendLine(". (Uses iterative loop for tail-call optimization)");
            EmitTailCallDef(sb, def);
        }
        else
        {
            int resultCol = AllocStore($"_result_{def.Name}");
            EmitExprToStore(sb, def.Body, resultCol);
            sb.AppendLine($". Result of {def.Name} in Store column {resultCol}");
        }
    }

    void EmitTailCallDef(StringBuilder sb, IRDefinition def)
    {
        int labelStart = m_labelCounter++;
        int labelEnd = m_labelCounter++;

        sb.AppendLine();
        sb.AppendLine($"LABEL_{labelStart}:  . Loop start for {def.Name}");

        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, labelStart, labelEnd);

        sb.AppendLine($"LABEL_{labelEnd}:  . Loop end for {def.Name}");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int labelStart, int labelEnd)
    {
        switch (expr)
        {
            case IRIf iff:
                int condStore = AllocStore("_cond");
                EmitExprToStore(sb, iff.Condition, condStore);
                int labelElse = m_labelCounter++;
                int labelDone = m_labelCounter++;
                sb.AppendLine($"L{condStore:D3}  . Load condition");
                sb.AppendLine($"CF LABEL_{labelElse}  . Branch if zero");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, labelStart, labelEnd);
                sb.AppendLine($"CB LABEL_{labelDone}  . Jump past else");
                sb.AppendLine($"LABEL_{labelElse}:");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, labelStart, labelEnd);
                sb.AppendLine($"LABEL_{labelDone}:");
                break;

            case IRLet let:
                int letCol = AllocStore(let.Name);
                EmitExprToStore(sb, let.Value, letCol);
                EmitTailCallBody(sb, let.Body, funcName, parameters, labelStart, labelEnd);
                break;

            case IRApply app when IsSelfCall(app, funcName):
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    int tmpCol = AllocStore($"_tco_tmp_{i}");
                    EmitExprToStore(sb, args[i], tmpCol);
                    int paramCol = GetStore(parameters[i].Name);
                    sb.AppendLine($"L{tmpCol:D3}  . Load new value for {parameters[i].Name}");
                    sb.AppendLine($"S{paramCol:D3}  . Store into param column");
                }
                sb.AppendLine($"CB LABEL_{labelStart}  . Continue loop (tail call)");
                break;

            default:
                EmitExprToStore(sb, expr, 0);
                sb.AppendLine($"CB LABEL_{labelEnd}  . Exit loop with result in Store 0");
                break;
        }
    }

    void EmitExprToStore(StringBuilder sb, IRExpr expr, int targetCol)
    {
        switch (expr)
        {
            case IRIntegerLit lit:
                sb.AppendLine($"N{lit.Value:D3}  . Load constant {lit.Value} onto number cards");
                sb.AppendLine($"S{targetCol:D3}  . Store in column {targetCol}");
                break;

            case IRBoolLit lit:
                sb.AppendLine($"N{(lit.Value ? 1 : 0):D3}  . Load boolean {lit.Value}");
                sb.AppendLine($"S{targetCol:D3}");
                break;

            case IRName name:
                if (m_storeMap.TryGet(name.Name, out int srcCol))
                {
                    sb.AppendLine($"L{srcCol:D3}  . Load '{name.Name}'");
                    sb.AppendLine($"S{targetCol:D3}  . Store in column {targetCol}");
                }
                else
                {
                    sb.AppendLine($"N000  . Unknown name '{name.Name}' - load 0");
                    sb.AppendLine($"S{targetCol:D3}");
                }
                break;

            case IRBinary bin:
                int leftCol = AllocStore("_left");
                int rightCol = AllocStore("_right");
                EmitExprToStore(sb, bin.Left, leftCol);
                EmitExprToStore(sb, bin.Right, rightCol);
                sb.AppendLine($"L{leftCol:D3}  . Load left operand into Mill");
                sb.AppendLine($"L{rightCol:D3}  . Load right operand into Mill");
                sb.AppendLine($"{BinOpCard(bin.Op)}  . {BinOpComment(bin.Op)}");
                sb.AppendLine($"S{targetCol:D3}  . Store result from Mill");
                break;

            case IRNegate neg:
                int negCol = AllocStore("_neg");
                EmitExprToStore(sb, neg.Operand, negCol);
                sb.AppendLine($"N000  . Load 0");
                sb.AppendLine($"S{targetCol:D3}");
                sb.AppendLine($"L{targetCol:D3}");
                sb.AppendLine($"L{negCol:D3}");
                sb.AppendLine("-  . Negate: 0 - operand");
                sb.AppendLine($"S{targetCol:D3}");
                break;

            case IRIf iff:
                int condCol = AllocStore("_if_cond");
                EmitExprToStore(sb, iff.Condition, condCol);
                int ifLabel1 = m_labelCounter++;
                int ifLabel2 = m_labelCounter++;
                sb.AppendLine($"L{condCol:D3}  . Load condition into Mill");
                sb.AppendLine($"CF LABEL_{ifLabel1}  . Branch to else if zero");
                EmitExprToStore(sb, iff.Then, targetCol);
                sb.AppendLine($"CB LABEL_{ifLabel2}  . Jump past else");
                sb.AppendLine($"LABEL_{ifLabel1}:");
                EmitExprToStore(sb, iff.Else, targetCol);
                sb.AppendLine($"LABEL_{ifLabel2}:");
                break;

            case IRLet let:
                int letCol = AllocStore(let.Name);
                EmitExprToStore(sb, let.Value, letCol);
                EmitExprToStore(sb, let.Body, targetCol);
                break;

            case IRApply app:
                EmitApplyToStore(sb, app, targetCol);
                break;

            default:
                sb.AppendLine($"N000  . Unsupported expression ({expr.GetType().Name}) - load 0");
                sb.AppendLine($"S{targetCol:D3}");
                break;
        }
    }

    void EmitApplyToStore(StringBuilder sb, IRApply app, int targetCol)
    {
        string? defName = FindDefinitionName(app);
        if (defName is not null
            && m_definitionArity.TryGet(defName, out int arity))
        {
            List<IRExpr> args = [];
            CollectApplyArgs(app, args);
            sb.AppendLine($". Call {defName} with {args.Count} argument(s)");
            for (int i = 0; i < args.Count; i++)
            {
                int argCol = AllocStore($"_arg_{defName}_{i}");
                EmitExprToStore(sb, args[i], argCol);
                sb.AppendLine($". Argument {i} in column {argCol}");
            }
            sb.AppendLine($". (Inline expansion of {defName} would go here)");
            sb.AppendLine($"N000  . Placeholder result");
            sb.AppendLine($"S{targetCol:D3}");
        }
        else
        {
            sb.AppendLine($". Apply expression");
            EmitExprToStore(sb, app.Argument, targetCol);
        }
    }

    int AllocStore(string name)
    {
        if (m_storeMap.TryGet(name, out int existing))
            return existing;
        int col = m_nextStore++;
        m_storeMap = m_storeMap.Set(name, col);
        return col;
    }

    int GetStore(string name)
    {
        if (m_storeMap.TryGet(name, out int col))
            return col;
        return AllocStore(name);
    }

    static string BinOpCard(IRBinaryOp op) => op switch
    {
        IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
        IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
        IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
        IRBinaryOp.DivInt or IRBinaryOp.DivNum => "/",
        IRBinaryOp.Eq => "-",
        IRBinaryOp.NotEq => "-",
        IRBinaryOp.Lt => "-",
        IRBinaryOp.Gt => "-",
        IRBinaryOp.LtEq => "-",
        IRBinaryOp.GtEq => "-",
        IRBinaryOp.And => "*",
        IRBinaryOp.Or => "+",
        _ => "+"
    };

    static string BinOpComment(IRBinaryOp op) => op switch
    {
        IRBinaryOp.AddInt => "Add integers in Mill",
        IRBinaryOp.SubInt => "Subtract integers in Mill",
        IRBinaryOp.MulInt => "Multiply integers in Mill",
        IRBinaryOp.DivInt => "Divide integers in Mill",
        IRBinaryOp.AddNum => "Add numbers in Mill",
        IRBinaryOp.SubNum => "Subtract numbers in Mill",
        IRBinaryOp.MulNum => "Multiply numbers in Mill",
        IRBinaryOp.DivNum => "Divide numbers in Mill",
        IRBinaryOp.Eq => "Compare: subtract (zero = equal)",
        IRBinaryOp.NotEq => "Compare: subtract (nonzero = not equal)",
        IRBinaryOp.Lt => "Compare: subtract (negative = less than)",
        IRBinaryOp.Gt => "Compare: subtract (positive = greater than)",
        IRBinaryOp.And => "Logical AND via multiplication",
        IRBinaryOp.Or => "Logical OR via addition",
        _ => "Operation in Mill"
    };

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner) current = inner.Function;
        return current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]) ? name.Name : null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner) CollectApplyArgs(inner, args);
        args.Add(app.Argument);
    }

    static bool HasSelfTailCall(IRDefinition def) =>
        def.Parameters.Length > 0 && ExprHasTailCall(def.Body, def.Name);

    static bool ExprHasTailCall(IRExpr expr, string funcName) => expr switch
    {
        IRIf iff => ExprHasTailCall(iff.Then, funcName) || ExprHasTailCall(iff.Else, funcName),
        IRLet let => ExprHasTailCall(let.Body, funcName),
        IRMatch match => match.Branches.Any(b => ExprHasTailCall(b.Body, funcName)),
        IRApply app => IsSelfCall(app, funcName),
        _ => false
    };

    static bool IsSelfCall(IRApply app, string funcName)
    {
        IRExpr root = app.Function;
        while (root is IRApply inner) root = inner.Function;
        return root is IRName name && name.Name == funcName;
    }
}
