// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn codex_main() -> () {
    {
        println!("{}", "What is your name?".to_string());
        let name = { let mut s = String::new(); std::io::stdin().read_line(&mut s).unwrap(); s.trim().to_string() };
        println!("{}", format!("{}{}", "Hello, ".to_string(), format!("{}{}", name, "!".to_string())));
    };
}

fn main() {
    codex_main();
}
