// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn fib(n: i64) -> i64 {
    if (n == 0_i64) { 0_i64 } else { if (n == 1_i64) { 1_i64 } else { (fib((n - 1_i64)) + fib((n - 2_i64))) } }
}

fn codex_main() -> i64 {
    fib(20_i64)
}

fn main() {
    println!("{:?}", codex_main());
}
