// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn greeting(name: String) -> String {
    format!("{}{}", "Hello, ".to_string(), format!("{}{}", name, "!".to_string()))
}

fn codex_main() -> String {
    greeting("World".to_string())
}

fn main() {
    println!("{:?}", codex_main());
}
