// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn square(x: i64) -> i64 {
    (x * x)
}

fn double(x: i64) -> i64 {
    (x + x)
}

fn codex_main() -> i64 {
    square(5_i64)
}

fn main() {
    println!("{:?}", codex_main());
}
