// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn square(x: i64) -> i64 {
    (x * x)
}

fn cube(x: i64) -> i64 {
    ((x * x) * x)
}

fn helper(x: i64) -> i64 {
    (x + 1_i64)
}

fn main() {
    println!("Module loaded.");
}
