// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

#[derive(Debug, Clone, PartialEq)]
enum Color {
    Red,
    Green,
    Blue(i64),
}

#[derive(Debug, Clone, PartialEq)]
struct Point {
    x: i64,
    y: i64,
}

fn show_color(c: Color) -> String {
    match c {
        Color::Red => "red".to_string(),
        Color::Green => "green".to_string(),
        Color::Blue(n) => "blue".to_string(),
    }
}

fn get_x(p: Point) -> i64 {
    p.x
}

fn add_points(a: Point, b: Point) -> Point {
    Point { x: (a.x + b.x), y: (a.y + b.y) }
}

fn map_list(f: Box<dyn Fn(Box<dyn std::any::Any>) -> Box<dyn std::any::Any>>, xs: Vec<Box<dyn std::any::Any>>) -> Vec<Box<dyn std::any::Any>> {
    map_list_loop(f, xs, 0_i64, xs.len() as i64, vec![])
}

fn map_list_loop(mut f: Box<dyn Fn(Box<dyn std::any::Any>) -> Box<dyn std::any::Any>>, mut xs: Vec<Box<dyn std::any::Any>>, mut i: i64, mut len: i64, mut acc: Vec<Box<dyn std::any::Any>>) -> Vec<Box<dyn std::any::Any>> {
    loop {
        if (i == len) {
            return acc;
        } else {
            let _tco_0 = f;
            let _tco_1 = xs;
            let _tco_2 = (i + 1_i64);
            let _tco_3 = len;
            let _tco_4 = { let mut v = acc.clone(); v.extend(vec![f(xs[i as usize].clone())].iter().cloned()); v };
            f = _tco_0;
            xs = _tco_1;
            i = _tco_2;
            len = _tco_3;
            acc = _tco_4;
            continue;
        }
    }
}

fn use_map(pts: Vec<Point>) -> Vec<i64> {
    map_list(get_x, pts)
}

fn codex_main() -> Vec<i64> {
    use_map(vec![Point { x: 1_i64, y: 2_i64 }])
}

fn main() {
    println!("{:?}", codex_main());
}
