// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

#[derive(Debug, Clone, PartialEq)]
struct Person {
    name: String,
    age: i64,
}

fn greet(p: Person) -> String {
    format!("{}{}", "Hello, ".to_string(), format!("{}{}", p.name, "!".to_string()))
}

fn codex_main() -> String {
    greet(Person { name: "Alice".to_string(), age: 30_i64 })
}

fn main() {
    println!("{:?}", codex_main());
}
