// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

#[derive(Debug, Clone, PartialEq)]
enum Result {
    Success(Box<dyn std::any::Any>),
    Failure(String),
}

fn safe_divide(x: i64, y: i64) -> Result {
    if (y == 0_i64) { Result::Failure("division by zero".to_string()) } else { Result::Success((x / y)) }
}

fn describe(result: Result) -> String {
    match result {
        Result::Success(n) => format!("{}{}", "got ".to_string(), format!("{}", n)),
        Result::Failure(msg) => format!("{}{}", "error: ".to_string(), msg),
    }
}

fn codex_main() -> String {
    describe(safe_divide(42_i64, 7_i64))
}

fn main() {
    println!("{:?}", codex_main());
}
