// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

#[derive(Debug, Clone, PartialEq)]
enum Shape {
    Circle(f64),
    Rectangle(f64, f64),
}

fn codex_main() -> f64 {
    match Shape::Circle(5.0_f64) {
        Shape::Circle(r) => ((3.14_f64 * r) * r),
        Shape::Rectangle(w, h) => (w * h),
    }
}

fn main() {
    println!("{:?}", codex_main());
}
