// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn square(x: i64) -> i64 {
    (x * x)
}

fn greet(name: String) -> String {
    format!("{}{}", "Hello, ".to_string(), format!("{}{}", name, "!".to_string()))
}

fn codex_main() -> () {
    {
        println!("{}", greet("Codex".to_string()));
        println!("{}", format!("{}", square(7_i64)));
    };
}

fn main() {
    codex_main();
}
