// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn is_identifier_char(ch: String) -> bool {
    if ch.chars().next().map_or(false, |c| c.is_alphabetic()) { true } else { if ch.chars().next().map_or(false, |c| c.is_ascii_digit()) { true } else { if (ch == "-".to_string()) { true } else { false } } }
}

fn count_letters(mut s: String, mut i: i64, mut acc: i64) -> i64 {
    loop {
        if (i >= s.len() as i64) {
            return acc;
        } else {
            let ch = s.chars().nth(i as usize).unwrap().to_string();
            if ch.chars().next().map_or(false, |c| c.is_alphabetic()) {
                let _tco_0 = s;
                let _tco_1 = (i + 1_i64);
                let _tco_2 = (acc + 1_i64);
                s = _tco_0;
                i = _tco_1;
                acc = _tco_2;
                continue;
            } else {
                let _tco_0 = s;
                let _tco_1 = (i + 1_i64);
                let _tco_2 = acc;
                s = _tco_0;
                i = _tco_1;
                acc = _tco_2;
                continue;
            }
        }
    }
}

fn codex_main() -> i64 {
    count_letters("hello world 123".to_string(), 0_i64, 0_i64)
}

fn main() {
    println!("{:?}", codex_main());
}
