// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn codex_main() -> () {
    {
        { let result = run_process("dotnet".to_string())("--version".to_string()); println!("{}", format!("{}{}", "dotnet version: ".to_string(), result)) };
    };
}

fn main() {
    codex_main();
}
