// Generated by Codex compiler — Rust backend
#![allow(non_snake_case, unused_variables, dead_code)]

fn add_one(x: i64) -> i64 {
    (x + 1_i64)
}

fn double(x: i64) -> i64 {
    (x * 2_i64)
}

fn greet(name: String) -> String {
    format!("{}{}", "Hello, ".to_string(), format!("{}{}", name, "!".to_string()))
}

fn is_positive(x: i64) -> bool {
    (x > 0_i64)
}

fn apply_twice(f: Box<dyn Fn(i64) -> i64>, x: i64) -> i64 {
    f(f(x))
}

fn codex_main() -> i64 {
    apply_twice(add_one, 40_i64)
}

fn main() {
    println!("{:?}", codex_main());
}
