using System.Collections.Immutable;
using System.Text;
using Codex.Core;
using Codex.IR;
using Codex.Types;

namespace Codex.Emit.Rust;

public sealed class RustEmitter : ICodeEmitter
{
    Set<string> m_constructorNames = Set<string>.s_empty;
    ValueMap<string, int> m_definitionArity = ValueMap<string, int>.s_empty;
    Map<string, string> m_constructorToEnum = Map<string, string>.s_empty;

    public string TargetName => "Rust";
    public string FileExtension => ".rs";

    public string Emit(IRModule module)
    {
        m_constructorNames = CollectConstructorNames(module);
        m_constructorToEnum = BuildConstructorToEnumMap(module);
        m_definitionArity = ValueMap<string, int>.s_empty;
        foreach (IRDefinition d in module.Definitions)
            m_definitionArity = m_definitionArity.Set(d.Name, d.Parameters.Length);

        StringBuilder sb = new();
        sb.AppendLine("// Generated by Codex compiler — Rust backend");
        sb.AppendLine("#![allow(non_snake_case, unused_variables, dead_code)]");
        sb.AppendLine();

        EmitTypeDefinitions(sb, module);

        foreach (IRDefinition def in module.Definitions)
        {
            EmitDefinition(sb, def);
            sb.AppendLine();
        }

        IRDefinition? mainDef = module.Definitions
            .FirstOrDefault(d => d.Name == "main");

        if (mainDef is not null && mainDef.Parameters.Length == 0)
        {
            sb.AppendLine("fn main() {");
            if (IsEffectfulDefinition(mainDef))
            {
                sb.AppendLine("    codex_main();");
            }
            else
            {
                sb.AppendLine("    println!(\"{:?}\", codex_main());");
            }
            sb.AppendLine("}");
        }
        else
        {
            sb.AppendLine("fn main() {");
            if (module.Definitions.Length == 0)
                sb.AppendLine("    println!(\"All proofs verified at compile time.\");");
            else
                sb.AppendLine("    println!(\"Module loaded.\");");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void EmitTypeDefinitions(StringBuilder sb, IRModule module)
    {
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            switch (kv.Value)
            {
                case SumType sum:
                    EmitSumType(sb, sum);
                    break;
                case RecordType rec:
                    EmitRecordType(sb, rec);
                    break;
            }
        }
    }

    static void EmitSumType(StringBuilder sb, SumType sum)
    {
        string baseName = Sanitize(sum.TypeName.Value);
        sb.AppendLine("#[derive(Debug, Clone, PartialEq)]");
        sb.AppendLine($"enum {baseName} {{");
        foreach (SumConstructorType ctor in sum.Constructors)
        {
            string ctorName = Sanitize(ctor.Name.Value);
            if (ctor.Fields.IsEmpty)
            {
                sb.AppendLine($"    {ctorName},");
            }
            else
            {
                sb.Append($"    {ctorName}(");
                for (int i = 0; i < ctor.Fields.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(EmitType(ctor.Fields[i]));
                }
                sb.AppendLine("),");
            }
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitRecordType(StringBuilder sb, RecordType rec)
    {
        string name = Sanitize(rec.TypeName.Value);
        sb.AppendLine("#[derive(Debug, Clone, PartialEq)]");
        sb.AppendLine($"struct {name} {{");
        foreach (RecordFieldType field in rec.Fields)
        {
            sb.AppendLine($"    {Sanitize(field.FieldName.Value)}: {EmitType(field.Type)},");

        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    void EmitDefinition(StringBuilder sb, IRDefinition def)
    {
        string name = def.Name == "main" ? "codex_main" : Sanitize(def.Name);

        if (HasSelfTailCall(def))
        {
            EmitTailCallDefinition(sb, def, name);
            return;
        }

        string returnType = EmitType(GetReturnType(def));

        sb.Append($"fn {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            IRParameter param = def.Parameters[i];
            sb.Append($"{Sanitize(param.Name)}: {EmitType(param.Type)}");
        }
        sb.AppendLine($") -> {returnType} {{");

        if (IsEffectfulDefinition(def))
        {
            sb.Append("    ");
            EmitExpr(sb, def.Body, 1);
            sb.AppendLine(";");
        }
        else
        {
            sb.Append("    ");
            EmitExpr(sb, def.Body, 1);
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    static bool HasSelfTailCall(IRDefinition def)
    {
        if (def.Parameters.Length == 0)
            return false;
        return ExprHasTailCall(def.Body, def.Name);
    }

    static bool ExprHasTailCall(IRExpr expr, string funcName)
    {
        return expr switch
        {
            IRIf iff => ExprHasTailCall(iff.Then, funcName)
                     || ExprHasTailCall(iff.Else, funcName),
            IRLet let => ExprHasTailCall(let.Body, funcName),
            IRMatch match => match.Branches.Any(b => ExprHasTailCall(b.Body, funcName)),
            IRApply app => IsSelfCall(app, funcName),
            _ => false
        };
    }

    static bool IsSelfCall(IRApply app, string funcName)
    {
        IRExpr root = app.Function;
        while (root is IRApply inner)
            root = inner.Function;
        return root is IRName name && name.Name == funcName;
    }

    void EmitTailCallDefinition(StringBuilder sb, IRDefinition def, string name)
    {
        string returnType = EmitType(GetReturnType(def));

        sb.Append($"fn {name}(");
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            IRParameter param = def.Parameters[i];
            sb.Append($"mut {Sanitize(param.Name)}: {EmitType(param.Type)}");
        }
        sb.AppendLine($") -> {returnType} {{");
        sb.AppendLine("    loop {");

        EmitTailCallBody(sb, def.Body, def.Name, def.Parameters, 2);

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    void EmitTailCallBody(
        StringBuilder sb, IRExpr expr, string funcName,
        ImmutableArray<IRParameter> parameters, int indent)
    {
        string pad = new(' ', indent * 4);

        switch (expr)
        {
            case IRIf iff:
                sb.Append($"{pad}if ");
                EmitExpr(sb, iff.Condition, indent);
                sb.AppendLine(" {");
                EmitTailCallBody(sb, iff.Then, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}} else {{");
                EmitTailCallBody(sb, iff.Else, funcName, parameters, indent + 1);
                sb.AppendLine($"{pad}}}");
                break;

            case IRLet let:
                sb.Append($"{pad}let {Sanitize(let.Name)} = ");
                EmitExpr(sb, let.Value, indent);
                sb.AppendLine(";");
                EmitTailCallBody(sb, let.Body, funcName, parameters, indent);
                break;

            case IRApply app when IsSelfCall(app, funcName):
            {
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                {
                    sb.Append($"{pad}let _tco_{i} = ");
                    EmitExpr(sb, args[i], indent);
                    sb.AppendLine(";");
                }
                for (int i = 0; i < args.Count && i < parameters.Length; i++)
                    sb.AppendLine($"{pad}{Sanitize(parameters[i].Name)} = _tco_{i};");
                sb.AppendLine($"{pad}continue;");
                break;
            }

            default:
                sb.Append($"{pad}return ");
                EmitExpr(sb, expr, indent);
                sb.AppendLine(";");
                break;
        }
    }

    void EmitExpr(StringBuilder sb, IRExpr expr, int indent)
    {
        switch (expr)
        {
            case IRIntegerLit lit:
                sb.Append($"{lit.Value}_i64");
                break;

            case IRNumberLit lit:
                sb.Append($"{lit.Value}_f64");
                break;

            case IRTextLit lit:
                sb.Append($"\"{EscapeString(lit.Value)}\".to_string()");
                break;

            case IRBoolLit lit:
                sb.Append(lit.Value ? "true" : "false");
                break;

            case IRName name:
                if (name.Name == "read-line")
                {
                    sb.Append("{ let mut s = String::new(); ");
                    sb.Append("std::io::stdin().read_line(&mut s).unwrap(); ");
                    sb.Append("s.trim().to_string() }");
                }
                else if (name.Name == "show")
                    sb.Append("|x: i64| format!(\"{}\", x)");
                else if (name.Name == "negate")
                    sb.Append("|x: i64| -x");
                else if (name.Name.Length > 0 && char.IsUpper(name.Name[0])
                    && name.Type is not FunctionType
                    && m_constructorNames.Contains(name.Name))
                {
                    string parentEnum = FindParentEnum(name.Name);
                    if (parentEnum.Length > 0)
                        sb.Append($"{Sanitize(parentEnum)}::{Sanitize(name.Name)}");
                    else
                        sb.Append(Sanitize(name.Name));
                }
                else
                    sb.Append(Sanitize(name.Name));
                break;

            case IRBinary bin:
                EmitBinary(sb, bin, indent);
                break;

            case IRNegate neg:
                sb.Append("(-");
                EmitExpr(sb, neg.Operand, indent);
                sb.Append(')');
                break;

            case IRIf iff:
                sb.Append("if ");
                EmitExpr(sb, iff.Condition, indent);
                sb.Append(" { ");
                EmitExpr(sb, iff.Then, indent);
                sb.Append(" } else { ");
                EmitExpr(sb, iff.Else, indent);
                sb.Append(" }");
                break;

            case IRLet let:
                sb.Append("{ let ");
                sb.Append(Sanitize(let.Name));
                sb.Append(" = ");
                EmitExpr(sb, let.Value, indent);
                sb.Append("; ");
                EmitExpr(sb, let.Body, indent);
                sb.Append(" }");
                break;

            case IRApply app:
                EmitApply(sb, app, indent);
                break;

            case IRLambda lam:
                sb.Append('|');
                for (int i = 0; i < lam.Parameters.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(
                        $"{Sanitize(lam.Parameters[i].Name)}: {EmitType(lam.Parameters[i].Type)}");
                }
                sb.Append("| ");
                EmitExpr(sb, lam.Body, indent);
                break;

            case IRList list:
                sb.Append("vec![");

                for (int i = 0; i < list.Elements.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, list.Elements[i], indent);
                }
                sb.Append(']');
                break;

            case IRMatch match:
                EmitMatch(sb, match, indent);
                break;

            case IRDo doExpr:
                EmitDoExpr(sb, doExpr, indent);
                break;

            case IRRecord rec:
                sb.Append($"{Sanitize(rec.TypeName)} {{ ");
                for (int i = 0; i < rec.Fields.Length; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append($"{Sanitize(rec.Fields[i].FieldName)}: ");
                    EmitExpr(sb, rec.Fields[i].Value, indent);
                }
                sb.Append(" }");
                break;

            case IRFieldAccess fa:
                EmitExpr(sb, fa.Record, indent);
                sb.Append('.');
                sb.Append(Sanitize(fa.FieldName));
                break;

            case IRError err:
                sb.Append($"panic!(\"{EscapeString(err.Message)}\")");
                break;

            default:
                sb.Append("todo!()");
                break;
        }
    }

    void EmitApply(StringBuilder sb, IRApply app, int indent)
    {
        if (app.Function is IRName fn && fn.Name == "show")
        {
            sb.Append("format!(\"{}\", ");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn2 && fn2.Name == "negate")
        {
            sb.Append("(-");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn3 && fn3.Name == "print-line")
        {
            sb.Append("println!(\"{}\", ");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn4 && fn4.Name == "open-file")
        {
            sb.Append("std::fs::File::open(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(").unwrap()");
        }
        else if (app.Function is IRName fn5 && fn5.Name == "read-all")
        {
            sb.Append("{ use std::io::Read; let mut s = String::new(); ");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".read_to_string(&mut s).unwrap(); s }");
        }
        else if (app.Function is IRName fn6 && fn6.Name == "close-file")
        {
            sb.Append("drop(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(')');
        }
        else if (app.Function is IRName fn7 && fn7.Name == "text-length")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".len() as i64");
        }
        else if (app.Function is IRName fn8 && fn8.Name == "is-letter")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".chars().next().map_or(false, |c| c.is_alphabetic())");
        }
        else if (app.Function is IRName fn9 && fn9.Name == "is-digit")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".chars().next().map_or(false, |c| c.is_ascii_digit())");
        }
        else if (app.Function is IRName fn10 && fn10.Name == "is-whitespace")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".chars().next().map_or(false, |c| c.is_whitespace())");
        }
        else if (app.Function is IRName fn11 && fn11.Name == "text-to-integer")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".parse::<i64>().unwrap()");
        }
        else if (app.Function is IRName fn11b && fn11b.Name == "integer-to-text")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".to_string()");
        }
        else if (app.Function is IRName fn12 && fn12.Name == "char-code")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".chars().next().unwrap() as i64");
        }
        else if (app.Function is IRName fn13 && fn13.Name == "code-to-char")
        {
            sb.Append("String::from(char::from_u32(");
            EmitExpr(sb, app.Argument, indent);
            sb.Append(" as u32).unwrap())");
        }
        else if (app.Function is IRName fn14 && fn14.Name == "list-length")
        {
            EmitExpr(sb, app.Argument, indent);
            sb.Append(".len() as i64");
        }
        else if (TryEmitMultiArgBuiltin(sb, app, indent))
        {
        }
        else
        {
            string? ctorName = FindConstructorName(app);
            if (ctorName is not null)
            {
                string parentEnum = FindParentEnum(ctorName);
                List<IRExpr> args = [];
                CollectApplyArgs(app, args);
                if (parentEnum.Length > 0)
                    sb.Append($"{Sanitize(parentEnum)}::{Sanitize(ctorName)}(");
                else
                    sb.Append($"{Sanitize(ctorName)}(");
                for (int i = 0; i < args.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    EmitExpr(sb, args[i], indent);
                }
                sb.Append(')');
            }
            else
            {
                string? defName = FindDefinitionName(app);
                if (defName is not null
                    && m_definitionArity.TryGet(defName, out int arity)
                    && arity > 1)
                {
                    List<IRExpr> args = [];
                    CollectApplyArgs(app, args);
                    if (args.Count == arity)
                    {
                        sb.Append(Sanitize(defName));
                        sb.Append('(');
                        for (int i = 0; i < args.Count; i++)
                        {
                            if (i > 0) sb.Append(", ");
                            EmitExpr(sb, args[i], indent);
                        }
                        sb.Append(')');
                    }
                    else
                    {
                        EmitExpr(sb, app.Function, indent);
                        sb.Append('(');
                        EmitExpr(sb, app.Argument, indent);
                        sb.Append(')');
                    }
                }
                else
                {
                    EmitExpr(sb, app.Function, indent);
                    sb.Append('(');
                    EmitExpr(sb, app.Argument, indent);
                    sb.Append(')');
                }
            }
        }
    }

    void EmitBinary(StringBuilder sb, IRBinary bin, int indent)
    {
        switch (bin.Op)
        {
            case IRBinaryOp.AppendText:
                sb.Append("format!(\"{}{}\", ");
                EmitExpr(sb, bin.Left, indent);
                sb.Append(", ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;

            case IRBinaryOp.AppendList:
                sb.Append("{ let mut v = ");
                EmitExpr(sb, bin.Left, indent);
                sb.Append(".clone(); v.extend(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(".iter().cloned()); v }");
                break;

            case IRBinaryOp.ConsList:
                sb.Append("{ let mut v = vec![");
                EmitExpr(sb, bin.Left, indent);
                sb.Append("]; v.extend(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(".iter().cloned()); v }");
                break;

            case IRBinaryOp.PowInt:
                EmitExpr(sb, bin.Left, indent);
                sb.Append(".pow(");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(" as u32)");
                break;

            default:
                string op = bin.Op switch
                {
                    IRBinaryOp.AddInt or IRBinaryOp.AddNum => "+",
                    IRBinaryOp.SubInt or IRBinaryOp.SubNum => "-",
                    IRBinaryOp.MulInt or IRBinaryOp.MulNum => "*",
                    IRBinaryOp.DivInt or IRBinaryOp.DivNum => "/",
                    IRBinaryOp.Eq => "==",
                    IRBinaryOp.NotEq => "!=",
                    IRBinaryOp.Lt => "<",
                    IRBinaryOp.Gt => ">",
                    IRBinaryOp.LtEq => "<=",
                    IRBinaryOp.GtEq => ">=",
                    IRBinaryOp.And => "&&",
                    IRBinaryOp.Or => "||",
                    _ => "+"
                };
                sb.Append('(');
                EmitExpr(sb, bin.Left, indent);
                sb.Append($" {op} ");
                EmitExpr(sb, bin.Right, indent);
                sb.Append(')');
                break;
        }
    }

    void EmitMatch(StringBuilder sb, IRMatch match, int indent)
    {
        sb.Append("match ");
        EmitExpr(sb, match.Scrutinee, indent);
        sb.AppendLine(" {");
        string pad = new(' ', (indent + 1) * 4);

        foreach (IRMatchBranch branch in match.Branches)
        {
            sb.Append(pad);
            switch (branch.Pattern)
            {
                case IRLiteralPattern litPat:
                    sb.Append(litPat.Value switch
                    {
                        bool b => b ? "true" : "false",
                        long l => $"{l}_i64",
                        string s => $"\"{EscapeString(s)}\"",
                        _ => "_"
                    });
                    break;

                case IRCtorPattern ctorPat:
                    string parentEnum = FindParentEnum(ctorPat.Name);
                    if (parentEnum.Length > 0)
                        sb.Append($"{Sanitize(parentEnum)}::");
                    sb.Append(Sanitize(ctorPat.Name));
                    if (ctorPat.SubPatterns.Length > 0)
                    {
                        sb.Append('(');
                        for (int i = 0; i < ctorPat.SubPatterns.Length; i++)
                        {
                            if (i > 0) sb.Append(", ");
                            if (ctorPat.SubPatterns[i] is IRVarPattern vp)
                                sb.Append(Sanitize(vp.Name));
                            else
                                sb.Append('_');
                        }
                        sb.Append(')');
                    }
                    break;

                case IRVarPattern varPat:
                    sb.Append(Sanitize(varPat.Name));
                    break;

                case IRWildcardPattern:
                    sb.Append('_');
                    break;
            }

            sb.Append(" => ");
            EmitExpr(sb, branch.Body, indent + 1);
            sb.AppendLine(",");
        }

        sb.Append(new string(' ', indent * 4));
        sb.Append('}');
    }

    void EmitDoExpr(StringBuilder sb, IRDo doExpr, int indent)
    {
        sb.AppendLine("{");
        string pad = new(' ', (indent + 1) * 4);
        foreach (IRDoStatement stmt in doExpr.Statements)
        {
            switch (stmt)
            {
                case IRDoBind bind:
                    sb.Append(pad);
                    sb.Append($"let {Sanitize(bind.Name)} = ");
                    EmitExpr(sb, bind.Value, indent + 1);
                    sb.AppendLine(";");
                    break;
                case IRDoExec exec:
                    sb.Append(pad);
                    EmitExpr(sb, exec.Expression, indent + 1);
                    sb.AppendLine(";");
                    break;
            }
        }
        sb.Append(new string(' ', indent * 4));
        sb.Append('}');
    }

    static string EmitType(CodexType type)
    {
        return type switch
        {
            IntegerType => "i64",
            NumberType => "f64",
            TextType => "String",
            BooleanType => "bool",
            NothingType => "()",
            VoidType => "()",
            EffectfulType eft => EmitType(eft.Return),
            LinearType lin => EmitType(lin.Inner),
            FunctionType ft => $"Box<dyn Fn({EmitType(ft.Parameter)}) -> {EmitType(ft.Return)}>",
            DependentFunctionType dep =>
                $"Box<dyn Fn({EmitType(dep.ParamType)}) -> {EmitType(dep.Body)}>",
            ListType lt => $"Vec<{EmitType(lt.Element)}>",
            SumType st => Sanitize(st.TypeName.Value),
            RecordType rt => Sanitize(rt.TypeName.Value),
            ConstructedType ct => Sanitize(ct.Constructor.Value),
            TypeLevelValue => "i64",
            TypeLevelVar => "i64",
            TypeLevelBinary => "i64",
            ProofType => "()",
            TypeVariable => "Box<dyn std::any::Any>",
            ErrorType => "Box<dyn std::any::Any>",
            _ => "Box<dyn std::any::Any>"
        };
    }

    static CodexType GetReturnType(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType)
                type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType)
            type = pft2.Return;
        if (type is EffectfulType eft) type = eft.Return;
        return type;
    }

    static bool IsEffectfulDefinition(IRDefinition def)
    {
        CodexType type = def.Type;
        for (int i = 0; i < def.Parameters.Length; i++)
        {
            while (type is FunctionType pft && pft.Parameter is ProofType)
                type = pft.Return;
            if (type is FunctionType ft) type = ft.Return;
            else if (type is DependentFunctionType dep) type = dep.Body;
            else break;
        }
        while (type is FunctionType pft2 && pft2.Parameter is ProofType)
            type = pft2.Return;
        return type is EffectfulType;
    }

    string FindParentEnum(string constructorName)
    {
        string? parent = m_constructorToEnum[constructorName];
        return parent ?? "";
    }

    static Map<string, string> BuildConstructorToEnumMap(IRModule module)
    {
        Map<string, string> map = Map<string, string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            if (kv.Value is SumType sum)
            {
                foreach (SumConstructorType ctor in sum.Constructors)
                    map = map.Set(ctor.Name.Value, sum.TypeName.Value);
            }
        }
        return map;
    }

    static string? FindConstructorName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && name.Name.Length > 0 && char.IsUpper(name.Name[0]))
            return name.Name;
        return null;
    }

    static string? FindDefinitionName(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && name.Name.Length > 0 && char.IsLower(name.Name[0]))
            return name.Name;
        return null;
    }

    static void CollectApplyArgs(IRApply app, List<IRExpr> args)
    {
        if (app.Function is IRApply inner)
            CollectApplyArgs(inner, args);
        args.Add(app.Argument);
    }

    static readonly Set<string> s_multiArgBuiltins = Set<string>.Of("char-at", "substring", "list-at", "text-replace");

    static string? FindBuiltinRoot(IRApply app)
    {
        IRExpr current = app.Function;
        while (current is IRApply inner)
            current = inner.Function;
        if (current is IRName name && s_multiArgBuiltins.Contains(name.Name))
            return name.Name;
        return null;
    }

    bool TryEmitMultiArgBuiltin(StringBuilder sb, IRApply app, int indent)
    {
        string? name = FindBuiltinRoot(app);
        if (name is null) return false;

        List<IRExpr> args = [];
        CollectApplyArgs(app, args);

        switch (name)
        {
            case "char-at" when args.Count == 2:
                EmitExpr(sb, args[0], indent);
                sb.Append(".chars().nth(");
                EmitExpr(sb, args[1], indent);
                sb.Append(" as usize).unwrap().to_string()");
                return true;

            case "substring" when args.Count == 3:
                sb.Append("{ let s = &");
                EmitExpr(sb, args[0], indent);
                sb.Append("; s.chars().skip(");
                EmitExpr(sb, args[1], indent);
                sb.Append(" as usize).take(");
                EmitExpr(sb, args[2], indent);
                sb.Append(" as usize).collect::<String>() }");
                return true;

            case "list-at" when args.Count == 2:
                EmitExpr(sb, args[0], indent);
                sb.Append("[");
                EmitExpr(sb, args[1], indent);
                sb.Append(" as usize].clone()");
                return true;

            case "text-replace" when args.Count == 3:
                EmitExpr(sb, args[0], indent);
                sb.Append(".replace(&");
                EmitExpr(sb, args[1], indent);
                sb.Append(", &");
                EmitExpr(sb, args[2], indent);
                sb.Append(')');
                return true;

            default:
                return false;
        }
    }

    static Set<string> CollectConstructorNames(IRModule module)
    {
        Set<string> names = Set<string>.s_empty;
        foreach (KeyValuePair<string, CodexType> kv in module.TypeDefinitions)
        {
            if (kv.Value is SumType sum)
            {
                foreach (SumConstructorType ctor in sum.Constructors)
                    names = names.Add(ctor.Name.Value);
            }
        }
        return names;
    }

    static string Sanitize(string name)
    {
        string sanitized = name.Replace('-', '_');
        return sanitized switch
        {
            "fn" or "let" or "mut" or "pub" or "struct" or "enum" or "impl" or "trait"
            or "type" or "use" or "mod" or "crate" or "self" or "super" or "where"
            or "match" or "if" or "else" or "for" or "while" or "loop" or "break"
            or "continue" or "return" or "move" or "ref" or "as" or "in" or "true"
            or "false" or "const" or "static" or "unsafe" or "extern" or "async"
            or "await" or "dyn" or "abstract" or "become" or "box" or "do" or "final"
            or "macro" or "override" or "priv" or "try" or "typeof" or "virtual"
            or "yield"
                => $"r#{sanitized}",
            _ => sanitized
        };
    }

    static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
